// Code generated by protoc-gen-go.
// source: shuiguoji.proto
// DO NOT EDIT!

package bbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from base.proto

// Ignoring public import of TerminalInfo from base.proto

// Ignoring public import of EUnitType from base.proto

// Ignoring public import of EUnitRace from base.proto

type Shuiguoji struct {
	ProtoHeader *ProtoHeader `protobuf:"bytes,1,opt,name=ProtoHeader" json:"ProtoHeader,omitempty"`
	Type        *int32       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	// 押注
	ScoresBet *int32 `protobuf:"varint,3,opt,name=scoresBet" json:"scoresBet,omitempty"`
	ScoresWin *int32 `protobuf:"varint,4,opt,name=scoresWin" json:"scoresWin,omitempty"`
	// 押注的分数
	ScoresApple      *int32 `protobuf:"varint,5,opt,name=scoresApple" json:"scoresApple,omitempty"`
	ScoresOrange     *int32 `protobuf:"varint,6,opt,name=scoresOrange" json:"scoresOrange,omitempty"`
	ScoresMango      *int32 `protobuf:"varint,7,opt,name=scoresMango" json:"scoresMango,omitempty"`
	ScoresBell       *int32 `protobuf:"varint,8,opt,name=scoresBell" json:"scoresBell,omitempty"`
	ScoresWatermelon *int32 `protobuf:"varint,9,opt,name=scoresWatermelon" json:"scoresWatermelon,omitempty"`
	ScoresStar       *int32 `protobuf:"varint,10,opt,name=scoresStar" json:"scoresStar,omitempty"`
	Scores77         *int32 `protobuf:"varint,11,opt,name=scores77" json:"scores77,omitempty"`
	ScoresBar        *int32 `protobuf:"varint,12,opt,name=scoresBar" json:"scoresBar,omitempty"`
	// 大小
	ScoresHilomp     *int32 `protobuf:"varint,13,opt,name=scoresHilomp" json:"scoresHilomp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Shuiguoji) Reset()                    { *m = Shuiguoji{} }
func (m *Shuiguoji) String() string            { return proto.CompactTextString(m) }
func (*Shuiguoji) ProtoMessage()               {}
func (*Shuiguoji) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *Shuiguoji) GetProtoHeader() *ProtoHeader {
	if m != nil {
		return m.ProtoHeader
	}
	return nil
}

func (m *Shuiguoji) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Shuiguoji) GetScoresBet() int32 {
	if m != nil && m.ScoresBet != nil {
		return *m.ScoresBet
	}
	return 0
}

func (m *Shuiguoji) GetScoresWin() int32 {
	if m != nil && m.ScoresWin != nil {
		return *m.ScoresWin
	}
	return 0
}

func (m *Shuiguoji) GetScoresApple() int32 {
	if m != nil && m.ScoresApple != nil {
		return *m.ScoresApple
	}
	return 0
}

func (m *Shuiguoji) GetScoresOrange() int32 {
	if m != nil && m.ScoresOrange != nil {
		return *m.ScoresOrange
	}
	return 0
}

func (m *Shuiguoji) GetScoresMango() int32 {
	if m != nil && m.ScoresMango != nil {
		return *m.ScoresMango
	}
	return 0
}

func (m *Shuiguoji) GetScoresBell() int32 {
	if m != nil && m.ScoresBell != nil {
		return *m.ScoresBell
	}
	return 0
}

func (m *Shuiguoji) GetScoresWatermelon() int32 {
	if m != nil && m.ScoresWatermelon != nil {
		return *m.ScoresWatermelon
	}
	return 0
}

func (m *Shuiguoji) GetScoresStar() int32 {
	if m != nil && m.ScoresStar != nil {
		return *m.ScoresStar
	}
	return 0
}

func (m *Shuiguoji) GetScores77() int32 {
	if m != nil && m.Scores77 != nil {
		return *m.Scores77
	}
	return 0
}

func (m *Shuiguoji) GetScoresBar() int32 {
	if m != nil && m.ScoresBar != nil {
		return *m.ScoresBar
	}
	return 0
}

func (m *Shuiguoji) GetScoresHilomp() int32 {
	if m != nil && m.ScoresHilomp != nil {
		return *m.ScoresHilomp
	}
	return 0
}

func init() {
	proto.RegisterType((*Shuiguoji)(nil), "bbproto.Shuiguoji")
}

var fileDescriptor7 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0xce, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x61, 0x5a, 0x5a, 0xda, 0x9c, 0x83, 0x28, 0xa6, 0xc3, 0x89, 0x09, 0x31, 0xc1, 0x92,
	0x81, 0xa5, 0x33, 0x4c, 0x5d, 0x10, 0x91, 0x32, 0x30, 0x3b, 0x70, 0x0a, 0x46, 0x4e, 0x6c, 0xd9,
	0xce, 0xc0, 0x13, 0xf1, 0x9a, 0x24, 0x76, 0x22, 0xe1, 0x6e, 0xd6, 0xe7, 0xff, 0x74, 0x07, 0x57,
	0xee, 0xab, 0x97, 0x4d, 0xaf, 0xbf, 0x65, 0x61, 0xac, 0xf6, 0x9a, 0x6f, 0xea, 0x3a, 0x3c, 0x6e,
	0xa1, 0x16, 0x8e, 0x22, 0xde, 0xff, 0x2e, 0x21, 0xab, 0xe6, 0x90, 0x3f, 0x02, 0x2b, 0x47, 0x3e,
	0x92, 0xf8, 0x24, 0x8b, 0x8b, 0xbb, 0xc5, 0x03, 0x7b, 0xda, 0x17, 0xd3, 0x60, 0xf1, 0xef, 0x8f,
	0xe7, 0xb0, 0xf2, 0x3f, 0x86, 0x70, 0x39, 0x34, 0x6b, 0x7e, 0x0d, 0x99, 0xfb, 0xd0, 0x96, 0xdc,
	0x0b, 0x79, 0x3c, 0x4f, 0xe9, 0x5d, 0x76, 0xb8, 0x0a, 0x74, 0x03, 0x2c, 0xd2, 0xb3, 0x31, 0x8a,
	0x70, 0x1d, 0x70, 0x0f, 0x79, 0xc4, 0x37, 0x2b, 0xba, 0x86, 0xf0, 0x22, 0x4d, 0x5f, 0x07, 0xd4,
	0xb8, 0x09, 0xc8, 0x01, 0xe6, 0x2d, 0x4a, 0xe1, 0x36, 0x18, 0xc2, 0x6e, 0x5a, 0x23, 0x3c, 0xd9,
	0x96, 0x94, 0xee, 0x30, 0x4b, 0xeb, 0xca, 0x0b, 0x8b, 0x10, 0x6c, 0x07, 0xdb, 0x68, 0x87, 0x03,
	0xb2, 0x93, 0xcb, 0x87, 0x28, 0x4f, 0x2f, 0x3a, 0x4a, 0xa5, 0x5b, 0x83, 0x97, 0xa3, 0x96, 0x67,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0x24, 0x14, 0x63, 0x52, 0x01, 0x00, 0x00,
}
