// Code generated by protoc-gen-go.
// source: ddz_server.proto
// DO NOT EDIT!

/*
Package doudizhu is a generated protocol buffer package.

It is generated from these files:
	ddz_server.proto

It has these top-level messages:
	PPokerPai
	PDdzDesk
	PDdzUser
	PDdzRoom
	PDdzbak
	PDdzSession
*/
package doudizhu

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 牌 ,单张扑克牌
type PPokerPai struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PPokerPai) Reset()                    { *m = PPokerPai{} }
func (m *PPokerPai) String() string            { return proto.CompactTextString(m) }
func (*PPokerPai) ProtoMessage()               {}
func (*PPokerPai) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// desk
type PDdzDesk struct {
	DeskId           *int32  `protobuf:"varint,1,opt,name=deskId" json:"deskId,omitempty"`
	Key              *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PDdzDesk) Reset()                    { *m = PDdzDesk{} }
func (m *PDdzDesk) String() string            { return proto.CompactTextString(m) }
func (*PDdzDesk) ProtoMessage()               {}
func (*PDdzDesk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PDdzDesk) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *PDdzDesk) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// user
type PDdzUser struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PDdzUser) Reset()                    { *m = PDdzUser{} }
func (m *PDdzUser) String() string            { return proto.CompactTextString(m) }
func (*PDdzUser) ProtoMessage()               {}
func (*PDdzUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// room
type PDdzRoom struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PDdzRoom) Reset()                    { *m = PDdzRoom{} }
func (m *PDdzRoom) String() string            { return proto.CompactTextString(m) }
func (*PDdzRoom) ProtoMessage()               {}
func (*PDdzRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 备份专用...
type PDdzbak struct {
	Desk             *PDdzDesk   `protobuf:"bytes,1,opt,name=desk" json:"desk,omitempty"`
	Users            []*PDdzUser `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PDdzbak) Reset()                    { *m = PDdzbak{} }
func (m *PDdzbak) String() string            { return proto.CompactTextString(m) }
func (*PDdzbak) ProtoMessage()               {}
func (*PDdzbak) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PDdzbak) GetDesk() *PDdzDesk {
	if m != nil {
		return m.Desk
	}
	return nil
}

func (m *PDdzbak) GetUsers() []*PDdzUser {
	if m != nil {
		return m.Users
	}
	return nil
}

// session
type PDdzSession struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	RoomId           *int32  `protobuf:"varint,2,opt,name=RoomId" json:"RoomId,omitempty"`
	DeskId           *int32  `protobuf:"varint,3,opt,name=DeskId" json:"DeskId,omitempty"`
	GameStatus       *int32  `protobuf:"varint,4,opt,name=GameStatus" json:"GameStatus,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PDdzSession) Reset()                    { *m = PDdzSession{} }
func (m *PDdzSession) String() string            { return proto.CompactTextString(m) }
func (*PDdzSession) ProtoMessage()               {}
func (*PDdzSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PDdzSession) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PDdzSession) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *PDdzSession) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *PDdzSession) GetGameStatus() int32 {
	if m != nil && m.GameStatus != nil {
		return *m.GameStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*PPokerPai)(nil), "doudizhu.PPokerPai")
	proto.RegisterType((*PDdzDesk)(nil), "doudizhu.PDdzDesk")
	proto.RegisterType((*PDdzUser)(nil), "doudizhu.PDdzUser")
	proto.RegisterType((*PDdzRoom)(nil), "doudizhu.PDdzRoom")
	proto.RegisterType((*PDdzbak)(nil), "doudizhu.PDdzbak")
	proto.RegisterType((*PDdzSession)(nil), "doudizhu.PDdzSession")
}

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8e, 0x3f, 0x6b, 0xc3, 0x30,
	0x10, 0xc5, 0xf1, 0xbf, 0xd6, 0x3e, 0xd1, 0x52, 0x34, 0x79, 0x74, 0xb5, 0xb4, 0x93, 0x87, 0x7e,
	0x06, 0x43, 0xe9, 0x52, 0x94, 0x98, 0xcc, 0x41, 0x41, 0x82, 0x18, 0xe1, 0x28, 0x48, 0x56, 0x20,
	0xfe, 0xf4, 0xd1, 0xc9, 0x71, 0x96, 0x4c, 0xf7, 0x7e, 0xc7, 0xdd, 0x7b, 0x0f, 0x3e, 0xa4, 0x9c,
	0xf7, 0x4e, 0xd9, 0x8b, 0xb2, 0xed, 0xd9, 0x9a, 0xc9, 0xd0, 0x52, 0x1a, 0x2f, 0x87, 0xf9, 0xe8,
	0x19, 0x81, 0x8a, 0x73, 0xa3, 0x95, 0xe5, 0x62, 0x60, 0x5f, 0x50, 0xf2, 0x4e, 0xce, 0x9d, 0x72,
	0x9a, 0xbe, 0xc3, 0x8b, 0x0c, 0xf3, 0x4f, 0xd6, 0x49, 0x93, 0x7c, 0x17, 0x94, 0x40, 0xa6, 0xd5,
	0xb5, 0x4e, 0x03, 0x54, 0x0c, 0x96, 0xc3, 0x5d, 0x30, 0x5d, 0xf5, 0xd6, 0x98, 0x91, 0xfd, 0xc3,
	0x2b, 0xea, 0x83, 0xd0, 0xb4, 0x81, 0x1c, 0xff, 0xe3, 0x37, 0xf9, 0xa1, 0xed, 0x9a, 0xd8, 0x3e,
	0x12, 0x3e, 0xa1, 0xf0, 0xc1, 0xc0, 0x05, 0xcf, 0xec, 0xf9, 0x24, 0x7a, 0x6f, 0x80, 0xa0, 0xee,
	0x95, 0x73, 0x83, 0x39, 0x61, 0x27, 0x5c, 0xdf, 0x3b, 0xbd, 0x21, 0x63, 0x6c, 0xe0, 0x34, 0x76,
	0x0c, 0xdc, 0x2d, 0x9d, 0xb3, 0xc8, 0x14, 0xe0, 0x57, 0x8c, 0xaa, 0x9f, 0xc4, 0xe4, 0x5d, 0x9d,
	0xe3, 0xee, 0x16, 0x00, 0x00, 0xff, 0xff, 0x45, 0x4e, 0x96, 0xe9, 0x0d, 0x01, 0x00, 0x00,
}
