// Code generated by protoc-gen-go.
// source: roomProto.proto
// DO NOT EDIT!

/*
Package mjroom is a generated protocol buffer package.

It is generated from these files:
	roomProto.proto

It has these top-level messages:
	MjDesk
	MjUser
*/
package mjroom

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 麻将牌的结构
type MjDesk struct {
	DeskId           *int32 `protobuf:"varint,1,opt,name=DeskId" json:"DeskId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MjDesk) Reset()                    { *m = MjDesk{} }
func (m *MjDesk) String() string            { return proto.CompactTextString(m) }
func (*MjDesk) ProtoMessage()               {}
func (*MjDesk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MjDesk) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

// 手里的一副牌
type MjUser struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MjUser) Reset()                    { *m = MjUser{} }
func (m *MjUser) String() string            { return proto.CompactTextString(m) }
func (*MjUser) ProtoMessage()               {}
func (*MjUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MjUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*MjDesk)(nil), "mjroom.MjDesk")
	proto.RegisterType((*MjUser)(nil), "mjroom.MjUser")
}

var fileDescriptor0 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xca, 0xcf, 0xcf,
	0x0d, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0x6c, 0xb9, 0x59, 0x20, 0x21, 0x25,
	0x09, 0x2e, 0x36, 0xdf, 0x2c, 0x97, 0xd4, 0xe2, 0x6c, 0x21, 0x3e, 0x2e, 0x36, 0x10, 0xed, 0x99,
	0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x0a, 0x91, 0x09, 0x2d, 0x4e, 0x2d, 0x02, 0xc9, 0x80, 0x68,
	0xa8, 0x0c, 0x2f, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xee, 0x67, 0x54, 0x4d, 0x00, 0x00, 0x00,
}
