#!/bin/sh
TARGET_PROTO_PATH=/Users/kory/Documents/Dev/cocos2d-x-3.12/casino/TexasPoker/Protocols/


mkdir -p ./OutCpp
rm -f OutCpp/*

cp ../MatchList.proto ./MatchList.proto
cp ../TexasGame.proto ./TexasGame.proto
cp ../base.proto ./

sed -i '' 's/package bbproto;//g' *.proto
cp -vf ./*.proto ${TARGET_PROTO_PATH}/protobuf/


protoc --proto_path=./ --cpp_out=./OutCpp *.proto
cd OutCpp
ls -lrt *
cp -vf * ${TARGET_PROTO_PATH}
