// Code generated by protoc-gen-go.
// source: casinoCommonProto.proto
// DO NOT EDIT!

/*
Package casinoCommonProto is a generated protocol buffer package.

It is generated from these files:
	casinoCommonProto.proto

It has these top-level messages:
	User
*/
package casinoCommonProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Mid                *string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
	Pwd                *string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	Coin               *int64  `protobuf:"varint,3,opt,name=coin" json:"coin,omitempty"`
	Id                 *uint32 `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	NickName           *string `protobuf:"bytes,5,opt,name=nickName" json:"nickName,omitempty"`
	LoginTurntable     *bool   `protobuf:"varint,6,opt,name=loginTurntable" json:"loginTurntable,omitempty"`
	LoginTurntableTime *string `protobuf:"bytes,7,opt,name=loginTurntableTime" json:"loginTurntableTime,omitempty"`
	Scores             *int32  `protobuf:"varint,8,opt,name=scores" json:"scores,omitempty"`
	LastSignTime       *string `protobuf:"bytes,9,opt,name=lastSignTime" json:"lastSignTime,omitempty"`
	SignCount          *int32  `protobuf:"varint,10,opt,name=signCount" json:"signCount,omitempty"`
	Diamond            *int64  `protobuf:"varint,11,opt,name=Diamond" json:"Diamond,omitempty"`
	OpenId             *string `protobuf:"bytes,12,opt,name=openId" json:"openId,omitempty"`
	HeadUrl            *string `protobuf:"bytes,13,opt,name=headUrl" json:"headUrl,omitempty"`
	City               *string `protobuf:"bytes,14,opt,name=city" json:"city,omitempty"`
	Sex                *int32  `protobuf:"varint,15,opt,name=sex" json:"sex,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetMid() string {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *User) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *User) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *User) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *User) GetLoginTurntable() bool {
	if m != nil && m.LoginTurntable != nil {
		return *m.LoginTurntable
	}
	return false
}

func (m *User) GetLoginTurntableTime() string {
	if m != nil && m.LoginTurntableTime != nil {
		return *m.LoginTurntableTime
	}
	return ""
}

func (m *User) GetScores() int32 {
	if m != nil && m.Scores != nil {
		return *m.Scores
	}
	return 0
}

func (m *User) GetLastSignTime() string {
	if m != nil && m.LastSignTime != nil {
		return *m.LastSignTime
	}
	return ""
}

func (m *User) GetSignCount() int32 {
	if m != nil && m.SignCount != nil {
		return *m.SignCount
	}
	return 0
}

func (m *User) GetDiamond() int64 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *User) GetOpenId() string {
	if m != nil && m.OpenId != nil {
		return *m.OpenId
	}
	return ""
}

func (m *User) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "casinoCommonProto.User")
}

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0x4e, 0xc3, 0x30,
	0x10, 0x44, 0xd5, 0x24, 0x6d, 0x93, 0x6d, 0x9a, 0x52, 0x0b, 0xc1, 0x8a, 0x13, 0xe2, 0xc4, 0x89,
	0x9f, 0x28, 0x17, 0x2e, 0x08, 0x89, 0xf6, 0x03, 0x4c, 0x62, 0x95, 0x15, 0xc9, 0x6e, 0x64, 0xbb,
	0x02, 0x7e, 0x80, 0xef, 0x66, 0x63, 0x09, 0x24, 0xc4, 0xc5, 0xf2, 0x8c, 0xdf, 0x8c, 0x3c, 0x70,
	0xd9, 0xda, 0x40, 0x2c, 0x3b, 0x19, 0x06, 0xe1, 0x27, 0x2f, 0x51, 0xee, 0xc6, 0xe9, 0x34, 0xdb,
	0x7f, 0x0f, 0x37, 0x5f, 0x19, 0x14, 0x87, 0xe0, 0xbc, 0x59, 0x41, 0x3e, 0x50, 0x87, 0xb3, 0xeb,
	0xd9, 0x6d, 0x35, 0x89, 0xf1, 0xbd, 0xc3, 0x2c, 0x89, 0x1a, 0x8a, 0x56, 0x88, 0x31, 0x57, 0x95,
	0x1b, 0x80, 0x4c, 0xb1, 0x42, 0xef, 0x6b, 0x73, 0x06, 0x25, 0x53, 0xfb, 0xf6, 0x68, 0x07, 0x87,
	0xf3, 0xc4, 0x5e, 0x40, 0xd3, 0xcb, 0x91, 0x78, 0x7f, 0xf2, 0x1c, 0xed, 0x4b, 0xef, 0x70, 0xa1,
	0x7e, 0x69, 0xae, 0xc0, 0xfc, 0xf5, 0xf7, 0xa4, 0x99, 0x65, 0xca, 0x34, 0xb0, 0x08, 0xad, 0x78,
	0x17, 0xb0, 0x54, 0x3d, 0x37, 0xe7, 0x50, 0xf7, 0x36, 0xc4, 0x67, 0x3a, 0x72, 0xa2, 0xaa, 0x44,
	0x6d, 0xa1, 0x0a, 0xea, 0xec, 0xe4, 0xc4, 0x11, 0x21, 0x81, 0x1b, 0x58, 0xde, 0x93, 0xd5, 0x29,
	0x1d, 0xae, 0xd2, 0xdf, 0xb4, 0x49, 0x46, 0xc7, 0x0f, 0x1d, 0xd6, 0x29, 0xa3, 0xc0, 0xab, 0xb3,
	0xdd, 0xc1, 0xf7, 0xb8, 0xfe, 0x9d, 0x42, 0xf1, 0x13, 0x9b, 0x9f, 0x95, 0xc1, 0x7d, 0xe0, 0x66,
	0x2a, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x92, 0x1c, 0xca, 0x35, 0x01, 0x00, 0x00,
}
