// Code generated by protoc-gen-go.
// source: mahjong_server.proto
// DO NOT EDIT!

/*
Package majiang is a generated protocol buffer package.

It is generated from these files:
	mahjong_server.proto

It has these top-level messages:
	MJPai
	MJHandPai
	HuPaiInfo
	GangPaiInfo
	GuoHuInfo
	PlayerGameData
	CheckBean
	CheckCase
	MjDesk
	BillBean
	Bill
	StatiscRound
	MjUserStatisc
	MjUser
	MjSession
	MjRoom
	RunningDeskKeys
*/
package majiang

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 麻将牌的结构
type MJPai struct {
	Index            *int32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Flower           *int32  `protobuf:"varint,2,opt,name=flower" json:"flower,omitempty"`
	Value            *int32  `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	Des              *string `protobuf:"bytes,4,opt,name=des" json:"des,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MJPai) Reset()                    { *m = MJPai{} }
func (m *MJPai) String() string            { return proto.CompactTextString(m) }
func (*MJPai) ProtoMessage()               {}
func (*MJPai) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MJPai) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *MJPai) GetFlower() int32 {
	if m != nil && m.Flower != nil {
		return *m.Flower
	}
	return 0
}

func (m *MJPai) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *MJPai) GetDes() string {
	if m != nil && m.Des != nil {
		return *m.Des
	}
	return ""
}

// 手里的一副牌
type MJHandPai struct {
	Pais             []*MJPai `protobuf:"bytes,1,rep,name=Pais" json:"Pais,omitempty"`
	PengPais         []*MJPai `protobuf:"bytes,2,rep,name=PengPais" json:"PengPais,omitempty"`
	GangPais         []*MJPai `protobuf:"bytes,3,rep,name=GangPais" json:"GangPais,omitempty"`
	HuPais           []*MJPai `protobuf:"bytes,4,rep,name=HuPais" json:"HuPais,omitempty"`
	InPai            *MJPai   `protobuf:"bytes,5,opt,name=inPai" json:"inPai,omitempty"`
	QueFlower        *int32   `protobuf:"varint,6,opt,name=queFlower" json:"queFlower,omitempty"`
	OutPais          []*MJPai `protobuf:"bytes,7,rep,name=OutPais" json:"OutPais,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MJHandPai) Reset()                    { *m = MJHandPai{} }
func (m *MJHandPai) String() string            { return proto.CompactTextString(m) }
func (*MJHandPai) ProtoMessage()               {}
func (*MJHandPai) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MJHandPai) GetPais() []*MJPai {
	if m != nil {
		return m.Pais
	}
	return nil
}

func (m *MJHandPai) GetPengPais() []*MJPai {
	if m != nil {
		return m.PengPais
	}
	return nil
}

func (m *MJHandPai) GetGangPais() []*MJPai {
	if m != nil {
		return m.GangPais
	}
	return nil
}

func (m *MJHandPai) GetHuPais() []*MJPai {
	if m != nil {
		return m.HuPais
	}
	return nil
}

func (m *MJHandPai) GetInPai() *MJPai {
	if m != nil {
		return m.InPai
	}
	return nil
}

func (m *MJHandPai) GetQueFlower() int32 {
	if m != nil && m.QueFlower != nil {
		return *m.QueFlower
	}
	return 0
}

func (m *MJHandPai) GetOutPais() []*MJPai {
	if m != nil {
		return m.OutPais
	}
	return nil
}

type HuPaiInfo struct {
	SendUserId       *uint32 `protobuf:"varint,1,opt,name=sendUserId" json:"sendUserId,omitempty"`
	GetUserId        *uint32 `protobuf:"varint,2,opt,name=getUserId" json:"getUserId,omitempty"`
	ByWho            *int32  `protobuf:"varint,3,opt,name=byWho" json:"byWho,omitempty"`
	HuType           *int32  `protobuf:"varint,4,opt,name=huType" json:"huType,omitempty"`
	CardType         *int32  `protobuf:"varint,5,opt,name=cardType" json:"cardType,omitempty"`
	HuDesc           *string `protobuf:"bytes,6,opt,name=huDesc" json:"huDesc,omitempty"`
	Pai              *MJPai  `protobuf:"bytes,7,opt,name=pai" json:"pai,omitempty"`
	Fan              *int32  `protobuf:"varint,8,opt,name=fan" json:"fan,omitempty"`
	Score            *int64  `protobuf:"varint,9,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HuPaiInfo) Reset()                    { *m = HuPaiInfo{} }
func (m *HuPaiInfo) String() string            { return proto.CompactTextString(m) }
func (*HuPaiInfo) ProtoMessage()               {}
func (*HuPaiInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HuPaiInfo) GetSendUserId() uint32 {
	if m != nil && m.SendUserId != nil {
		return *m.SendUserId
	}
	return 0
}

func (m *HuPaiInfo) GetGetUserId() uint32 {
	if m != nil && m.GetUserId != nil {
		return *m.GetUserId
	}
	return 0
}

func (m *HuPaiInfo) GetByWho() int32 {
	if m != nil && m.ByWho != nil {
		return *m.ByWho
	}
	return 0
}

func (m *HuPaiInfo) GetHuType() int32 {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return 0
}

func (m *HuPaiInfo) GetCardType() int32 {
	if m != nil && m.CardType != nil {
		return *m.CardType
	}
	return 0
}

func (m *HuPaiInfo) GetHuDesc() string {
	if m != nil && m.HuDesc != nil {
		return *m.HuDesc
	}
	return ""
}

func (m *HuPaiInfo) GetPai() *MJPai {
	if m != nil {
		return m.Pai
	}
	return nil
}

func (m *HuPaiInfo) GetFan() int32 {
	if m != nil && m.Fan != nil {
		return *m.Fan
	}
	return 0
}

func (m *HuPaiInfo) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type GangPaiInfo struct {
	SendUserId       *uint32 `protobuf:"varint,1,opt,name=sendUserId" json:"sendUserId,omitempty"`
	GetUserId        *uint32 `protobuf:"varint,2,opt,name=getUserId" json:"getUserId,omitempty"`
	ByWho            *int32  `protobuf:"varint,3,opt,name=byWho" json:"byWho,omitempty"`
	GangType         *int32  `protobuf:"varint,4,opt,name=gangType" json:"gangType,omitempty"`
	Pai              *MJPai  `protobuf:"bytes,5,opt,name=pai" json:"pai,omitempty"`
	Transfer         *int32  `protobuf:"varint,6,opt,name=transfer" json:"transfer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GangPaiInfo) Reset()                    { *m = GangPaiInfo{} }
func (m *GangPaiInfo) String() string            { return proto.CompactTextString(m) }
func (*GangPaiInfo) ProtoMessage()               {}
func (*GangPaiInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GangPaiInfo) GetSendUserId() uint32 {
	if m != nil && m.SendUserId != nil {
		return *m.SendUserId
	}
	return 0
}

func (m *GangPaiInfo) GetGetUserId() uint32 {
	if m != nil && m.GetUserId != nil {
		return *m.GetUserId
	}
	return 0
}

func (m *GangPaiInfo) GetByWho() int32 {
	if m != nil && m.ByWho != nil {
		return *m.ByWho
	}
	return 0
}

func (m *GangPaiInfo) GetGangType() int32 {
	if m != nil && m.GangType != nil {
		return *m.GangType
	}
	return 0
}

func (m *GangPaiInfo) GetPai() *MJPai {
	if m != nil {
		return m.Pai
	}
	return nil
}

func (m *GangPaiInfo) GetTransfer() int32 {
	if m != nil && m.Transfer != nil {
		return *m.Transfer
	}
	return 0
}

type GuoHuInfo struct {
	SendUserId       *uint32 `protobuf:"varint,1,opt,name=sendUserId" json:"sendUserId,omitempty"`
	GetUserId        *uint32 `protobuf:"varint,2,opt,name=getUserId" json:"getUserId,omitempty"`
	Pai              *MJPai  `protobuf:"bytes,3,opt,name=pai" json:"pai,omitempty"`
	FanShu           *int32  `protobuf:"varint,4,opt,name=fanShu" json:"fanShu,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GuoHuInfo) Reset()                    { *m = GuoHuInfo{} }
func (m *GuoHuInfo) String() string            { return proto.CompactTextString(m) }
func (*GuoHuInfo) ProtoMessage()               {}
func (*GuoHuInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GuoHuInfo) GetSendUserId() uint32 {
	if m != nil && m.SendUserId != nil {
		return *m.SendUserId
	}
	return 0
}

func (m *GuoHuInfo) GetGetUserId() uint32 {
	if m != nil && m.GetUserId != nil {
		return *m.GetUserId
	}
	return 0
}

func (m *GuoHuInfo) GetPai() *MJPai {
	if m != nil {
		return m.Pai
	}
	return nil
}

func (m *GuoHuInfo) GetFanShu() int32 {
	if m != nil && m.FanShu != nil {
		return *m.FanShu
	}
	return 0
}

// 一个玩家的游戏信息
type PlayerGameData struct {
	HandPai          *MJHandPai     `protobuf:"bytes,1,opt,name=handPai" json:"handPai,omitempty"`
	HuInfo           []*HuPaiInfo   `protobuf:"bytes,2,rep,name=huInfo" json:"huInfo,omitempty"`
	DianHuInfo       []*HuPaiInfo   `protobuf:"bytes,3,rep,name=dianHuInfo" json:"dianHuInfo,omitempty"`
	GangInfo         []*GangPaiInfo `protobuf:"bytes,4,rep,name=gangInfo" json:"gangInfo,omitempty"`
	DianGangInfo     []*GangPaiInfo `protobuf:"bytes,5,rep,name=dianGangInfo" json:"dianGangInfo,omitempty"`
	GangTransfer     []*GangPaiInfo `protobuf:"bytes,6,rep,name=gangTransfer" json:"gangTransfer,omitempty"`
	TotalScore       *int32         `protobuf:"varint,7,opt,name=totalScore" json:"totalScore,omitempty"`
	GuoHuInfo        []*GuoHuInfo   `protobuf:"bytes,8,rep,name=guoHuInfo" json:"guoHuInfo,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayerGameData) Reset()                    { *m = PlayerGameData{} }
func (m *PlayerGameData) String() string            { return proto.CompactTextString(m) }
func (*PlayerGameData) ProtoMessage()               {}
func (*PlayerGameData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerGameData) GetHandPai() *MJHandPai {
	if m != nil {
		return m.HandPai
	}
	return nil
}

func (m *PlayerGameData) GetHuInfo() []*HuPaiInfo {
	if m != nil {
		return m.HuInfo
	}
	return nil
}

func (m *PlayerGameData) GetDianHuInfo() []*HuPaiInfo {
	if m != nil {
		return m.DianHuInfo
	}
	return nil
}

func (m *PlayerGameData) GetGangInfo() []*GangPaiInfo {
	if m != nil {
		return m.GangInfo
	}
	return nil
}

func (m *PlayerGameData) GetDianGangInfo() []*GangPaiInfo {
	if m != nil {
		return m.DianGangInfo
	}
	return nil
}

func (m *PlayerGameData) GetGangTransfer() []*GangPaiInfo {
	if m != nil {
		return m.GangTransfer
	}
	return nil
}

func (m *PlayerGameData) GetTotalScore() int32 {
	if m != nil && m.TotalScore != nil {
		return *m.TotalScore
	}
	return 0
}

func (m *PlayerGameData) GetGuoHuInfo() []*GuoHuInfo {
	if m != nil {
		return m.GuoHuInfo
	}
	return nil
}

// 需要确认的时间
type CheckBean struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	CanPeng          *bool   `protobuf:"varint,2,opt,name=CanPeng" json:"CanPeng,omitempty"`
	CanGang          *bool   `protobuf:"varint,3,opt,name=CanGang" json:"CanGang,omitempty"`
	CanHu            *bool   `protobuf:"varint,4,opt,name=CanHu" json:"CanHu,omitempty"`
	CheckStatus      *int32  `protobuf:"varint,5,opt,name=CheckStatus" json:"CheckStatus,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CheckBean) Reset()                    { *m = CheckBean{} }
func (m *CheckBean) String() string            { return proto.CompactTextString(m) }
func (*CheckBean) ProtoMessage()               {}
func (*CheckBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CheckBean) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CheckBean) GetCanPeng() bool {
	if m != nil && m.CanPeng != nil {
		return *m.CanPeng
	}
	return false
}

func (m *CheckBean) GetCanGang() bool {
	if m != nil && m.CanGang != nil {
		return *m.CanGang
	}
	return false
}

func (m *CheckBean) GetCanHu() bool {
	if m != nil && m.CanHu != nil {
		return *m.CanHu
	}
	return false
}

func (m *CheckBean) GetCheckStatus() int32 {
	if m != nil && m.CheckStatus != nil {
		return *m.CheckStatus
	}
	return 0
}

type CheckCase struct {
	CheckB           []*CheckBean `protobuf:"bytes,1,rep,name=CheckB" json:"CheckB,omitempty"`
	CheckStatus      *int32       `protobuf:"varint,2,opt,name=CheckStatus" json:"CheckStatus,omitempty"`
	CheckMJPai       *MJPai       `protobuf:"bytes,3,opt,name=CheckMJPai" json:"CheckMJPai,omitempty"`
	UserIdOut        *uint32      `protobuf:"varint,4,opt,name=UserIdOut" json:"UserIdOut,omitempty"`
	PreOutGangInfo   *GangPaiInfo `protobuf:"bytes,5,opt,name=PreOutGangInfo" json:"PreOutGangInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CheckCase) Reset()                    { *m = CheckCase{} }
func (m *CheckCase) String() string            { return proto.CompactTextString(m) }
func (*CheckCase) ProtoMessage()               {}
func (*CheckCase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CheckCase) GetCheckB() []*CheckBean {
	if m != nil {
		return m.CheckB
	}
	return nil
}

func (m *CheckCase) GetCheckStatus() int32 {
	if m != nil && m.CheckStatus != nil {
		return *m.CheckStatus
	}
	return 0
}

func (m *CheckCase) GetCheckMJPai() *MJPai {
	if m != nil {
		return m.CheckMJPai
	}
	return nil
}

func (m *CheckCase) GetUserIdOut() uint32 {
	if m != nil && m.UserIdOut != nil {
		return *m.UserIdOut
	}
	return 0
}

func (m *CheckCase) GetPreOutGangInfo() *GangPaiInfo {
	if m != nil {
		return m.PreOutGangInfo
	}
	return nil
}

// 麻将牌的结构
type MjDesk struct {
	DeskId           *int32     `protobuf:"varint,1,opt,name=DeskId" json:"DeskId,omitempty"`
	RoomId           *int32     `protobuf:"varint,2,opt,name=RoomId" json:"RoomId,omitempty"`
	Status           *int32     `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	Users            []*MjUser  `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	Password         *string    `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
	Owner            *uint32    `protobuf:"varint,6,opt,name=Owner" json:"Owner,omitempty"`
	CreateFee        *int64     `protobuf:"varint,7,opt,name=CreateFee" json:"CreateFee,omitempty"`
	MjRoomType       *int32     `protobuf:"varint,8,opt,name=mjRoomType" json:"mjRoomType,omitempty"`
	BoardsCout       *int32     `protobuf:"varint,9,opt,name=boardsCout" json:"boardsCout,omitempty"`
	CapMax           *int64     `protobuf:"varint,10,opt,name=capMax" json:"capMax,omitempty"`
	CardsNum         *int32     `protobuf:"varint,11,opt,name=cardsNum" json:"cardsNum,omitempty"`
	Settlement       *int32     `protobuf:"varint,12,opt,name=settlement" json:"settlement,omitempty"`
	BaseValue        *int64     `protobuf:"varint,13,opt,name=baseValue" json:"baseValue,omitempty"`
	ZiMoRadio        *int32     `protobuf:"varint,14,opt,name=ziMoRadio" json:"ziMoRadio,omitempty"`
	DianGangHuaRadio *int32     `protobuf:"varint,15,opt,name=dianGangHuaRadio" json:"dianGangHuaRadio,omitempty"`
	OthersCheckBox   []int32    `protobuf:"varint,16,rep,name=othersCheckBox" json:"othersCheckBox,omitempty"`
	HuRadio          *int32     `protobuf:"varint,17,opt,name=huRadio" json:"huRadio,omitempty"`
	AllMJPai         []*MJPai   `protobuf:"bytes,18,rep,name=AllMJPai" json:"AllMJPai,omitempty"`
	DeskMJPai        []*MJPai   `protobuf:"bytes,19,rep,name=DeskMJPai" json:"DeskMJPai,omitempty"`
	MJPaiCursor      *int32     `protobuf:"varint,20,opt,name=MJPaiCursor" json:"MJPaiCursor,omitempty"`
	TotalPlayCount   *int32     `protobuf:"varint,21,opt,name=TotalPlayCount" json:"TotalPlayCount,omitempty"`
	CurrPlayCount    *int32     `protobuf:"varint,22,opt,name=CurrPlayCount" json:"CurrPlayCount,omitempty"`
	Banker           *uint32    `protobuf:"varint,23,opt,name=Banker" json:"Banker,omitempty"`
	CheckCase        *CheckCase `protobuf:"bytes,24,opt,name=CheckCase" json:"CheckCase,omitempty"`
	ActiveUser       *uint32    `protobuf:"varint,25,opt,name=ActiveUser" json:"ActiveUser,omitempty"`
	GameNumber       *int32     `protobuf:"varint,26,opt,name=GameNumber" json:"GameNumber,omitempty"`
	ActUser          *uint32    `protobuf:"varint,27,opt,name=ActUser" json:"ActUser,omitempty"`
	ActType          *int32     `protobuf:"varint,28,opt,name=ActType" json:"ActType,omitempty"`
	BeginTime        *string    `protobuf:"bytes,29,opt,name=BeginTime" json:"BeginTime,omitempty"`
	EndTime          *string    `protobuf:"bytes,30,opt,name=EndTime" json:"EndTime,omitempty"`
	NextBanker       *uint32    `protobuf:"varint,31,opt,name=nextBanker" json:"nextBanker,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MjDesk) Reset()                    { *m = MjDesk{} }
func (m *MjDesk) String() string            { return proto.CompactTextString(m) }
func (*MjDesk) ProtoMessage()               {}
func (*MjDesk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MjDesk) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *MjDesk) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MjDesk) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *MjDesk) GetUsers() []*MjUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MjDesk) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *MjDesk) GetOwner() uint32 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *MjDesk) GetCreateFee() int64 {
	if m != nil && m.CreateFee != nil {
		return *m.CreateFee
	}
	return 0
}

func (m *MjDesk) GetMjRoomType() int32 {
	if m != nil && m.MjRoomType != nil {
		return *m.MjRoomType
	}
	return 0
}

func (m *MjDesk) GetBoardsCout() int32 {
	if m != nil && m.BoardsCout != nil {
		return *m.BoardsCout
	}
	return 0
}

func (m *MjDesk) GetCapMax() int64 {
	if m != nil && m.CapMax != nil {
		return *m.CapMax
	}
	return 0
}

func (m *MjDesk) GetCardsNum() int32 {
	if m != nil && m.CardsNum != nil {
		return *m.CardsNum
	}
	return 0
}

func (m *MjDesk) GetSettlement() int32 {
	if m != nil && m.Settlement != nil {
		return *m.Settlement
	}
	return 0
}

func (m *MjDesk) GetBaseValue() int64 {
	if m != nil && m.BaseValue != nil {
		return *m.BaseValue
	}
	return 0
}

func (m *MjDesk) GetZiMoRadio() int32 {
	if m != nil && m.ZiMoRadio != nil {
		return *m.ZiMoRadio
	}
	return 0
}

func (m *MjDesk) GetDianGangHuaRadio() int32 {
	if m != nil && m.DianGangHuaRadio != nil {
		return *m.DianGangHuaRadio
	}
	return 0
}

func (m *MjDesk) GetOthersCheckBox() []int32 {
	if m != nil {
		return m.OthersCheckBox
	}
	return nil
}

func (m *MjDesk) GetHuRadio() int32 {
	if m != nil && m.HuRadio != nil {
		return *m.HuRadio
	}
	return 0
}

func (m *MjDesk) GetAllMJPai() []*MJPai {
	if m != nil {
		return m.AllMJPai
	}
	return nil
}

func (m *MjDesk) GetDeskMJPai() []*MJPai {
	if m != nil {
		return m.DeskMJPai
	}
	return nil
}

func (m *MjDesk) GetMJPaiCursor() int32 {
	if m != nil && m.MJPaiCursor != nil {
		return *m.MJPaiCursor
	}
	return 0
}

func (m *MjDesk) GetTotalPlayCount() int32 {
	if m != nil && m.TotalPlayCount != nil {
		return *m.TotalPlayCount
	}
	return 0
}

func (m *MjDesk) GetCurrPlayCount() int32 {
	if m != nil && m.CurrPlayCount != nil {
		return *m.CurrPlayCount
	}
	return 0
}

func (m *MjDesk) GetBanker() uint32 {
	if m != nil && m.Banker != nil {
		return *m.Banker
	}
	return 0
}

func (m *MjDesk) GetCheckCase() *CheckCase {
	if m != nil {
		return m.CheckCase
	}
	return nil
}

func (m *MjDesk) GetActiveUser() uint32 {
	if m != nil && m.ActiveUser != nil {
		return *m.ActiveUser
	}
	return 0
}

func (m *MjDesk) GetGameNumber() int32 {
	if m != nil && m.GameNumber != nil {
		return *m.GameNumber
	}
	return 0
}

func (m *MjDesk) GetActUser() uint32 {
	if m != nil && m.ActUser != nil {
		return *m.ActUser
	}
	return 0
}

func (m *MjDesk) GetActType() int32 {
	if m != nil && m.ActType != nil {
		return *m.ActType
	}
	return 0
}

func (m *MjDesk) GetBeginTime() string {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return ""
}

func (m *MjDesk) GetEndTime() string {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return ""
}

func (m *MjDesk) GetNextBanker() uint32 {
	if m != nil && m.NextBanker != nil {
		return *m.NextBanker
	}
	return 0
}

type BillBean struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	OutUserId        *uint32 `protobuf:"varint,2,opt,name=OutUserId" json:"OutUserId,omitempty"`
	Type             *int32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Des              *string `protobuf:"bytes,4,opt,name=des" json:"des,omitempty"`
	Amount           *int64  `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
	Pai              *MJPai  `protobuf:"bytes,6,opt,name=pai" json:"pai,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BillBean) Reset()                    { *m = BillBean{} }
func (m *BillBean) String() string            { return proto.CompactTextString(m) }
func (*BillBean) ProtoMessage()               {}
func (*BillBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BillBean) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BillBean) GetOutUserId() uint32 {
	if m != nil && m.OutUserId != nil {
		return *m.OutUserId
	}
	return 0
}

func (m *BillBean) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BillBean) GetDes() string {
	if m != nil && m.Des != nil {
		return *m.Des
	}
	return ""
}

func (m *BillBean) GetAmount() int64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *BillBean) GetPai() *MJPai {
	if m != nil {
		return m.Pai
	}
	return nil
}

type Bill struct {
	WinAmount        *int64      `protobuf:"varint,1,opt,name=WinAmount" json:"WinAmount,omitempty"`
	Bills            []*BillBean `protobuf:"bytes,2,rep,name=bills" json:"bills,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Bill) Reset()                    { *m = Bill{} }
func (m *Bill) String() string            { return proto.CompactTextString(m) }
func (*Bill) ProtoMessage()               {}
func (*Bill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Bill) GetWinAmount() int64 {
	if m != nil && m.WinAmount != nil {
		return *m.WinAmount
	}
	return 0
}

func (m *Bill) GetBills() []*BillBean {
	if m != nil {
		return m.Bills
	}
	return nil
}

type StatiscRound struct {
	Round            *int32  `protobuf:"varint,1,opt,name=Round" json:"Round,omitempty"`
	GameNumber       *int32  `protobuf:"varint,2,opt,name=GameNumber" json:"GameNumber,omitempty"`
	Result           *string `protobuf:"bytes,3,opt,name=Result" json:"Result,omitempty"`
	WinAmount        *int64  `protobuf:"varint,4,opt,name=WinAmount" json:"WinAmount,omitempty"`
	CountHu          *int32  `protobuf:"varint,5,opt,name=CountHu" json:"CountHu,omitempty"`
	CountZiMo        *int32  `protobuf:"varint,6,opt,name=CountZiMo" json:"CountZiMo,omitempty"`
	CountDianPao     *int32  `protobuf:"varint,7,opt,name=CountDianPao" json:"CountDianPao,omitempty"`
	CountAnGang      *int32  `protobuf:"varint,8,opt,name=CountAnGang" json:"CountAnGang,omitempty"`
	CountMingGang    *int32  `protobuf:"varint,9,opt,name=CountMingGang" json:"CountMingGang,omitempty"`
	CountDianGang    *int32  `protobuf:"varint,10,opt,name=CountDianGang" json:"CountDianGang,omitempty"`
	CountChaJiao     *int32  `protobuf:"varint,11,opt,name=CountChaJiao" json:"CountChaJiao,omitempty"`
	CountBaGnag      *int32  `protobuf:"varint,12,opt,name=CountBaGnag" json:"CountBaGnag,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatiscRound) Reset()                    { *m = StatiscRound{} }
func (m *StatiscRound) String() string            { return proto.CompactTextString(m) }
func (*StatiscRound) ProtoMessage()               {}
func (*StatiscRound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StatiscRound) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *StatiscRound) GetGameNumber() int32 {
	if m != nil && m.GameNumber != nil {
		return *m.GameNumber
	}
	return 0
}

func (m *StatiscRound) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

func (m *StatiscRound) GetWinAmount() int64 {
	if m != nil && m.WinAmount != nil {
		return *m.WinAmount
	}
	return 0
}

func (m *StatiscRound) GetCountHu() int32 {
	if m != nil && m.CountHu != nil {
		return *m.CountHu
	}
	return 0
}

func (m *StatiscRound) GetCountZiMo() int32 {
	if m != nil && m.CountZiMo != nil {
		return *m.CountZiMo
	}
	return 0
}

func (m *StatiscRound) GetCountDianPao() int32 {
	if m != nil && m.CountDianPao != nil {
		return *m.CountDianPao
	}
	return 0
}

func (m *StatiscRound) GetCountAnGang() int32 {
	if m != nil && m.CountAnGang != nil {
		return *m.CountAnGang
	}
	return 0
}

func (m *StatiscRound) GetCountMingGang() int32 {
	if m != nil && m.CountMingGang != nil {
		return *m.CountMingGang
	}
	return 0
}

func (m *StatiscRound) GetCountDianGang() int32 {
	if m != nil && m.CountDianGang != nil {
		return *m.CountDianGang
	}
	return 0
}

func (m *StatiscRound) GetCountChaJiao() int32 {
	if m != nil && m.CountChaJiao != nil {
		return *m.CountChaJiao
	}
	return 0
}

func (m *StatiscRound) GetCountBaGnag() int32 {
	if m != nil && m.CountBaGnag != nil {
		return *m.CountBaGnag
	}
	return 0
}

type MjUserStatisc struct {
	WinCoin          *int64          `protobuf:"varint,1,opt,name=WinCoin" json:"WinCoin,omitempty"`
	CountHu          *int32          `protobuf:"varint,2,opt,name=CountHu" json:"CountHu,omitempty"`
	CountZiMo        *int32          `protobuf:"varint,3,opt,name=CountZiMo" json:"CountZiMo,omitempty"`
	CountDianPao     *int32          `protobuf:"varint,4,opt,name=CountDianPao" json:"CountDianPao,omitempty"`
	CountAnGang      *int32          `protobuf:"varint,5,opt,name=CountAnGang" json:"CountAnGang,omitempty"`
	CountMingGang    *int32          `protobuf:"varint,6,opt,name=CountMingGang" json:"CountMingGang,omitempty"`
	CountDianGang    *int32          `protobuf:"varint,7,opt,name=CountDianGang" json:"CountDianGang,omitempty"`
	CountChaJiao     *int32          `protobuf:"varint,8,opt,name=CountChaJiao" json:"CountChaJiao,omitempty"`
	RoundBean        []*StatiscRound `protobuf:"bytes,9,rep,name=roundBean" json:"roundBean,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MjUserStatisc) Reset()                    { *m = MjUserStatisc{} }
func (m *MjUserStatisc) String() string            { return proto.CompactTextString(m) }
func (*MjUserStatisc) ProtoMessage()               {}
func (*MjUserStatisc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MjUserStatisc) GetWinCoin() int64 {
	if m != nil && m.WinCoin != nil {
		return *m.WinCoin
	}
	return 0
}

func (m *MjUserStatisc) GetCountHu() int32 {
	if m != nil && m.CountHu != nil {
		return *m.CountHu
	}
	return 0
}

func (m *MjUserStatisc) GetCountZiMo() int32 {
	if m != nil && m.CountZiMo != nil {
		return *m.CountZiMo
	}
	return 0
}

func (m *MjUserStatisc) GetCountDianPao() int32 {
	if m != nil && m.CountDianPao != nil {
		return *m.CountDianPao
	}
	return 0
}

func (m *MjUserStatisc) GetCountAnGang() int32 {
	if m != nil && m.CountAnGang != nil {
		return *m.CountAnGang
	}
	return 0
}

func (m *MjUserStatisc) GetCountMingGang() int32 {
	if m != nil && m.CountMingGang != nil {
		return *m.CountMingGang
	}
	return 0
}

func (m *MjUserStatisc) GetCountDianGang() int32 {
	if m != nil && m.CountDianGang != nil {
		return *m.CountDianGang
	}
	return 0
}

func (m *MjUserStatisc) GetCountChaJiao() int32 {
	if m != nil && m.CountChaJiao != nil {
		return *m.CountChaJiao
	}
	return 0
}

func (m *MjUserStatisc) GetRoundBean() []*StatiscRound {
	if m != nil {
		return m.RoundBean
	}
	return nil
}

type MjUser struct {
	UserId           *uint32         `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	Coin             *int64          `protobuf:"varint,2,opt,name=Coin" json:"Coin,omitempty"`
	GameData         *PlayerGameData `protobuf:"bytes,3,opt,name=GameData" json:"GameData,omitempty"`
	Status           *int32          `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	IsBreak          *bool           `protobuf:"varint,5,opt,name=IsBreak" json:"IsBreak,omitempty"`
	IsLeave          *bool           `protobuf:"varint,6,opt,name=IsLeave" json:"IsLeave,omitempty"`
	DeskId           *int32          `protobuf:"varint,7,opt,name=DeskId" json:"DeskId,omitempty"`
	RoomId           *int32          `protobuf:"varint,8,opt,name=RoomId" json:"RoomId,omitempty"`
	DingQue          *bool           `protobuf:"varint,9,opt,name=DingQue" json:"DingQue,omitempty"`
	Exchanged        *bool           `protobuf:"varint,10,opt,name=Exchanged" json:"Exchanged,omitempty"`
	Ready            *bool           `protobuf:"varint,11,opt,name=Ready" json:"Ready,omitempty"`
	IsBanker         *bool           `protobuf:"varint,12,opt,name=IsBanker" json:"IsBanker,omitempty"`
	PreMoGangInfo    *GangPaiInfo    `protobuf:"bytes,13,opt,name=PreMoGangInfo" json:"PreMoGangInfo,omitempty"`
	Bill             *Bill           `protobuf:"bytes,14,opt,name=bill" json:"bill,omitempty"`
	Statisc          *MjUserStatisc  `protobuf:"bytes,15,opt,name=statisc" json:"statisc,omitempty"`
	WaitTime         *int64          `protobuf:"varint,16,opt,name=WaitTime" json:"WaitTime,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MjUser) Reset()                    { *m = MjUser{} }
func (m *MjUser) String() string            { return proto.CompactTextString(m) }
func (*MjUser) ProtoMessage()               {}
func (*MjUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MjUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MjUser) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *MjUser) GetGameData() *PlayerGameData {
	if m != nil {
		return m.GameData
	}
	return nil
}

func (m *MjUser) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *MjUser) GetIsBreak() bool {
	if m != nil && m.IsBreak != nil {
		return *m.IsBreak
	}
	return false
}

func (m *MjUser) GetIsLeave() bool {
	if m != nil && m.IsLeave != nil {
		return *m.IsLeave
	}
	return false
}

func (m *MjUser) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *MjUser) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MjUser) GetDingQue() bool {
	if m != nil && m.DingQue != nil {
		return *m.DingQue
	}
	return false
}

func (m *MjUser) GetExchanged() bool {
	if m != nil && m.Exchanged != nil {
		return *m.Exchanged
	}
	return false
}

func (m *MjUser) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *MjUser) GetIsBanker() bool {
	if m != nil && m.IsBanker != nil {
		return *m.IsBanker
	}
	return false
}

func (m *MjUser) GetPreMoGangInfo() *GangPaiInfo {
	if m != nil {
		return m.PreMoGangInfo
	}
	return nil
}

func (m *MjUser) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

func (m *MjUser) GetStatisc() *MjUserStatisc {
	if m != nil {
		return m.Statisc
	}
	return nil
}

func (m *MjUser) GetWaitTime() int64 {
	if m != nil && m.WaitTime != nil {
		return *m.WaitTime
	}
	return 0
}

// 用户的session
type MjSession struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	RoomId           *int32  `protobuf:"varint,2,opt,name=RoomId" json:"RoomId,omitempty"`
	DeskId           *int32  `protobuf:"varint,3,opt,name=DeskId" json:"DeskId,omitempty"`
	GameStatus       *int32  `protobuf:"varint,4,opt,name=GameStatus" json:"GameStatus,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MjSession) Reset()                    { *m = MjSession{} }
func (m *MjSession) String() string            { return proto.CompactTextString(m) }
func (*MjSession) ProtoMessage()               {}
func (*MjSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MjSession) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MjSession) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MjSession) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *MjSession) GetGameStatus() int32 {
	if m != nil && m.GameStatus != nil {
		return *m.GameStatus
	}
	return 0
}

// 一个麻将room
type MjRoom struct {
	RoomId           *int32    `protobuf:"varint,1,opt,name=RoomId" json:"RoomId,omitempty"`
	RoomType         *int32    `protobuf:"varint,2,opt,name=RoomType" json:"RoomType,omitempty"`
	ReadyTime        *int64    `protobuf:"varint,3,opt,name=ReadyTime" json:"ReadyTime,omitempty"`
	BeginTime        *int64    `protobuf:"varint,4,opt,name=BeginTime" json:"BeginTime,omitempty"`
	EndTIme          *int64    `protobuf:"varint,5,opt,name=EndTIme" json:"EndTIme,omitempty"`
	Desks            []*MjDesk `protobuf:"bytes,6,rep,name=Desks" json:"Desks,omitempty"`
	PaiIndexNow      *int32    `protobuf:"varint,7,opt,name=PaiIndexNow" json:"PaiIndexNow,omitempty"`
	MjPais           []*MJPai  `protobuf:"bytes,8,rep,name=MjPais" json:"MjPais,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MjRoom) Reset()                    { *m = MjRoom{} }
func (m *MjRoom) String() string            { return proto.CompactTextString(m) }
func (*MjRoom) ProtoMessage()               {}
func (*MjRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MjRoom) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MjRoom) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *MjRoom) GetReadyTime() int64 {
	if m != nil && m.ReadyTime != nil {
		return *m.ReadyTime
	}
	return 0
}

func (m *MjRoom) GetBeginTime() int64 {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return 0
}

func (m *MjRoom) GetEndTIme() int64 {
	if m != nil && m.EndTIme != nil {
		return *m.EndTIme
	}
	return 0
}

func (m *MjRoom) GetDesks() []*MjDesk {
	if m != nil {
		return m.Desks
	}
	return nil
}

func (m *MjRoom) GetPaiIndexNow() int32 {
	if m != nil && m.PaiIndexNow != nil {
		return *m.PaiIndexNow
	}
	return 0
}

func (m *MjRoom) GetMjPais() []*MJPai {
	if m != nil {
		return m.MjPais
	}
	return nil
}

//
type RunningDeskKeys struct {
	Keys             []int32 `protobuf:"varint,1,rep,name=keys" json:"keys,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RunningDeskKeys) Reset()                    { *m = RunningDeskKeys{} }
func (m *RunningDeskKeys) String() string            { return proto.CompactTextString(m) }
func (*RunningDeskKeys) ProtoMessage()               {}
func (*RunningDeskKeys) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RunningDeskKeys) GetKeys() []int32 {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*MJPai)(nil), "majiang.MJPai")
	proto.RegisterType((*MJHandPai)(nil), "majiang.MJHandPai")
	proto.RegisterType((*HuPaiInfo)(nil), "majiang.HuPaiInfo")
	proto.RegisterType((*GangPaiInfo)(nil), "majiang.GangPaiInfo")
	proto.RegisterType((*GuoHuInfo)(nil), "majiang.GuoHuInfo")
	proto.RegisterType((*PlayerGameData)(nil), "majiang.PlayerGameData")
	proto.RegisterType((*CheckBean)(nil), "majiang.CheckBean")
	proto.RegisterType((*CheckCase)(nil), "majiang.CheckCase")
	proto.RegisterType((*MjDesk)(nil), "majiang.MjDesk")
	proto.RegisterType((*BillBean)(nil), "majiang.BillBean")
	proto.RegisterType((*Bill)(nil), "majiang.Bill")
	proto.RegisterType((*StatiscRound)(nil), "majiang.StatiscRound")
	proto.RegisterType((*MjUserStatisc)(nil), "majiang.MjUserStatisc")
	proto.RegisterType((*MjUser)(nil), "majiang.MjUser")
	proto.RegisterType((*MjSession)(nil), "majiang.MjSession")
	proto.RegisterType((*MjRoom)(nil), "majiang.MjRoom")
	proto.RegisterType((*RunningDeskKeys)(nil), "majiang.RunningDeskKeys")
}

var fileDescriptor0 = []byte{
	// 1380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x57, 0xc9, 0x72, 0xdb, 0x46,
	0x13, 0x2e, 0x2e, 0x20, 0x81, 0x21, 0x29, 0xc9, 0xb0, 0x6c, 0xe3, 0xff, 0x6d, 0xcb, 0x0e, 0x52,
	0x4e, 0x9c, 0xa5, 0x74, 0xd0, 0x35, 0x27, 0x91, 0xb2, 0xb5, 0x24, 0xb4, 0x14, 0x4a, 0x89, 0xaa,
	0x72, 0x71, 0x8d, 0x88, 0x11, 0x09, 0x8a, 0x9c, 0x51, 0xb0, 0x68, 0xc9, 0x39, 0xaf, 0x90, 0x87,
	0x48, 0x55, 0xce, 0x39, 0xe5, 0x55, 0x52, 0x95, 0x17, 0xc8, 0x1b, 0xe4, 0x90, 0xee, 0x9e, 0x01,
	0x01, 0x52, 0x50, 0xaa, 0x52, 0x39, 0x89, 0xe8, 0xe9, 0xe9, 0xe5, 0xeb, 0xee, 0xaf, 0x47, 0x6c,
	0x7d, 0xc6, 0xc7, 0x13, 0x25, 0x47, 0xef, 0x63, 0x11, 0x5d, 0x89, 0x68, 0xf3, 0x32, 0x52, 0x89,
	0x72, 0x9b, 0x33, 0x3e, 0x09, 0xb9, 0x1c, 0xf9, 0x5d, 0x66, 0xf5, 0x0f, 0x8e, 0x78, 0xe8, 0x76,
	0x98, 0x15, 0xca, 0x40, 0xdc, 0x78, 0x95, 0x97, 0x95, 0xd7, 0x96, 0xbb, 0xc2, 0x1a, 0xe7, 0x53,
	0x75, 0x2d, 0x22, 0xaf, 0x4a, 0xdf, 0x70, 0x7c, 0xc5, 0xa7, 0xa9, 0xf0, 0x6a, 0xf4, 0xd9, 0x62,
	0xb5, 0x40, 0xc4, 0x5e, 0x1d, 0x3e, 0x1c, 0xff, 0x8f, 0x0a, 0x73, 0xfa, 0x07, 0x7b, 0x5c, 0x06,
	0x68, 0xe8, 0x19, 0xab, 0xc3, 0x9f, 0x18, 0xec, 0xd4, 0x5e, 0xb7, 0xb6, 0x56, 0x36, 0x8d, 0xa7,
	0x4d, 0xed, 0xe6, 0x25, 0xb3, 0x8f, 0x84, 0x1c, 0x91, 0x46, 0xf5, 0x3e, 0x8d, 0x5d, 0x6e, 0x34,
	0x6a, 0xa5, 0x1a, 0x1b, 0xac, 0xb1, 0x97, 0xd2, 0x79, 0xbd, 0xf4, 0xfc, 0x39, 0xa6, 0x02, 0x3f,
	0x3c, 0x0b, 0xc2, 0xbb, 0x7b, 0xfc, 0x80, 0x39, 0xdf, 0xa7, 0xe2, 0xad, 0xce, 0xae, 0x41, 0xe9,
	0xbc, 0x60, 0xcd, 0xc3, 0x34, 0x21, 0x93, 0xcd, 0x32, 0x93, 0xfe, 0x2f, 0x90, 0x22, 0xf9, 0xdc,
	0x97, 0xe7, 0xca, 0x75, 0x19, 0x8b, 0x85, 0x0c, 0xbe, 0x01, 0x48, 0xf7, 0x03, 0x02, 0xac, 0x83,
	0x56, 0x47, 0x22, 0x31, 0xa2, 0x2a, 0x89, 0x00, 0xb3, 0xb3, 0xdb, 0xd3, 0xb1, 0x32, 0x98, 0x01,
	0xa4, 0xe3, 0xf4, 0xe4, 0xf6, 0x52, 0x10, 0x6c, 0x96, 0xbb, 0xc6, 0xec, 0x21, 0x8f, 0x02, 0x92,
	0x58, 0xb9, 0xc6, 0x8e, 0x88, 0x87, 0x14, 0x96, 0xe3, 0x3e, 0x65, 0xb5, 0x4b, 0x48, 0xa3, 0x59,
	0x9a, 0x06, 0x94, 0xe0, 0x9c, 0x4b, 0xcf, 0xce, 0xca, 0x13, 0x0f, 0x55, 0x24, 0x3c, 0x07, 0x3e,
	0x6b, 0xfe, 0x8f, 0x15, 0xd6, 0x32, 0x20, 0xfe, 0x87, 0x80, 0x21, 0xc0, 0x11, 0x18, 0x29, 0x84,
	0x6c, 0x02, 0x2a, 0xc7, 0x15, 0xd4, 0x93, 0x88, 0xcb, 0xf8, 0x3c, 0x83, 0xd5, 0x7f, 0xcf, 0x9c,
	0xdd, 0x54, 0xed, 0xa5, 0xff, 0x26, 0x06, 0xe3, 0xa2, 0x56, 0xea, 0x02, 0xbb, 0x92, 0xcb, 0xe3,
	0x71, 0xaa, 0xe3, 0xf1, 0x7f, 0xab, 0xb2, 0x95, 0xa3, 0x29, 0xbf, 0x15, 0xd1, 0x2e, 0x9f, 0x89,
	0x1d, 0x9e, 0x70, 0xf7, 0x43, 0xd6, 0x1c, 0xeb, 0x4e, 0x24, 0x1f, 0xad, 0x2d, 0xb7, 0x60, 0x23,
	0xeb, 0x51, 0x1f, 0x81, 0xc6, 0xa8, 0x4c, 0x0f, 0xe6, 0x3a, 0x79, 0x91, 0x3f, 0x62, 0x2c, 0x00,
	0x91, 0x8e, 0xde, 0x74, 0x62, 0xb9, 0x1e, 0xa1, 0x44, 0x5a, 0xba, 0x1f, 0xd7, 0xe7, 0x5a, 0xc5,
	0x1a, 0x7c, 0xca, 0xda, 0x68, 0x6f, 0x37, 0xd3, 0xb5, 0xfe, 0x59, 0x97, 0x90, 0xcf, 0xe1, 0xbc,
	0x5f, 0x17, 0x70, 0x4d, 0x54, 0xc2, 0xa7, 0xc7, 0x54, 0xff, 0x26, 0xd5, 0xe9, 0x15, 0xe0, 0x9a,
	0x01, 0x0f, 0x1d, 0xb2, 0x18, 0xfa, 0xbc, 0x24, 0x3e, 0x67, 0x4e, 0x6f, 0x2c, 0x86, 0x17, 0x5d,
	0xc1, 0x25, 0x62, 0x9b, 0x16, 0x6b, 0xb3, 0xca, 0x9a, 0x3d, 0x2e, 0x71, 0x58, 0xa9, 0x32, 0xb6,
	0x11, 0xa0, 0x6b, 0xaa, 0x8e, 0x8d, 0xed, 0xd2, 0x43, 0x80, 0xa8, 0x18, 0xb6, 0xfb, 0x90, 0xb5,
	0xc8, 0xda, 0x71, 0xc2, 0x93, 0x34, 0xd6, 0x2d, 0xed, 0xff, 0x5c, 0x31, 0x3e, 0x7a, 0x3c, 0x16,
	0x88, 0xbb, 0x76, 0x68, 0xd8, 0x21, 0x0f, 0x2a, 0x8f, 0x63, 0xc9, 0x8c, 0xa6, 0x1f, 0x9f, 0x31,
	0x12, 0x52, 0x1b, 0xdc, 0xd3, 0x1c, 0xd0, 0x4c, 0xba, 0x93, 0x60, 0x94, 0x29, 0xa4, 0x8e, 0xfb,
	0x39, 0xb4, 0x47, 0x24, 0xe0, 0xbb, 0x80, 0x7a, 0xe5, 0x3e, 0x24, 0xfd, 0x9f, 0x2c, 0xd6, 0xe8,
	0x4f, 0x60, 0xfe, 0x2e, 0x10, 0x0c, 0xfc, 0x6b, 0xc0, 0xa0, 0xc9, 0x1c, 0x28, 0x35, 0x33, 0x5d,
	0x4a, 0xdf, 0x26, 0x3e, 0x3d, 0x2a, 0x1b, 0xcc, 0x42, 0xf0, 0x32, 0x46, 0x5a, 0xcd, 0x43, 0x9b,
	0x60, 0x4c, 0x38, 0x1b, 0x47, 0x3c, 0x8e, 0xaf, 0x55, 0x14, 0x50, 0x08, 0x0e, 0x82, 0x77, 0x78,
	0x2d, 0xcd, 0xa8, 0xd0, 0x24, 0xf4, 0x22, 0xc1, 0x13, 0xf1, 0x56, 0xe8, 0x22, 0xd6, 0xb0, 0xb0,
	0xb3, 0x09, 0x7a, 0xa5, 0x01, 0xd4, 0x73, 0x0e, 0xb2, 0x33, 0x05, 0xa4, 0x11, 0xf7, 0x14, 0x24,
	0xe9, 0x64, 0xb1, 0x0c, 0xf9, 0x65, 0x9f, 0xdf, 0x78, 0x8c, 0xee, 0x19, 0x5e, 0x89, 0xdf, 0xa5,
	0x33, 0xaf, 0x95, 0xdd, 0x8a, 0x45, 0x92, 0x4c, 0xc5, 0x4c, 0xc8, 0xc4, 0x6b, 0x93, 0x0c, 0x1c,
	0x9e, 0x41, 0x49, 0xbe, 0x25, 0x52, 0xef, 0xd0, 0x45, 0x10, 0xfd, 0x10, 0xf6, 0xd5, 0x80, 0x07,
	0xa1, 0xf2, 0x56, 0x48, 0xcb, 0x63, 0x6b, 0x59, 0xd3, 0xee, 0xa5, 0x5c, 0x9f, 0xac, 0xd2, 0xc9,
	0x63, 0xb6, 0xa2, 0x92, 0x31, 0xa4, 0xac, 0x2b, 0xa7, 0x6e, 0xbc, 0x35, 0x48, 0xdd, 0xc2, 0x2e,
	0x19, 0xa7, 0x5a, 0xf1, 0x01, 0x29, 0x02, 0x9f, 0x6f, 0x4f, 0xa7, 0xba, 0x70, 0x6e, 0x29, 0x5f,
	0x7f, 0xc0, 0x1c, 0x04, 0x5b, 0xab, 0x3c, 0x2c, 0x55, 0x81, 0xa6, 0xa0, 0x1f, 0xbd, 0x34, 0x8a,
	0x55, 0xe4, 0xad, 0x67, 0x21, 0x9c, 0x60, 0xe7, 0x23, 0x03, 0x00, 0x1e, 0x90, 0xda, 0x23, 0x92,
	0x3f, 0x62, 0x1d, 0xd0, 0x8b, 0x72, 0xf1, 0xe3, 0x0c, 0xa7, 0x2e, 0x97, 0x17, 0x00, 0xf9, 0x13,
	0x82, 0xfc, 0x55, 0xa1, 0x33, 0x3d, 0x6f, 0x89, 0x2b, 0xf2, 0x9e, 0x05, 0xf0, 0xb6, 0x87, 0x49,
	0x78, 0x25, 0xb0, 0x90, 0xde, 0xff, 0xe8, 0x2a, 0xc8, 0x90, 0x70, 0x00, 0xe1, 0x33, 0x90, 0xfd,
	0x9f, 0xcc, 0x43, 0xe2, 0xa0, 0x47, 0x4a, 0x4f, 0xb3, 0x01, 0x02, 0x01, 0x15, 0xef, 0x59, 0x06,
	0x79, 0x57, 0x8c, 0x42, 0x79, 0x12, 0xce, 0x84, 0xf7, 0x9c, 0xba, 0x00, 0x74, 0xde, 0xc8, 0x80,
	0x04, 0x1b, 0x24, 0x00, 0xcb, 0x52, 0xdc, 0x24, 0x26, 0xd0, 0x17, 0x68, 0xc8, 0x4f, 0x99, 0xdd,
	0x0d, 0xa7, 0xd3, 0x6c, 0x4a, 0x97, 0x19, 0x14, 0xda, 0x7b, 0x81, 0x41, 0xdb, 0xac, 0x9e, 0xa0,
	0xd3, 0xbb, 0x9b, 0x1a, 0x6f, 0xf3, 0x19, 0x41, 0x62, 0x51, 0xc5, 0x0d, 0xd9, 0x36, 0xca, 0xe6,
	0xc9, 0xff, 0x82, 0xd5, 0xd1, 0x2d, 0xba, 0x38, 0x0d, 0xe5, 0xb6, 0xbe, 0x57, 0xa1, 0x7b, 0x2f,
	0x61, 0x51, 0xc0, 0x51, 0xb6, 0xc2, 0x1f, 0xcc, 0x6f, 0x66, 0x71, 0xfa, 0x7f, 0x55, 0x58, 0x1b,
	0x27, 0x24, 0x8c, 0x87, 0x03, 0xb8, 0x18, 0x60, 0xbf, 0xd3, 0x0f, 0x33, 0x50, 0x8b, 0x08, 0xce,
	0x87, 0x6a, 0x20, 0xe2, 0x74, 0x9a, 0x50, 0xe8, 0xce, 0xa2, 0xe3, 0x3a, 0x39, 0x46, 0x0e, 0xc2,
	0x4f, 0x20, 0x1d, 0x2b, 0xc3, 0x94, 0x04, 0xdf, 0x41, 0xe3, 0x9a, 0x65, 0xbe, 0xce, 0xda, 0x24,
	0xda, 0x81, 0x88, 0x8e, 0xb8, 0x32, 0x94, 0x88, 0xb4, 0x82, 0xd2, 0x6d, 0xcd, 0x60, 0xf6, 0xbc,
	0x53, 0x50, 0xd8, 0x0f, 0xe5, 0x88, 0xc4, 0xce, 0x82, 0x78, 0xc7, 0xb4, 0x3e, 0x0d, 0x56, 0x6e,
	0xb8, 0x37, 0xe6, 0x07, 0x21, 0x18, 0x6e, 0x2d, 0x18, 0xee, 0xf2, 0x5d, 0xc9, 0x47, 0x7a, 0xba,
	0xfc, 0xdf, 0x2b, 0xac, 0xa3, 0x47, 0xdf, 0x80, 0x80, 0x91, 0x43, 0x32, 0x3d, 0x15, 0x4a, 0x83,
	0x61, 0x21, 0x95, 0xea, 0xdd, 0x54, 0x6a, 0xa5, 0xa9, 0xd4, 0xcb, 0x52, 0xb1, 0xca, 0x53, 0x69,
	0x94, 0xa7, 0xd2, 0x2c, 0x4d, 0x45, 0xc3, 0xf1, 0x9a, 0x39, 0x11, 0xd6, 0x08, 0x2b, 0x08, 0x50,
	0x60, 0x69, 0x1f, 0xcd, 0x4b, 0x5b, 0xac, 0xa6, 0xff, 0x67, 0x15, 0xa9, 0x92, 0xa8, 0x6d, 0xb9,
	0x23, 0xa1, 0xfd, 0x28, 0xcb, 0x2a, 0x65, 0xf9, 0x09, 0xbe, 0xe6, 0xf4, 0x6a, 0x36, 0xb4, 0xfd,
	0x64, 0x6e, 0x71, 0x69, 0x73, 0xe7, 0x9c, 0x5a, 0xcf, 0x06, 0x6a, 0x3f, 0xee, 0x02, 0x29, 0x5e,
	0x50, 0x8a, 0xb6, 0x16, 0x7c, 0x25, 0xf8, 0x95, 0xa0, 0xe4, 0xec, 0x02, 0x4b, 0x37, 0x97, 0x58,
	0xda, 0xce, 0x2c, 0xec, 0x00, 0x1c, 0x5f, 0xa7, 0xfa, 0x5d, 0x64, 0x23, 0xc4, 0x6f, 0x6e, 0x86,
	0xf0, 0x3e, 0x18, 0x89, 0x80, 0x8a, 0x4a, 0x4b, 0x6c, 0x20, 0x78, 0x70, 0x4b, 0xd5, 0xb4, 0x91,
	0x3c, 0xc1, 0xa9, 0x9e, 0xbe, 0x36, 0x49, 0x3e, 0x63, 0x1d, 0xd8, 0x21, 0x7d, 0x35, 0x5f, 0x21,
	0x9d, 0xfb, 0x57, 0x08, 0x0c, 0x54, 0x1d, 0x07, 0x83, 0xd8, 0xb3, 0xb5, 0xd5, 0x59, 0x98, 0x0b,
	0xf7, 0x63, 0xd6, 0x8c, 0x35, 0x88, 0xc4, 0xa1, 0xad, 0xad, 0xc7, 0x4b, 0x6b, 0x22, 0xeb, 0x15,
	0x08, 0xe2, 0x94, 0x87, 0x09, 0xd1, 0xc2, 0x1a, 0x3d, 0xe8, 0x0e, 0xe1, 0x85, 0x3d, 0x39, 0x16,
	0x71, 0x1c, 0xaa, 0xbb, 0x1c, 0x50, 0xb2, 0x9c, 0x0c, 0x2c, 0xb5, 0xe2, 0xac, 0x15, 0xc1, 0xf5,
	0x7f, 0xad, 0x60, 0x01, 0xf1, 0x5a, 0xe1, 0x7a, 0x25, 0x7b, 0xf6, 0xcd, 0xb7, 0xce, 0xbc, 0x33,
	0x09, 0x23, 0x0a, 0xa8, 0x96, 0xed, 0x8a, 0x9c, 0xcb, 0xe6, 0xb3, 0x89, 0x5c, 0xb6, 0x3f, 0x13,
	0x86, 0x5d, 0x60, 0x29, 0x62, 0x1c, 0xb1, 0x79, 0xbe, 0x14, 0x97, 0x22, 0x2d, 0x59, 0xe8, 0x63,
	0xc2, 0x0d, 0xfe, 0xeb, 0x78, 0xa7, 0xae, 0x4d, 0x0d, 0x37, 0x30, 0x2e, 0x7a, 0x89, 0xdb, 0xa5,
	0x2f, 0xf1, 0x17, 0x6c, 0x75, 0x90, 0x4a, 0x09, 0x65, 0x45, 0x1b, 0x5f, 0x8a, 0xdb, 0x18, 0x3b,
	0xee, 0x02, 0xfe, 0xd2, 0x9b, 0xc2, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x01, 0xbd, 0x74, 0x4e,
	0xf1, 0x0c, 0x00, 0x00,
}
