// Code generated by protoc-gen-go.
// source: ogth.proto
// DO NOT EDIT!

package bbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 注册
// THRANID_SVR_REG = 0x00001003;//注册消息
type REQThranReg struct {
	UserName         *string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Pwd              *string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
	VerifyId         *int32  `protobuf:"varint,3,opt,name=VerifyId" json:"VerifyId,omitempty"`
	VerifyStr        *string `protobuf:"bytes,4,opt,name=VerifyStr" json:"VerifyStr,omitempty"`
	SecureID         *string `protobuf:"bytes,5,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,6,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,7,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,8,opt,name=GameId" json:"GameId,omitempty"`
	Token            *string `protobuf:"bytes,9,opt,name=token" json:"token,omitempty"`
	UserNameApl      []byte  `protobuf:"bytes,10,opt,name=UserNameApl" json:"UserNameApl,omitempty"`
	RoomAdapte       *int32  `protobuf:"varint,11,opt,name=RoomAdapte,def=0" json:"RoomAdapte,omitempty"`
	Sex              *int32  `protobuf:"varint,12,opt,name=Sex,def=0" json:"Sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranReg) Reset()                    { *m = REQThranReg{} }
func (m *REQThranReg) String() string            { return proto.CompactTextString(m) }
func (*REQThranReg) ProtoMessage()               {}
func (*REQThranReg) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

const Default_REQThranReg_RoomAdapte int32 = 0
const Default_REQThranReg_Sex int32 = 0

func (m *REQThranReg) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *REQThranReg) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *REQThranReg) GetVerifyId() int32 {
	if m != nil && m.VerifyId != nil {
		return *m.VerifyId
	}
	return 0
}

func (m *REQThranReg) GetVerifyStr() string {
	if m != nil && m.VerifyStr != nil {
		return *m.VerifyStr
	}
	return ""
}

func (m *REQThranReg) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQThranReg) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQThranReg) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQThranReg) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQThranReg) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *REQThranReg) GetUserNameApl() []byte {
	if m != nil {
		return m.UserNameApl
	}
	return nil
}

func (m *REQThranReg) GetRoomAdapte() int32 {
	if m != nil && m.RoomAdapte != nil {
		return *m.RoomAdapte
	}
	return Default_REQThranReg_RoomAdapte
}

func (m *REQThranReg) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return Default_REQThranReg_Sex
}

type ACKThranReg struct {
	AckResult        *int32        `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	ErrorStr         *string       `protobuf:"bytes,2,opt,name=ErrorStr" json:"ErrorStr,omitempty"`
	Cert             []byte        `protobuf:"bytes,3,opt,name=cert" json:"cert,omitempty"`
	RoleName         *string       `protobuf:"bytes,4,opt,name=RoleName" json:"RoleName,omitempty"`
	RoomList         []*OGRoomInfo `protobuf:"bytes,5,rep,name=RoomList" json:"RoomList,omitempty"`
	LoginId          *int32        `protobuf:"varint,6,opt,name=LoginId" json:"LoginId,omitempty"`
	MatchRoomList    []*OGRoomInfo `protobuf:"bytes,7,rep,name=MatchRoomList" json:"MatchRoomList,omitempty"`
	CertNoRole       []byte        `protobuf:"bytes,8,opt,name=CertNoRole" json:"CertNoRole,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ACKThranReg) Reset()                    { *m = ACKThranReg{} }
func (m *ACKThranReg) String() string            { return proto.CompactTextString(m) }
func (*ACKThranReg) ProtoMessage()               {}
func (*ACKThranReg) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *ACKThranReg) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKThranReg) GetErrorStr() string {
	if m != nil && m.ErrorStr != nil {
		return *m.ErrorStr
	}
	return ""
}

func (m *ACKThranReg) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ACKThranReg) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *ACKThranReg) GetRoomList() []*OGRoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *ACKThranReg) GetLoginId() int32 {
	if m != nil && m.LoginId != nil {
		return *m.LoginId
	}
	return 0
}

func (m *ACKThranReg) GetMatchRoomList() []*OGRoomInfo {
	if m != nil {
		return m.MatchRoomList
	}
	return nil
}

func (m *ACKThranReg) GetCertNoRole() []byte {
	if m != nil {
		return m.CertNoRole
	}
	return nil
}

// 登录THRAN服务器
// THRANID_SVR_LOGINCONN = 0x00001001;//登录消息
type REQThranConn struct {
	UserName         *string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
	Pwd              *string `protobuf:"bytes,3,opt,name=Pwd" json:"Pwd,omitempty"`
	Sex              *int32  `protobuf:"varint,4,opt,name=Sex" json:"Sex,omitempty"`
	SecureID         *string `protobuf:"bytes,5,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,6,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,7,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,8,opt,name=GameId" json:"GameId,omitempty"`
	Token            *string `protobuf:"bytes,9,opt,name=token" json:"token,omitempty"`
	UserNameApl      []byte  `protobuf:"bytes,10,opt,name=UserNameApl" json:"UserNameApl,omitempty"`
	VerifyId         *int32  `protobuf:"varint,11,opt,name=VerifyId" json:"VerifyId,omitempty"`
	Ticket           *string `protobuf:"bytes,12,opt,name=Ticket" json:"Ticket,omitempty"`
	RoomAdapte       *int32  `protobuf:"varint,13,opt,name=RoomAdapte,def=0" json:"RoomAdapte,omitempty"`
	LoginType        *int32  `protobuf:"varint,14,opt,name=LoginType,def=0" json:"LoginType,omitempty"`
	GroupID          *int32  `protobuf:"varint,15,opt,name=GroupID" json:"GroupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranConn) Reset()                    { *m = REQThranConn{} }
func (m *REQThranConn) String() string            { return proto.CompactTextString(m) }
func (*REQThranConn) ProtoMessage()               {}
func (*REQThranConn) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

const Default_REQThranConn_RoomAdapte int32 = 0
const Default_REQThranConn_LoginType int32 = 0

func (m *REQThranConn) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *REQThranConn) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *REQThranConn) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *REQThranConn) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *REQThranConn) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQThranConn) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQThranConn) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQThranConn) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQThranConn) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *REQThranConn) GetUserNameApl() []byte {
	if m != nil {
		return m.UserNameApl
	}
	return nil
}

func (m *REQThranConn) GetVerifyId() int32 {
	if m != nil && m.VerifyId != nil {
		return *m.VerifyId
	}
	return 0
}

func (m *REQThranConn) GetTicket() string {
	if m != nil && m.Ticket != nil {
		return *m.Ticket
	}
	return ""
}

func (m *REQThranConn) GetRoomAdapte() int32 {
	if m != nil && m.RoomAdapte != nil {
		return *m.RoomAdapte
	}
	return Default_REQThranConn_RoomAdapte
}

func (m *REQThranConn) GetLoginType() int32 {
	if m != nil && m.LoginType != nil {
		return *m.LoginType
	}
	return Default_REQThranConn_LoginType
}

func (m *REQThranConn) GetGroupID() int32 {
	if m != nil && m.GroupID != nil {
		return *m.GroupID
	}
	return 0
}

type ACKThranConn struct {
	AckResult        *int32           `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	Cert             []byte           `protobuf:"bytes,2,opt,name=cert" json:"cert,omitempty"`
	UserName         *string          `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	RoleName         *string          `protobuf:"bytes,4,opt,name=RoleName" json:"RoleName,omitempty"`
	PassWord         *string          `protobuf:"bytes,5,opt,name=PassWord" json:"PassWord,omitempty"`
	YuanBaoCnt       *int32           `protobuf:"varint,6,opt,name=YuanBaoCnt" json:"YuanBaoCnt,omitempty"`
	CoinCnt          *int64           `protobuf:"varint,7,opt,name=CoinCnt" json:"CoinCnt,omitempty"`
	RoomList         []*OGRoomInfo    `protobuf:"bytes,8,rep,name=RoomList" json:"RoomList,omitempty"`
	LoginId          *int32           `protobuf:"varint,9,opt,name=LoginId" json:"LoginId,omitempty"`
	MatchRoomList    []*OGRoomInfo    `protobuf:"bytes,10,rep,name=MatchRoomList" json:"MatchRoomList,omitempty"`
	CertNoRole       []byte           `protobuf:"bytes,11,opt,name=CertNoRole" json:"CertNoRole,omitempty"`
	ThranRoomItems   []*ThranRoomInfo `protobuf:"bytes,12,rep,name=ThranRoomItems" json:"ThranRoomItems,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ACKThranConn) Reset()                    { *m = ACKThranConn{} }
func (m *ACKThranConn) String() string            { return proto.CompactTextString(m) }
func (*ACKThranConn) ProtoMessage()               {}
func (*ACKThranConn) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *ACKThranConn) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKThranConn) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ACKThranConn) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *ACKThranConn) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *ACKThranConn) GetPassWord() string {
	if m != nil && m.PassWord != nil {
		return *m.PassWord
	}
	return ""
}

func (m *ACKThranConn) GetYuanBaoCnt() int32 {
	if m != nil && m.YuanBaoCnt != nil {
		return *m.YuanBaoCnt
	}
	return 0
}

func (m *ACKThranConn) GetCoinCnt() int64 {
	if m != nil && m.CoinCnt != nil {
		return *m.CoinCnt
	}
	return 0
}

func (m *ACKThranConn) GetRoomList() []*OGRoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *ACKThranConn) GetLoginId() int32 {
	if m != nil && m.LoginId != nil {
		return *m.LoginId
	}
	return 0
}

func (m *ACKThranConn) GetMatchRoomList() []*OGRoomInfo {
	if m != nil {
		return m.MatchRoomList
	}
	return nil
}

func (m *ACKThranConn) GetCertNoRole() []byte {
	if m != nil {
		return m.CertNoRole
	}
	return nil
}

func (m *ACKThranConn) GetThranRoomItems() []*ThranRoomInfo {
	if m != nil {
		return m.ThranRoomItems
	}
	return nil
}

// 获取短证书  modify at 20120109  获取短证书
// THRANID_SVR_SHORTCERT = 0x00001005;//登录消息
type REQThranShortCert struct {
	UserName         *string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
	Pwd              *string `protobuf:"bytes,3,opt,name=Pwd" json:"Pwd,omitempty"`
	Sex              *int32  `protobuf:"varint,4,opt,name=Sex" json:"Sex,omitempty"`
	SecureID         *string `protobuf:"bytes,5,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,6,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,7,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,8,opt,name=GameId" json:"GameId,omitempty"`
	Token            *string `protobuf:"bytes,9,opt,name=token" json:"token,omitempty"`
	UserNameApl      []byte  `protobuf:"bytes,10,opt,name=UserNameApl" json:"UserNameApl,omitempty"`
	VerifyId         *int32  `protobuf:"varint,11,opt,name=VerifyId" json:"VerifyId,omitempty"`
	Ticket           *string `protobuf:"bytes,12,opt,name=Ticket" json:"Ticket,omitempty"`
	RoomAdapte       *int32  `protobuf:"varint,13,opt,name=RoomAdapte,def=0" json:"RoomAdapte,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranShortCert) Reset()                    { *m = REQThranShortCert{} }
func (m *REQThranShortCert) String() string            { return proto.CompactTextString(m) }
func (*REQThranShortCert) ProtoMessage()               {}
func (*REQThranShortCert) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

const Default_REQThranShortCert_RoomAdapte int32 = 0

func (m *REQThranShortCert) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *REQThranShortCert) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *REQThranShortCert) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *REQThranShortCert) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *REQThranShortCert) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQThranShortCert) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQThranShortCert) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQThranShortCert) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQThranShortCert) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *REQThranShortCert) GetUserNameApl() []byte {
	if m != nil {
		return m.UserNameApl
	}
	return nil
}

func (m *REQThranShortCert) GetVerifyId() int32 {
	if m != nil && m.VerifyId != nil {
		return *m.VerifyId
	}
	return 0
}

func (m *REQThranShortCert) GetTicket() string {
	if m != nil && m.Ticket != nil {
		return *m.Ticket
	}
	return ""
}

func (m *REQThranShortCert) GetRoomAdapte() int32 {
	if m != nil && m.RoomAdapte != nil {
		return *m.RoomAdapte
	}
	return Default_REQThranShortCert_RoomAdapte
}

type ACKThranShortCert struct {
	AckResult        *int32        `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	ShortCert        []byte        `protobuf:"bytes,2,opt,name=ShortCert" json:"ShortCert,omitempty"`
	UserName         *string       `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	RoomList         []*OGRoomInfo `protobuf:"bytes,4,rep,name=RoomList" json:"RoomList,omitempty"`
	MatchRoomList    []*OGRoomInfo `protobuf:"bytes,5,rep,name=MatchRoomList" json:"MatchRoomList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ACKThranShortCert) Reset()                    { *m = ACKThranShortCert{} }
func (m *ACKThranShortCert) String() string            { return proto.CompactTextString(m) }
func (*ACKThranShortCert) ProtoMessage()               {}
func (*ACKThranShortCert) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *ACKThranShortCert) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKThranShortCert) GetShortCert() []byte {
	if m != nil {
		return m.ShortCert
	}
	return nil
}

func (m *ACKThranShortCert) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *ACKThranShortCert) GetRoomList() []*OGRoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *ACKThranShortCert) GetMatchRoomList() []*OGRoomInfo {
	if m != nil {
		return m.MatchRoomList
	}
	return nil
}

// 登录THRAN服务OpenId
// THRANID_SVR_REG = 0x00001004;//OpenId登录消息
type REQThranOpenId struct {
	UserName         []byte  `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Pwd              *string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	SecureID         *string `protobuf:"bytes,4,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,5,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,6,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,7,opt,name=GameId" json:"GameId,omitempty"`
	VerifyId         *int32  `protobuf:"varint,8,opt,name=VerifyId" json:"VerifyId,omitempty"`
	Ticket           *string `protobuf:"bytes,9,opt,name=Ticket" json:"Ticket,omitempty"`
	Token            *string `protobuf:"bytes,10,opt,name=token" json:"token,omitempty"`
	Thirdkey         *string `protobuf:"bytes,11,opt,name=Thirdkey" json:"Thirdkey,omitempty"`
	RoomAdapte       *int32  `protobuf:"varint,12,opt,name=RoomAdapte,def=0" json:"RoomAdapte,omitempty"`
	ThirdAppId       *string `protobuf:"bytes,13,opt,name=ThirdAppId" json:"ThirdAppId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranOpenId) Reset()                    { *m = REQThranOpenId{} }
func (m *REQThranOpenId) String() string            { return proto.CompactTextString(m) }
func (*REQThranOpenId) ProtoMessage()               {}
func (*REQThranOpenId) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

const Default_REQThranOpenId_RoomAdapte int32 = 0

func (m *REQThranOpenId) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

func (m *REQThranOpenId) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *REQThranOpenId) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *REQThranOpenId) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQThranOpenId) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQThranOpenId) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQThranOpenId) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQThranOpenId) GetVerifyId() int32 {
	if m != nil && m.VerifyId != nil {
		return *m.VerifyId
	}
	return 0
}

func (m *REQThranOpenId) GetTicket() string {
	if m != nil && m.Ticket != nil {
		return *m.Ticket
	}
	return ""
}

func (m *REQThranOpenId) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *REQThranOpenId) GetThirdkey() string {
	if m != nil && m.Thirdkey != nil {
		return *m.Thirdkey
	}
	return ""
}

func (m *REQThranOpenId) GetRoomAdapte() int32 {
	if m != nil && m.RoomAdapte != nil {
		return *m.RoomAdapte
	}
	return Default_REQThranOpenId_RoomAdapte
}

func (m *REQThranOpenId) GetThirdAppId() string {
	if m != nil && m.ThirdAppId != nil {
		return *m.ThirdAppId
	}
	return ""
}

type ACKThranOpenId struct {
	AckResult        *int32        `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	Cert             []byte        `protobuf:"bytes,2,opt,name=cert" json:"cert,omitempty"`
	UserName         []byte        `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	RoleName         []byte        `protobuf:"bytes,4,opt,name=RoleName" json:"RoleName,omitempty"`
	YuanBaoCnt       *int32        `protobuf:"varint,5,opt,name=YuanBaoCnt" json:"YuanBaoCnt,omitempty"`
	CoinCnt          *int64        `protobuf:"varint,6,opt,name=CoinCnt" json:"CoinCnt,omitempty"`
	RoomList         []*OGRoomInfo `protobuf:"bytes,7,rep,name=RoomList" json:"RoomList,omitempty"`
	MatchRoomList    []*OGRoomInfo `protobuf:"bytes,8,rep,name=MatchRoomList" json:"MatchRoomList,omitempty"`
	LoginId          *int32        `protobuf:"varint,9,opt,name=LoginId" json:"LoginId,omitempty"`
	CertNoRole       []byte        `protobuf:"bytes,10,opt,name=CertNoRole" json:"CertNoRole,omitempty"`
	AchvId           []int32       `protobuf:"varint,11,rep,name=AchvId" json:"AchvId,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ACKThranOpenId) Reset()                    { *m = ACKThranOpenId{} }
func (m *ACKThranOpenId) String() string            { return proto.CompactTextString(m) }
func (*ACKThranOpenId) ProtoMessage()               {}
func (*ACKThranOpenId) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *ACKThranOpenId) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKThranOpenId) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ACKThranOpenId) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

func (m *ACKThranOpenId) GetRoleName() []byte {
	if m != nil {
		return m.RoleName
	}
	return nil
}

func (m *ACKThranOpenId) GetYuanBaoCnt() int32 {
	if m != nil && m.YuanBaoCnt != nil {
		return *m.YuanBaoCnt
	}
	return 0
}

func (m *ACKThranOpenId) GetCoinCnt() int64 {
	if m != nil && m.CoinCnt != nil {
		return *m.CoinCnt
	}
	return 0
}

func (m *ACKThranOpenId) GetRoomList() []*OGRoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *ACKThranOpenId) GetMatchRoomList() []*OGRoomInfo {
	if m != nil {
		return m.MatchRoomList
	}
	return nil
}

func (m *ACKThranOpenId) GetLoginId() int32 {
	if m != nil && m.LoginId != nil {
		return *m.LoginId
	}
	return 0
}

func (m *ACKThranOpenId) GetCertNoRole() []byte {
	if m != nil {
		return m.CertNoRole
	}
	return nil
}

func (m *ACKThranOpenId) GetAchvId() []int32 {
	if m != nil {
		return m.AchvId
	}
	return nil
}

// 新浪微游戏操作
// THRANID_SVR_SINAGAME = 0x00003007;//新浪微游戏相关
type REQSinaGame struct {
	Thirdkey         *string        `protobuf:"bytes,1,opt,name=Thirdkey" json:"Thirdkey,omitempty"`
	InfoList         []*SinaApiInfo `protobuf:"bytes,2,rep,name=InfoList" json:"InfoList,omitempty"`
	SecureID         *string        `protobuf:"bytes,4,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32         `protobuf:"varint,5,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string        `protobuf:"bytes,6,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32         `protobuf:"varint,7,opt,name=GameId" json:"GameId,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *REQSinaGame) Reset()                    { *m = REQSinaGame{} }
func (m *REQSinaGame) String() string            { return proto.CompactTextString(m) }
func (*REQSinaGame) ProtoMessage()               {}
func (*REQSinaGame) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *REQSinaGame) GetThirdkey() string {
	if m != nil && m.Thirdkey != nil {
		return *m.Thirdkey
	}
	return ""
}

func (m *REQSinaGame) GetInfoList() []*SinaApiInfo {
	if m != nil {
		return m.InfoList
	}
	return nil
}

func (m *REQSinaGame) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQSinaGame) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQSinaGame) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQSinaGame) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

type ACKSinaGame struct {
	AckResult        *int32        `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	RetList          []*SinaApiRet `protobuf:"bytes,2,rep,name=RetList" json:"RetList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ACKSinaGame) Reset()                    { *m = ACKSinaGame{} }
func (m *ACKSinaGame) String() string            { return proto.CompactTextString(m) }
func (*ACKSinaGame) ProtoMessage()               {}
func (*ACKSinaGame) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *ACKSinaGame) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKSinaGame) GetRetList() []*SinaApiRet {
	if m != nil {
		return m.RetList
	}
	return nil
}

// 发送新浪微博
// THRANID_SVR_WEIBO = 0x00003005;//发送微博
type REQWeiBo struct {
	UserName         []byte  `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Pwd              *string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	SecureID         *string `protobuf:"bytes,4,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,5,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,6,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,7,opt,name=GameId" json:"GameId,omitempty"`
	Token            *string `protobuf:"bytes,8,opt,name=token" json:"token,omitempty"`
	WbMsg            []byte  `protobuf:"bytes,9,opt,name=wbMsg" json:"wbMsg,omitempty"`
	WbPic            []byte  `protobuf:"bytes,10,opt,name=wbPic" json:"wbPic,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQWeiBo) Reset()                    { *m = REQWeiBo{} }
func (m *REQWeiBo) String() string            { return proto.CompactTextString(m) }
func (*REQWeiBo) ProtoMessage()               {}
func (*REQWeiBo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *REQWeiBo) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

func (m *REQWeiBo) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *REQWeiBo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *REQWeiBo) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQWeiBo) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQWeiBo) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQWeiBo) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQWeiBo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *REQWeiBo) GetWbMsg() []byte {
	if m != nil {
		return m.WbMsg
	}
	return nil
}

func (m *REQWeiBo) GetWbPic() []byte {
	if m != nil {
		return m.WbPic
	}
	return nil
}

type ACKWeiBo struct {
	AckResult        *int32 `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ACKWeiBo) Reset()                    { *m = ACKWeiBo{} }
func (m *ACKWeiBo) String() string            { return proto.CompactTextString(m) }
func (*ACKWeiBo) ProtoMessage()               {}
func (*ACKWeiBo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func (m *ACKWeiBo) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

// 退出
// THRANID_SVR_EXIT = 0x00001002;//退出消息
type REQThranExit struct {
	LoginId          *int32  `protobuf:"varint,1,opt,name=LoginId" json:"LoginId,omitempty"`
	ExitType         *int32  `protobuf:"varint,2,opt,name=ExitType" json:"ExitType,omitempty"`
	ExitMsg          *string `protobuf:"bytes,3,opt,name=ExitMsg" json:"ExitMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranExit) Reset()                    { *m = REQThranExit{} }
func (m *REQThranExit) String() string            { return proto.CompactTextString(m) }
func (*REQThranExit) ProtoMessage()               {}
func (*REQThranExit) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{12} }

func (m *REQThranExit) GetLoginId() int32 {
	if m != nil && m.LoginId != nil {
		return *m.LoginId
	}
	return 0
}

func (m *REQThranExit) GetExitType() int32 {
	if m != nil && m.ExitType != nil {
		return *m.ExitType
	}
	return 0
}

func (m *REQThranExit) GetExitMsg() string {
	if m != nil && m.ExitMsg != nil {
		return *m.ExitMsg
	}
	return ""
}

// 获取游戏版本信息
// THRANID_SVR_VERSION = 0x00003001;//索蓝游戏版本消息
type REQThranGameVersion struct {
	CurVersion       *int32  `protobuf:"varint,1,opt,name=CurVersion" json:"CurVersion,omitempty"`
	GameId           *int32  `protobuf:"varint,2,opt,name=GameId" json:"GameId,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,3,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ResolutionID     *string `protobuf:"bytes,4,opt,name=ResolutionID" json:"ResolutionID,omitempty"`
	ChannelID        *string `protobuf:"bytes,5,opt,name=ChannelID" json:"ChannelID,omitempty"`
	LanguageID       *string `protobuf:"bytes,6,opt,name=LanguageID" json:"LanguageID,omitempty"`
	SmallVersion     *int32  `protobuf:"varint,7,opt,name=smallVersion" json:"smallVersion,omitempty"`
	ClientType       *string `protobuf:"bytes,8,opt,name=ClientType" json:"ClientType,omitempty"`
	ScreenSize       *string `protobuf:"bytes,9,opt,name=ScreenSize" json:"ScreenSize,omitempty"`
	RoomAdapte       *int32  `protobuf:"varint,10,opt,name=RoomAdapte,def=0" json:"RoomAdapte,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranGameVersion) Reset()                    { *m = REQThranGameVersion{} }
func (m *REQThranGameVersion) String() string            { return proto.CompactTextString(m) }
func (*REQThranGameVersion) ProtoMessage()               {}
func (*REQThranGameVersion) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{13} }

const Default_REQThranGameVersion_RoomAdapte int32 = 0

func (m *REQThranGameVersion) GetCurVersion() int32 {
	if m != nil && m.CurVersion != nil {
		return *m.CurVersion
	}
	return 0
}

func (m *REQThranGameVersion) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQThranGameVersion) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQThranGameVersion) GetResolutionID() string {
	if m != nil && m.ResolutionID != nil {
		return *m.ResolutionID
	}
	return ""
}

func (m *REQThranGameVersion) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQThranGameVersion) GetLanguageID() string {
	if m != nil && m.LanguageID != nil {
		return *m.LanguageID
	}
	return ""
}

func (m *REQThranGameVersion) GetSmallVersion() int32 {
	if m != nil && m.SmallVersion != nil {
		return *m.SmallVersion
	}
	return 0
}

func (m *REQThranGameVersion) GetClientType() string {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return ""
}

func (m *REQThranGameVersion) GetScreenSize() string {
	if m != nil && m.ScreenSize != nil {
		return *m.ScreenSize
	}
	return ""
}

func (m *REQThranGameVersion) GetRoomAdapte() int32 {
	if m != nil && m.RoomAdapte != nil {
		return *m.RoomAdapte
	}
	return Default_REQThranGameVersion_RoomAdapte
}

type ACKThranGameVersion struct {
	AckResult        *int32              `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	PlayEnable       *string             `protobuf:"bytes,2,opt,name=PlayEnable" json:"PlayEnable,omitempty"`
	DownloadUrl      *string             `protobuf:"bytes,3,opt,name=DownloadUrl" json:"DownloadUrl,omitempty"`
	GameServerIp     *string             `protobuf:"bytes,4,opt,name=GameServerIp" json:"GameServerIp,omitempty"`
	GameServerPort   *string             `protobuf:"bytes,5,opt,name=GameServerPort" json:"GameServerPort,omitempty"`
	GameRankEnable   *string             `protobuf:"bytes,6,opt,name=GameRankEnable" json:"GameRankEnable,omitempty"`
	GameRankDef      *string             `protobuf:"bytes,7,opt,name=GameRankDef" json:"GameRankDef,omitempty"`
	IfPreserve       *string             `protobuf:"bytes,8,opt,name=IfPreserve" json:"IfPreserve,omitempty"`
	PreserveMsg      *string             `protobuf:"bytes,9,opt,name=PreserveMsg" json:"PreserveMsg,omitempty"`
	MatchInfoList    []*OGThranMatchInfo `protobuf:"bytes,10,rep,name=MatchInfoList" json:"MatchInfoList,omitempty"`
	DownloadReasion  *int32              `protobuf:"varint,11,opt,name=DownloadReasion" json:"DownloadReasion,omitempty"`
	GameId           *int32              `protobuf:"varint,12,opt,name=GameId" json:"GameId,omitempty"`
	GameSort         *int32              `protobuf:"varint,13,opt,name=gameSort" json:"gameSort,omitempty"`
	MatchRoomList    []*OGRoomInfo       `protobuf:"bytes,14,rep,name=MatchRoomList" json:"MatchRoomList,omitempty"`
	JssList          []*ThranJSSInfo     `protobuf:"bytes,15,rep,name=JssList" json:"JssList,omitempty"`
	IfSearch         *string             `protobuf:"bytes,16,opt,name=IfSearch" json:"IfSearch,omitempty"`
	BulletinList     []*OGBulletinInfo   `protobuf:"bytes,17,rep,name=BulletinList" json:"BulletinList,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ACKThranGameVersion) Reset()                    { *m = ACKThranGameVersion{} }
func (m *ACKThranGameVersion) String() string            { return proto.CompactTextString(m) }
func (*ACKThranGameVersion) ProtoMessage()               {}
func (*ACKThranGameVersion) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{14} }

func (m *ACKThranGameVersion) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKThranGameVersion) GetPlayEnable() string {
	if m != nil && m.PlayEnable != nil {
		return *m.PlayEnable
	}
	return ""
}

func (m *ACKThranGameVersion) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *ACKThranGameVersion) GetGameServerIp() string {
	if m != nil && m.GameServerIp != nil {
		return *m.GameServerIp
	}
	return ""
}

func (m *ACKThranGameVersion) GetGameServerPort() string {
	if m != nil && m.GameServerPort != nil {
		return *m.GameServerPort
	}
	return ""
}

func (m *ACKThranGameVersion) GetGameRankEnable() string {
	if m != nil && m.GameRankEnable != nil {
		return *m.GameRankEnable
	}
	return ""
}

func (m *ACKThranGameVersion) GetGameRankDef() string {
	if m != nil && m.GameRankDef != nil {
		return *m.GameRankDef
	}
	return ""
}

func (m *ACKThranGameVersion) GetIfPreserve() string {
	if m != nil && m.IfPreserve != nil {
		return *m.IfPreserve
	}
	return ""
}

func (m *ACKThranGameVersion) GetPreserveMsg() string {
	if m != nil && m.PreserveMsg != nil {
		return *m.PreserveMsg
	}
	return ""
}

func (m *ACKThranGameVersion) GetMatchInfoList() []*OGThranMatchInfo {
	if m != nil {
		return m.MatchInfoList
	}
	return nil
}

func (m *ACKThranGameVersion) GetDownloadReasion() int32 {
	if m != nil && m.DownloadReasion != nil {
		return *m.DownloadReasion
	}
	return 0
}

func (m *ACKThranGameVersion) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *ACKThranGameVersion) GetGameSort() int32 {
	if m != nil && m.GameSort != nil {
		return *m.GameSort
	}
	return 0
}

func (m *ACKThranGameVersion) GetMatchRoomList() []*OGRoomInfo {
	if m != nil {
		return m.MatchRoomList
	}
	return nil
}

func (m *ACKThranGameVersion) GetJssList() []*ThranJSSInfo {
	if m != nil {
		return m.JssList
	}
	return nil
}

func (m *ACKThranGameVersion) GetIfSearch() string {
	if m != nil && m.IfSearch != nil {
		return *m.IfSearch
	}
	return ""
}

func (m *ACKThranGameVersion) GetBulletinList() []*OGBulletinInfo {
	if m != nil {
		return m.BulletinList
	}
	return nil
}

// 获取验证码
// THRANID_SVR_VERIFY = 0x00003003;//获取验证码信息
type REQThranNewVerify struct {
	SecureID         *string `protobuf:"bytes,1,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,2,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,3,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,4,opt,name=GameId" json:"GameId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranNewVerify) Reset()                    { *m = REQThranNewVerify{} }
func (m *REQThranNewVerify) String() string            { return proto.CompactTextString(m) }
func (*REQThranNewVerify) ProtoMessage()               {}
func (*REQThranNewVerify) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{15} }

func (m *REQThranNewVerify) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQThranNewVerify) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQThranNewVerify) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQThranNewVerify) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

type ACKThranNewVerify struct {
	AckResult        *int32  `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	ErrorStr         *string `protobuf:"bytes,2,opt,name=ErrorStr" json:"ErrorStr,omitempty"`
	Verify           []byte  `protobuf:"bytes,3,opt,name=Verify" json:"Verify,omitempty"`
	VerifyId         *int32  `protobuf:"varint,4,opt,name=VerifyId" json:"VerifyId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ACKThranNewVerify) Reset()                    { *m = ACKThranNewVerify{} }
func (m *ACKThranNewVerify) String() string            { return proto.CompactTextString(m) }
func (*ACKThranNewVerify) ProtoMessage()               {}
func (*ACKThranNewVerify) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{16} }

func (m *ACKThranNewVerify) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKThranNewVerify) GetErrorStr() string {
	if m != nil && m.ErrorStr != nil {
		return *m.ErrorStr
	}
	return ""
}

func (m *ACKThranNewVerify) GetVerify() []byte {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *ACKThranNewVerify) GetVerifyId() int32 {
	if m != nil && m.VerifyId != nil {
		return *m.VerifyId
	}
	return 0
}

// 找回密码功能
// THRANID_SVR_FINDPWD = 0x00003002;//找回密码功能
// 新设置的密码未设置，表示只发送密码而不重置
// 新设置的密码不未空时，表示需要用户点击邮箱中的链接才能重置成功，且更新用户状态为已激活
type REQThranFindPwd struct {
	Email            *string `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	NewPwd           *string `protobuf:"bytes,2,opt,name=NewPwd" json:"NewPwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQThranFindPwd) Reset()                    { *m = REQThranFindPwd{} }
func (m *REQThranFindPwd) String() string            { return proto.CompactTextString(m) }
func (*REQThranFindPwd) ProtoMessage()               {}
func (*REQThranFindPwd) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{17} }

func (m *REQThranFindPwd) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *REQThranFindPwd) GetNewPwd() string {
	if m != nil && m.NewPwd != nil {
		return *m.NewPwd
	}
	return ""
}

type ACKThranFindPwd struct {
	AckResult        *int32 `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ACKThranFindPwd) Reset()                    { *m = ACKThranFindPwd{} }
func (m *ACKThranFindPwd) String() string            { return proto.CompactTextString(m) }
func (*ACKThranFindPwd) ProtoMessage()               {}
func (*ACKThranFindPwd) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{18} }

func (m *ACKThranFindPwd) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

// Thran心跳
// THRANID_SVR_HEART = 0x00003006;//thran的心跳
// REQ只有消息头，没有消息体
type ACKThranHeart struct {
	ServTime         *string `protobuf:"bytes,1,opt,name=ServTime" json:"ServTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ACKThranHeart) Reset()                    { *m = ACKThranHeart{} }
func (m *ACKThranHeart) String() string            { return proto.CompactTextString(m) }
func (*ACKThranHeart) ProtoMessage()               {}
func (*ACKThranHeart) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{19} }

func (m *ACKThranHeart) GetServTime() string {
	if m != nil && m.ServTime != nil {
		return *m.ServTime
	}
	return ""
}

// 相关的结构
// 新浪微游戏结构
type SinaApiInfo struct {
	ApiType          *int32  `protobuf:"varint,1,opt,name=ApiType" json:"ApiType,omitempty"`
	RetValue         *string `protobuf:"bytes,2,opt,name=RetValue" json:"RetValue,omitempty"`
	UserId           *string `protobuf:"bytes,3,opt,name=UserId" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SinaApiInfo) Reset()                    { *m = SinaApiInfo{} }
func (m *SinaApiInfo) String() string            { return proto.CompactTextString(m) }
func (*SinaApiInfo) ProtoMessage()               {}
func (*SinaApiInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{20} }

func (m *SinaApiInfo) GetApiType() int32 {
	if m != nil && m.ApiType != nil {
		return *m.ApiType
	}
	return 0
}

func (m *SinaApiInfo) GetRetValue() string {
	if m != nil && m.RetValue != nil {
		return *m.RetValue
	}
	return ""
}

func (m *SinaApiInfo) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

// 新浪微游戏结果返回结构
type SinaApiRet struct {
	RetResult        *int32  `protobuf:"varint,1,opt,name=RetResult" json:"RetResult,omitempty"`
	ApiType          *int32  `protobuf:"varint,2,opt,name=ApiType" json:"ApiType,omitempty"`
	RetValue         *string `protobuf:"bytes,3,opt,name=RetValue" json:"RetValue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SinaApiRet) Reset()                    { *m = SinaApiRet{} }
func (m *SinaApiRet) String() string            { return proto.CompactTextString(m) }
func (*SinaApiRet) ProtoMessage()               {}
func (*SinaApiRet) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{21} }

func (m *SinaApiRet) GetRetResult() int32 {
	if m != nil && m.RetResult != nil {
		return *m.RetResult
	}
	return 0
}

func (m *SinaApiRet) GetApiType() int32 {
	if m != nil && m.ApiType != nil {
		return *m.ApiType
	}
	return 0
}

func (m *SinaApiRet) GetRetValue() string {
	if m != nil && m.RetValue != nil {
		return *m.RetValue
	}
	return ""
}

// 游戏房间结构
type OGRoomInfo struct {
	RoomId           *string `protobuf:"bytes,1,opt,name=RoomId" json:"RoomId,omitempty"`
	RoomRank         *string `protobuf:"bytes,2,opt,name=RoomRank" json:"RoomRank,omitempty"`
	RoomIp           *string `protobuf:"bytes,3,opt,name=RoomIp" json:"RoomIp,omitempty"`
	RoomPort         *string `protobuf:"bytes,4,opt,name=RoomPort" json:"RoomPort,omitempty"`
	RoomStatus       *string `protobuf:"bytes,5,opt,name=RoomStatus" json:"RoomStatus,omitempty"`
	RoomMinGold      *string `protobuf:"bytes,6,opt,name=RoomMinGold" json:"RoomMinGold,omitempty"`
	RoomMaxGold      *string `protobuf:"bytes,7,opt,name=RoomMaxGold" json:"RoomMaxGold,omitempty"`
	RoomMinPlay      *string `protobuf:"bytes,8,opt,name=RoomMinPlay" json:"RoomMinPlay,omitempty"`
	RoomType         *string `protobuf:"bytes,9,opt,name=RoomType" json:"RoomType,omitempty"`
	ServerType       *string `protobuf:"bytes,10,opt,name=ServerType" json:"ServerType,omitempty"`
	Description      *string `protobuf:"bytes,11,opt,name=Description" json:"Description,omitempty"`
	RoomName         *string `protobuf:"bytes,12,opt,name=RoomName" json:"RoomName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OGRoomInfo) Reset()                    { *m = OGRoomInfo{} }
func (m *OGRoomInfo) String() string            { return proto.CompactTextString(m) }
func (*OGRoomInfo) ProtoMessage()               {}
func (*OGRoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{22} }

func (m *OGRoomInfo) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

func (m *OGRoomInfo) GetRoomRank() string {
	if m != nil && m.RoomRank != nil {
		return *m.RoomRank
	}
	return ""
}

func (m *OGRoomInfo) GetRoomIp() string {
	if m != nil && m.RoomIp != nil {
		return *m.RoomIp
	}
	return ""
}

func (m *OGRoomInfo) GetRoomPort() string {
	if m != nil && m.RoomPort != nil {
		return *m.RoomPort
	}
	return ""
}

func (m *OGRoomInfo) GetRoomStatus() string {
	if m != nil && m.RoomStatus != nil {
		return *m.RoomStatus
	}
	return ""
}

func (m *OGRoomInfo) GetRoomMinGold() string {
	if m != nil && m.RoomMinGold != nil {
		return *m.RoomMinGold
	}
	return ""
}

func (m *OGRoomInfo) GetRoomMaxGold() string {
	if m != nil && m.RoomMaxGold != nil {
		return *m.RoomMaxGold
	}
	return ""
}

func (m *OGRoomInfo) GetRoomMinPlay() string {
	if m != nil && m.RoomMinPlay != nil {
		return *m.RoomMinPlay
	}
	return ""
}

func (m *OGRoomInfo) GetRoomType() string {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return ""
}

func (m *OGRoomInfo) GetServerType() string {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return ""
}

func (m *OGRoomInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *OGRoomInfo) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

// 比赛信息结构
type OGThranMatchInfo struct {
	MatchID   *int32  `protobuf:"varint,1,opt,name=MatchID" json:"MatchID,omitempty"`
	MatchName *string `protobuf:"bytes,2,opt,name=MatchName" json:"MatchName,omitempty"`
	// 以下参数在斗地主比赛中应用
	AwardName        *string `protobuf:"bytes,3,opt,name=AwardName" json:"AwardName,omitempty"`
	AwardSum         *int32  `protobuf:"varint,4,opt,name=AwardSum" json:"AwardSum,omitempty"`
	MatchTerm        *string `protobuf:"bytes,5,opt,name=MatchTerm" json:"MatchTerm,omitempty"`
	HumanLimit       *int32  `protobuf:"varint,6,opt,name=HumanLimit" json:"HumanLimit,omitempty"`
	MatchHumanSum    *int32  `protobuf:"varint,7,opt,name=MatchHumanSum" json:"MatchHumanSum,omitempty"`
	MatchType        *int32  `protobuf:"varint,8,opt,name=MatchType" json:"MatchType,omitempty"`
	MatchInterval    *int32  `protobuf:"varint,9,opt,name=MatchInterval" json:"MatchInterval,omitempty"`
	MatchPrize       *string `protobuf:"bytes,10,opt,name=MatchPrize" json:"MatchPrize,omitempty"`
	MatchProcess     *string `protobuf:"bytes,11,opt,name=MatchProcess" json:"MatchProcess,omitempty"`
	MatchDate        *string `protobuf:"bytes,12,opt,name=MatchDate" json:"MatchDate,omitempty"`
	MatchFee         *string `protobuf:"bytes,13,opt,name=MatchFee" json:"MatchFee,omitempty"`
	MatchArea        *int32  `protobuf:"varint,14,opt,name=MatchArea" json:"MatchArea,omitempty"`
	Description      *string `protobuf:"bytes,15,opt,name=Description" json:"Description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OGThranMatchInfo) Reset()                    { *m = OGThranMatchInfo{} }
func (m *OGThranMatchInfo) String() string            { return proto.CompactTextString(m) }
func (*OGThranMatchInfo) ProtoMessage()               {}
func (*OGThranMatchInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{23} }

func (m *OGThranMatchInfo) GetMatchID() int32 {
	if m != nil && m.MatchID != nil {
		return *m.MatchID
	}
	return 0
}

func (m *OGThranMatchInfo) GetMatchName() string {
	if m != nil && m.MatchName != nil {
		return *m.MatchName
	}
	return ""
}

func (m *OGThranMatchInfo) GetAwardName() string {
	if m != nil && m.AwardName != nil {
		return *m.AwardName
	}
	return ""
}

func (m *OGThranMatchInfo) GetAwardSum() int32 {
	if m != nil && m.AwardSum != nil {
		return *m.AwardSum
	}
	return 0
}

func (m *OGThranMatchInfo) GetMatchTerm() string {
	if m != nil && m.MatchTerm != nil {
		return *m.MatchTerm
	}
	return ""
}

func (m *OGThranMatchInfo) GetHumanLimit() int32 {
	if m != nil && m.HumanLimit != nil {
		return *m.HumanLimit
	}
	return 0
}

func (m *OGThranMatchInfo) GetMatchHumanSum() int32 {
	if m != nil && m.MatchHumanSum != nil {
		return *m.MatchHumanSum
	}
	return 0
}

func (m *OGThranMatchInfo) GetMatchType() int32 {
	if m != nil && m.MatchType != nil {
		return *m.MatchType
	}
	return 0
}

func (m *OGThranMatchInfo) GetMatchInterval() int32 {
	if m != nil && m.MatchInterval != nil {
		return *m.MatchInterval
	}
	return 0
}

func (m *OGThranMatchInfo) GetMatchPrize() string {
	if m != nil && m.MatchPrize != nil {
		return *m.MatchPrize
	}
	return ""
}

func (m *OGThranMatchInfo) GetMatchProcess() string {
	if m != nil && m.MatchProcess != nil {
		return *m.MatchProcess
	}
	return ""
}

func (m *OGThranMatchInfo) GetMatchDate() string {
	if m != nil && m.MatchDate != nil {
		return *m.MatchDate
	}
	return ""
}

func (m *OGThranMatchInfo) GetMatchFee() string {
	if m != nil && m.MatchFee != nil {
		return *m.MatchFee
	}
	return ""
}

func (m *OGThranMatchInfo) GetMatchArea() int32 {
	if m != nil && m.MatchArea != nil {
		return *m.MatchArea
	}
	return 0
}

func (m *OGThranMatchInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

// 索蓝服务器的房间基本信息 modify at 20120217  索蓝酒吧骰子用
type ThranRoomInfo struct {
	GameID           *int32           `protobuf:"varint,1,opt,name=GameID" json:"GameID,omitempty"`
	GroupID          *int32           `protobuf:"varint,2,opt,name=GroupID" json:"GroupID,omitempty"`
	RoomID           []byte           `protobuf:"bytes,3,opt,name=RoomID" json:"RoomID,omitempty"`
	MaxPlayer        *int32           `protobuf:"varint,4,opt,name=MaxPlayer" json:"MaxPlayer,omitempty"`
	RoomIP           *string          `protobuf:"bytes,5,opt,name=RoomIP" json:"RoomIP,omitempty"`
	RoomPort         *int32           `protobuf:"varint,6,opt,name=RoomPort" json:"RoomPort,omitempty"`
	Context          []byte           `protobuf:"bytes,7,opt,name=Context" json:"Context,omitempty"`
	CurPlayer        *int32           `protobuf:"varint,8,opt,name=CurPlayer" json:"CurPlayer,omitempty"`
	RoomState        *int32           `protobuf:"varint,9,opt,name=RoomState" json:"RoomState,omitempty"`
	IsLock           *int32           `protobuf:"varint,10,opt,name=IsLock,def=0" json:"IsLock,omitempty"`
	ThranRoomItems   []*ThranRoomInfo `protobuf:"bytes,11,rep,name=ThranRoomItems" json:"ThranRoomItems,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ThranRoomInfo) Reset()                    { *m = ThranRoomInfo{} }
func (m *ThranRoomInfo) String() string            { return proto.CompactTextString(m) }
func (*ThranRoomInfo) ProtoMessage()               {}
func (*ThranRoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{24} }

const Default_ThranRoomInfo_IsLock int32 = 0

func (m *ThranRoomInfo) GetGameID() int32 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *ThranRoomInfo) GetGroupID() int32 {
	if m != nil && m.GroupID != nil {
		return *m.GroupID
	}
	return 0
}

func (m *ThranRoomInfo) GetRoomID() []byte {
	if m != nil {
		return m.RoomID
	}
	return nil
}

func (m *ThranRoomInfo) GetMaxPlayer() int32 {
	if m != nil && m.MaxPlayer != nil {
		return *m.MaxPlayer
	}
	return 0
}

func (m *ThranRoomInfo) GetRoomIP() string {
	if m != nil && m.RoomIP != nil {
		return *m.RoomIP
	}
	return ""
}

func (m *ThranRoomInfo) GetRoomPort() int32 {
	if m != nil && m.RoomPort != nil {
		return *m.RoomPort
	}
	return 0
}

func (m *ThranRoomInfo) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *ThranRoomInfo) GetCurPlayer() int32 {
	if m != nil && m.CurPlayer != nil {
		return *m.CurPlayer
	}
	return 0
}

func (m *ThranRoomInfo) GetRoomState() int32 {
	if m != nil && m.RoomState != nil {
		return *m.RoomState
	}
	return 0
}

func (m *ThranRoomInfo) GetIsLock() int32 {
	if m != nil && m.IsLock != nil {
		return *m.IsLock
	}
	return Default_ThranRoomInfo_IsLock
}

func (m *ThranRoomInfo) GetThranRoomItems() []*ThranRoomInfo {
	if m != nil {
		return m.ThranRoomItems
	}
	return nil
}

// 索蓝服务器配置的jss服务器  modify at 20120321
type ThranJSSInfo struct {
	RoomIP           *string `protobuf:"bytes,1,opt,name=RoomIP" json:"RoomIP,omitempty"`
	RoomPort         *string `protobuf:"bytes,2,opt,name=RoomPort" json:"RoomPort,omitempty"`
	Remark           *string `protobuf:"bytes,3,opt,name=Remark" json:"Remark,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ThranJSSInfo) Reset()                    { *m = ThranJSSInfo{} }
func (m *ThranJSSInfo) String() string            { return proto.CompactTextString(m) }
func (*ThranJSSInfo) ProtoMessage()               {}
func (*ThranJSSInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{25} }

func (m *ThranJSSInfo) GetRoomIP() string {
	if m != nil && m.RoomIP != nil {
		return *m.RoomIP
	}
	return ""
}

func (m *ThranJSSInfo) GetRoomPort() string {
	if m != nil && m.RoomPort != nil {
		return *m.RoomPort
	}
	return ""
}

func (m *ThranJSSInfo) GetRemark() string {
	if m != nil && m.Remark != nil {
		return *m.Remark
	}
	return ""
}

// 游戏公告
type OGBulletinInfo struct {
	Title            []byte `protobuf:"bytes,1,opt,name=Title" json:"Title,omitempty"`
	Content          []byte `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OGBulletinInfo) Reset()                    { *m = OGBulletinInfo{} }
func (m *OGBulletinInfo) String() string            { return proto.CompactTextString(m) }
func (*OGBulletinInfo) ProtoMessage()               {}
func (*OGBulletinInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{26} }

func (m *OGBulletinInfo) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *OGBulletinInfo) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// ***************************************************************//
// modify at 20120516
// 快速登录
// THRANID_SVR_QUICKCONN = 0x00001006;//快速登录
type REQQuickConn struct {
	UserName         []byte  `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Pwd              *string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
	SecureID         *string `protobuf:"bytes,3,opt,name=SecureID" json:"SecureID,omitempty"`
	ComeFromID       *int32  `protobuf:"varint,4,opt,name=ComeFromID" json:"ComeFromID,omitempty"`
	ChannelID        *string `protobuf:"bytes,5,opt,name=ChannelID" json:"ChannelID,omitempty"`
	GameId           *int32  `protobuf:"varint,6,opt,name=GameId" json:"GameId,omitempty"`
	Token            *string `protobuf:"bytes,7,opt,name=token" json:"token,omitempty"`
	RoomAdapte       *int32  `protobuf:"varint,8,opt,name=RoomAdapte,def=0" json:"RoomAdapte,omitempty"`
	LoginType        *int32  `protobuf:"varint,9,opt,name=LoginType,def=0" json:"LoginType,omitempty"`
	CurVersion       *int32  `protobuf:"varint,10,opt,name=CurVersion" json:"CurVersion,omitempty"`
	SmallVersion     *int32  `protobuf:"varint,11,opt,name=smallVersion" json:"smallVersion,omitempty"`
	ResolutionID     *string `protobuf:"bytes,12,opt,name=ResolutionID" json:"ResolutionID,omitempty"`
	LanguageID       *string `protobuf:"bytes,13,opt,name=LanguageID" json:"LanguageID,omitempty"`
	ScreenSize       *string `protobuf:"bytes,14,opt,name=ScreenSize" json:"ScreenSize,omitempty"`
	ThirdDigitalName *string `protobuf:"bytes,15,opt,name=ThirdDigitalName" json:"ThirdDigitalName,omitempty"`
	Thirdkey         *string `protobuf:"bytes,16,opt,name=Thirdkey" json:"Thirdkey,omitempty"`
	ThirdAppId       *string `protobuf:"bytes,17,opt,name=ThirdAppId" json:"ThirdAppId,omitempty"`
	UserId           *uint32 `protobuf:"varint,18,opt,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *REQQuickConn) Reset()                    { *m = REQQuickConn{} }
func (m *REQQuickConn) String() string            { return proto.CompactTextString(m) }
func (*REQQuickConn) ProtoMessage()               {}
func (*REQQuickConn) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{27} }

const Default_REQQuickConn_RoomAdapte int32 = 0
const Default_REQQuickConn_LoginType int32 = 0

func (m *REQQuickConn) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

func (m *REQQuickConn) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *REQQuickConn) GetSecureID() string {
	if m != nil && m.SecureID != nil {
		return *m.SecureID
	}
	return ""
}

func (m *REQQuickConn) GetComeFromID() int32 {
	if m != nil && m.ComeFromID != nil {
		return *m.ComeFromID
	}
	return 0
}

func (m *REQQuickConn) GetChannelID() string {
	if m != nil && m.ChannelID != nil {
		return *m.ChannelID
	}
	return ""
}

func (m *REQQuickConn) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *REQQuickConn) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *REQQuickConn) GetRoomAdapte() int32 {
	if m != nil && m.RoomAdapte != nil {
		return *m.RoomAdapte
	}
	return Default_REQQuickConn_RoomAdapte
}

func (m *REQQuickConn) GetLoginType() int32 {
	if m != nil && m.LoginType != nil {
		return *m.LoginType
	}
	return Default_REQQuickConn_LoginType
}

func (m *REQQuickConn) GetCurVersion() int32 {
	if m != nil && m.CurVersion != nil {
		return *m.CurVersion
	}
	return 0
}

func (m *REQQuickConn) GetSmallVersion() int32 {
	if m != nil && m.SmallVersion != nil {
		return *m.SmallVersion
	}
	return 0
}

func (m *REQQuickConn) GetResolutionID() string {
	if m != nil && m.ResolutionID != nil {
		return *m.ResolutionID
	}
	return ""
}

func (m *REQQuickConn) GetLanguageID() string {
	if m != nil && m.LanguageID != nil {
		return *m.LanguageID
	}
	return ""
}

func (m *REQQuickConn) GetScreenSize() string {
	if m != nil && m.ScreenSize != nil {
		return *m.ScreenSize
	}
	return ""
}

func (m *REQQuickConn) GetThirdDigitalName() string {
	if m != nil && m.ThirdDigitalName != nil {
		return *m.ThirdDigitalName
	}
	return ""
}

func (m *REQQuickConn) GetThirdkey() string {
	if m != nil && m.Thirdkey != nil {
		return *m.Thirdkey
	}
	return ""
}

func (m *REQQuickConn) GetThirdAppId() string {
	if m != nil && m.ThirdAppId != nil {
		return *m.ThirdAppId
	}
	return ""
}

func (m *REQQuickConn) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type ACKQuickConn struct {
	AckResult        *int32              `protobuf:"varint,1,opt,name=AckResult" json:"AckResult,omitempty"`
	UserId           *uint32             `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	UserName         *string             `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	RoleName         *string             `protobuf:"bytes,4,opt,name=RoleName" json:"RoleName,omitempty"`
	YuanBaoCnt       *int32              `protobuf:"varint,5,opt,name=YuanBaoCnt" json:"YuanBaoCnt,omitempty"`
	CoinCnt          *int64              `protobuf:"varint,6,opt,name=CoinCnt" json:"CoinCnt,omitempty"`
	RoomList         []*OGRoomInfo       `protobuf:"bytes,7,rep,name=RoomList" json:"RoomList,omitempty"`
	MatchRoomList    []*OGThranMatchInfo `protobuf:"bytes,8,rep,name=MatchRoomList" json:"MatchRoomList,omitempty"`
	Cert             []byte              `protobuf:"bytes,9,opt,name=Cert" json:"Cert,omitempty"`
	CertNoCert       []byte              `protobuf:"bytes,10,opt,name=CertNoCert" json:"CertNoCert,omitempty"`
	CurVersion       *int32              `protobuf:"varint,11,opt,name=CurVersion" json:"CurVersion,omitempty"`
	PlayEnable       *string             `protobuf:"bytes,12,opt,name=PlayEnable" json:"PlayEnable,omitempty"`
	DownloadUrl      *string             `protobuf:"bytes,13,opt,name=DownloadUrl" json:"DownloadUrl,omitempty"`
	IfPreserve       *string             `protobuf:"bytes,14,opt,name=IfPreserve" json:"IfPreserve,omitempty"`
	PreserveMsg      *string             `protobuf:"bytes,16,opt,name=PreserveMsg" json:"PreserveMsg,omitempty"`
	GameId           *int32              `protobuf:"varint,17,opt,name=GameId" json:"GameId,omitempty"`
	JssList          []*ThranJSSInfo     `protobuf:"bytes,18,rep,name=JssList" json:"JssList,omitempty"`
	IfSearch         *string             `protobuf:"bytes,19,opt,name=IfSearch" json:"IfSearch,omitempty"`
	BulletinList     []*OGBulletinInfo   `protobuf:"bytes,20,rep,name=BulletinList" json:"BulletinList,omitempty"`
	VersionInfo      *string             `protobuf:"bytes,21,opt,name=VersionInfo" json:"VersionInfo,omitempty"`
	MatchSvrList     []*OGRoomInfo       `protobuf:"bytes,22,rep,name=MatchSvrList" json:"MatchSvrList,omitempty"`
	Sex              *int32              `protobuf:"varint,23,opt,name=Sex" json:"Sex,omitempty"`
	RoomSvrList      []*OGRoomInfo       `protobuf:"bytes,24,rep,name=RoomSvrList" json:"RoomSvrList,omitempty"`
	DdzActive        *int32              `protobuf:"varint,25,opt,name=DdzActive,def=0" json:"DdzActive,omitempty"`
	MsgUrl           *string             `protobuf:"bytes,26,opt,name=MsgUrl" json:"MsgUrl,omitempty"`
	ErrorCode        *int32              `protobuf:"varint,27,opt,name=ErrorCode,def=0" json:"ErrorCode,omitempty"`
	NickName         *string             `protobuf:"bytes,28,opt,name=NickName" json:"NickName,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ACKQuickConn) Reset()                    { *m = ACKQuickConn{} }
func (m *ACKQuickConn) String() string            { return proto.CompactTextString(m) }
func (*ACKQuickConn) ProtoMessage()               {}
func (*ACKQuickConn) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{28} }

const Default_ACKQuickConn_DdzActive int32 = 0
const Default_ACKQuickConn_ErrorCode int32 = 0

func (m *ACKQuickConn) GetAckResult() int32 {
	if m != nil && m.AckResult != nil {
		return *m.AckResult
	}
	return 0
}

func (m *ACKQuickConn) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ACKQuickConn) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *ACKQuickConn) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *ACKQuickConn) GetYuanBaoCnt() int32 {
	if m != nil && m.YuanBaoCnt != nil {
		return *m.YuanBaoCnt
	}
	return 0
}

func (m *ACKQuickConn) GetCoinCnt() int64 {
	if m != nil && m.CoinCnt != nil {
		return *m.CoinCnt
	}
	return 0
}

func (m *ACKQuickConn) GetRoomList() []*OGRoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *ACKQuickConn) GetMatchRoomList() []*OGThranMatchInfo {
	if m != nil {
		return m.MatchRoomList
	}
	return nil
}

func (m *ACKQuickConn) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ACKQuickConn) GetCertNoCert() []byte {
	if m != nil {
		return m.CertNoCert
	}
	return nil
}

func (m *ACKQuickConn) GetCurVersion() int32 {
	if m != nil && m.CurVersion != nil {
		return *m.CurVersion
	}
	return 0
}

func (m *ACKQuickConn) GetPlayEnable() string {
	if m != nil && m.PlayEnable != nil {
		return *m.PlayEnable
	}
	return ""
}

func (m *ACKQuickConn) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *ACKQuickConn) GetIfPreserve() string {
	if m != nil && m.IfPreserve != nil {
		return *m.IfPreserve
	}
	return ""
}

func (m *ACKQuickConn) GetPreserveMsg() string {
	if m != nil && m.PreserveMsg != nil {
		return *m.PreserveMsg
	}
	return ""
}

func (m *ACKQuickConn) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *ACKQuickConn) GetJssList() []*ThranJSSInfo {
	if m != nil {
		return m.JssList
	}
	return nil
}

func (m *ACKQuickConn) GetIfSearch() string {
	if m != nil && m.IfSearch != nil {
		return *m.IfSearch
	}
	return ""
}

func (m *ACKQuickConn) GetBulletinList() []*OGBulletinInfo {
	if m != nil {
		return m.BulletinList
	}
	return nil
}

func (m *ACKQuickConn) GetVersionInfo() string {
	if m != nil && m.VersionInfo != nil {
		return *m.VersionInfo
	}
	return ""
}

func (m *ACKQuickConn) GetMatchSvrList() []*OGRoomInfo {
	if m != nil {
		return m.MatchSvrList
	}
	return nil
}

func (m *ACKQuickConn) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *ACKQuickConn) GetRoomSvrList() []*OGRoomInfo {
	if m != nil {
		return m.RoomSvrList
	}
	return nil
}

func (m *ACKQuickConn) GetDdzActive() int32 {
	if m != nil && m.DdzActive != nil {
		return *m.DdzActive
	}
	return Default_ACKQuickConn_DdzActive
}

func (m *ACKQuickConn) GetMsgUrl() string {
	if m != nil && m.MsgUrl != nil {
		return *m.MsgUrl
	}
	return ""
}

func (m *ACKQuickConn) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_ACKQuickConn_ErrorCode
}

func (m *ACKQuickConn) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

type NullMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NullMsg) Reset()                    { *m = NullMsg{} }
func (m *NullMsg) String() string            { return proto.CompactTextString(m) }
func (*NullMsg) ProtoMessage()               {}
func (*NullMsg) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{29} }

// 新增用户的时候,发送广播
type Game_SendAddUser struct {
	Matchid          []byte  `protobuf:"bytes,1,opt,name=Matchid" json:"Matchid,omitempty"`
	Tableid          *int32  `protobuf:"varint,2,opt,name=Tableid" json:"Tableid,omitempty"`
	NickName         *string `protobuf:"bytes,3,opt,name=NickName" json:"NickName,omitempty"`
	Coin             *int64  `protobuf:"varint,4,opt,name=Coin" json:"Coin,omitempty"`
	Seat             *int32  `protobuf:"varint,5,opt,name=seat" json:"seat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_SendAddUser) Reset()                    { *m = Game_SendAddUser{} }
func (m *Game_SendAddUser) String() string            { return proto.CompactTextString(m) }
func (*Game_SendAddUser) ProtoMessage()               {}
func (*Game_SendAddUser) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{30} }

func (m *Game_SendAddUser) GetMatchid() []byte {
	if m != nil {
		return m.Matchid
	}
	return nil
}

func (m *Game_SendAddUser) GetTableid() int32 {
	if m != nil && m.Tableid != nil {
		return *m.Tableid
	}
	return 0
}

func (m *Game_SendAddUser) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *Game_SendAddUser) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *Game_SendAddUser) GetSeat() int32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func init() {
	proto.RegisterType((*REQThranReg)(nil), "bbproto.REQThranReg")
	proto.RegisterType((*ACKThranReg)(nil), "bbproto.ACKThranReg")
	proto.RegisterType((*REQThranConn)(nil), "bbproto.REQThranConn")
	proto.RegisterType((*ACKThranConn)(nil), "bbproto.ACKThranConn")
	proto.RegisterType((*REQThranShortCert)(nil), "bbproto.REQThranShortCert")
	proto.RegisterType((*ACKThranShortCert)(nil), "bbproto.ACKThranShortCert")
	proto.RegisterType((*REQThranOpenId)(nil), "bbproto.REQThranOpenId")
	proto.RegisterType((*ACKThranOpenId)(nil), "bbproto.ACKThranOpenId")
	proto.RegisterType((*REQSinaGame)(nil), "bbproto.REQSinaGame")
	proto.RegisterType((*ACKSinaGame)(nil), "bbproto.ACKSinaGame")
	proto.RegisterType((*REQWeiBo)(nil), "bbproto.REQWeiBo")
	proto.RegisterType((*ACKWeiBo)(nil), "bbproto.ACKWeiBo")
	proto.RegisterType((*REQThranExit)(nil), "bbproto.REQThranExit")
	proto.RegisterType((*REQThranGameVersion)(nil), "bbproto.REQThranGameVersion")
	proto.RegisterType((*ACKThranGameVersion)(nil), "bbproto.ACKThranGameVersion")
	proto.RegisterType((*REQThranNewVerify)(nil), "bbproto.REQThranNewVerify")
	proto.RegisterType((*ACKThranNewVerify)(nil), "bbproto.ACKThranNewVerify")
	proto.RegisterType((*REQThranFindPwd)(nil), "bbproto.REQThranFindPwd")
	proto.RegisterType((*ACKThranFindPwd)(nil), "bbproto.ACKThranFindPwd")
	proto.RegisterType((*ACKThranHeart)(nil), "bbproto.ACKThranHeart")
	proto.RegisterType((*SinaApiInfo)(nil), "bbproto.SinaApiInfo")
	proto.RegisterType((*SinaApiRet)(nil), "bbproto.SinaApiRet")
	proto.RegisterType((*OGRoomInfo)(nil), "bbproto.OGRoomInfo")
	proto.RegisterType((*OGThranMatchInfo)(nil), "bbproto.OGThranMatchInfo")
	proto.RegisterType((*ThranRoomInfo)(nil), "bbproto.ThranRoomInfo")
	proto.RegisterType((*ThranJSSInfo)(nil), "bbproto.ThranJSSInfo")
	proto.RegisterType((*OGBulletinInfo)(nil), "bbproto.OGBulletinInfo")
	proto.RegisterType((*REQQuickConn)(nil), "bbproto.REQQuickConn")
	proto.RegisterType((*ACKQuickConn)(nil), "bbproto.ACKQuickConn")
	proto.RegisterType((*NullMsg)(nil), "bbproto.NullMsg")
	proto.RegisterType((*Game_SendAddUser)(nil), "bbproto.game_SendAddUser")
}

var fileDescriptor7 = []byte{
	// 1827 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe4, 0x58, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x86, 0x24, 0xeb, 0x6b, 0xf5, 0x65, 0xcb, 0x76, 0xa2, 0xbc, 0x1f, 0xc0, 0xfb, 0x12, 0x79,
	0x83, 0xbc, 0x05, 0x6a, 0x18, 0x3d, 0xf6, 0x14, 0xd9, 0xb2, 0x1d, 0xa5, 0x8e, 0xa3, 0x88, 0x4a,
	0x82, 0x16, 0x05, 0x0a, 0x5a, 0x5c, 0x4b, 0x84, 0x29, 0x52, 0x58, 0x52, 0xfe, 0xc8, 0xb1, 0xbf,
	0xa0, 0xd7, 0x5c, 0xfa, 0x0f, 0x7a, 0xe9, 0xb1, 0x3f, 0xa1, 0x7f, 0xa0, 0xc7, 0x9e, 0x7a, 0xe9,
	0xa5, 0x3d, 0x14, 0xe8, 0xb5, 0xb3, 0xc3, 0x1d, 0x2e, 0x29, 0xd1, 0x81, 0x03, 0x04, 0xed, 0xa1,
	0x27, 0x9b, 0xb3, 0xbb, 0xb3, 0x33, 0xcf, 0xcc, 0x3c, 0x3b, 0x23, 0xc6, 0xfc, 0x49, 0x38, 0xdd,
	0x99, 0x0b, 0x3f, 0xf4, 0xdb, 0xe5, 0xd3, 0x53, 0xfc, 0xc7, 0xf8, 0x29, 0xc7, 0x6a, 0xc3, 0x83,
	0xe7, 0xa3, 0xa9, 0xb0, 0xbc, 0x21, 0x9f, 0xb4, 0xd7, 0x59, 0xe5, 0x45, 0xc0, 0xc5, 0x89, 0x35,
	0xe3, 0x9d, 0xdc, 0x7f, 0x72, 0x0f, 0xab, 0xed, 0x1a, 0x2b, 0x0c, 0x2e, 0xed, 0x4e, 0x1e, 0x3f,
	0x60, 0xf9, 0x25, 0x17, 0xce, 0xd9, 0x75, 0xdf, 0xee, 0x14, 0x40, 0x52, 0x6c, 0x6f, 0xb0, 0x6a,
	0x24, 0x31, 0x43, 0xd1, 0x59, 0xa3, 0x4d, 0x26, 0x1f, 0x2f, 0x04, 0xef, 0xf7, 0x3a, 0x45, 0x94,
	0xb4, 0x19, 0xdb, 0xf7, 0x67, 0xfc, 0x50, 0xf8, 0x33, 0x90, 0x95, 0xe8, 0xe0, 0xfe, 0xd4, 0xf2,
	0x3c, 0xee, 0x82, 0xa8, 0x8c, 0xdb, 0x9a, 0xac, 0x74, 0x04, 0x17, 0x83, 0xee, 0x0a, 0x6e, 0x69,
	0xb0, 0x62, 0xe8, 0x9f, 0x73, 0xaf, 0x53, 0xc5, 0xe5, 0x4d, 0x56, 0x23, 0xdb, 0xba, 0x73, 0xb7,
	0xc3, 0x40, 0x58, 0x6f, 0x6f, 0x33, 0x36, 0xf4, 0xfd, 0x59, 0xd7, 0xb6, 0xe6, 0x21, 0xef, 0xd4,
	0xe4, 0xb9, 0x8f, 0x73, 0xbb, 0xa0, 0xaa, 0x60, 0xf2, 0xab, 0x4e, 0x5d, 0x7d, 0x1b, 0xdf, 0x83,
	0x9f, 0xdd, 0xfd, 0x4f, 0x62, 0x3f, 0xe1, 0xf6, 0xee, 0xf8, 0x7c, 0xc8, 0x83, 0x85, 0x1b, 0xa2,
	0xa3, 0x45, 0x69, 0xf6, 0x81, 0x10, 0xbe, 0x90, 0x8e, 0x44, 0xde, 0xd6, 0xd9, 0xda, 0x98, 0x8b,
	0x10, 0x3d, 0xad, 0xcb, 0xf5, 0xa1, 0xef, 0x72, 0x84, 0x26, 0x72, 0xf4, 0x7f, 0x52, 0xe2, 0xcf,
	0x8e, 0x9d, 0x20, 0x04, 0x47, 0x0b, 0x0f, 0x6b, 0x1f, 0x6d, 0xee, 0x28, 0x60, 0x77, 0x9e, 0x1d,
	0xc9, 0xa5, 0xbe, 0x77, 0xe6, 0xb7, 0x5b, 0xac, 0x7c, 0xec, 0x4f, 0x1c, 0x0f, 0xfc, 0x8a, 0x5c,
	0xff, 0x80, 0x35, 0x9e, 0x5a, 0xe1, 0x78, 0x1a, 0x1f, 0x2e, 0xdf, 0x7c, 0x58, 0x42, 0x07, 0x36,
	0x9c, 0xf8, 0xf2, 0x6e, 0xc4, 0xa5, 0x6e, 0xbc, 0xc9, 0xb3, 0x3a, 0x05, 0x6d, 0xdf, 0xf7, 0xbc,
	0x8c, 0xa8, 0x81, 0xe4, 0xc4, 0x19, 0x9f, 0xa3, 0x24, 0x9f, 0x8c, 0x63, 0x81, 0x3e, 0x24, 0x3c,
	0x6b, 0xe4, 0xf8, 0x9f, 0x17, 0xaf, 0x64, 0x06, 0x61, 0xb4, 0xa4, 0x96, 0x11, 0x98, 0xca, 0x43,
	0x8c, 0x56, 0x75, 0x29, 0xa2, 0x0d, 0x8a, 0xe8, 0x16, 0xab, 0x22, 0x8a, 0xa3, 0xeb, 0x39, 0xef,
	0x34, 0x49, 0x0a, 0xd8, 0x1e, 0x09, 0x7f, 0x31, 0x07, 0x9b, 0x5a, 0x52, 0x66, 0x7c, 0x0b, 0xd8,
	0x50, 0xa0, 0x11, 0x9b, 0x8c, 0x48, 0x53, 0x5c, 0xf3, 0x64, 0x51, 0x0c, 0x5e, 0x81, 0xc0, 0x5b,
	0x8a, 0x34, 0x48, 0x06, 0x56, 0x10, 0xbc, 0xf2, 0x85, 0xad, 0x21, 0xfa, 0x74, 0x61, 0x79, 0x7b,
	0x96, 0xbf, 0xef, 0x85, 0x0a, 0x22, 0x30, 0x66, 0xdf, 0x77, 0x3c, 0x29, 0x90, 0x00, 0x15, 0x52,
	0x09, 0x52, 0xb9, 0x55, 0x82, 0x54, 0xb3, 0x13, 0x84, 0xdd, 0x36, 0x41, 0x6a, 0xe8, 0xd2, 0x0e,
	0x6b, 0x46, 0x99, 0x2e, 0x37, 0x85, 0x7c, 0x16, 0x00, 0xb4, 0x52, 0xc1, 0x9d, 0x58, 0x81, 0x5e,
	0x06, 0x1d, 0xc6, 0xef, 0x39, 0xb6, 0x41, 0x09, 0x65, 0x4e, 0x7d, 0x11, 0x4a, 0x8d, 0x7f, 0x87,
	0xac, 0x32, 0xbe, 0x06, 0xcf, 0x29, 0x5d, 0xb4, 0xe7, 0x19, 0x39, 0x03, 0xa2, 0x78, 0xfd, 0xc6,
	0xc4, 0x49, 0xc6, 0x7b, 0xed, 0xe6, 0x90, 0xad, 0x84, 0xf7, 0x66, 0xf2, 0x30, 0x7e, 0xcb, 0xb1,
	0x26, 0x85, 0xe6, 0xd9, 0x9c, 0x43, 0x8e, 0xac, 0xc4, 0xa5, 0x9e, 0xe6, 0x68, 0xc8, 0xee, 0x50,
	0xd6, 0x48, 0x61, 0x85, 0x8c, 0xd7, 0x32, 0xc2, 0x50, 0x5c, 0x0d, 0x43, 0x69, 0x29, 0x0c, 0x65,
	0x8a, 0x67, 0x0c, 0x71, 0x65, 0x09, 0xe2, 0x28, 0x32, 0x71, 0xa0, 0x18, 0xdd, 0x3c, 0x9a, 0x3a,
	0xc2, 0x3e, 0xe7, 0xd7, 0x18, 0x93, 0xe5, 0x18, 0x10, 0x37, 0x4b, 0x83, 0x70, 0x63, 0x77, 0x3e,
	0x07, 0xdd, 0x32, 0x34, 0x55, 0xe3, 0xcb, 0x3c, 0x6b, 0x52, 0x5c, 0x94, 0xdb, 0xef, 0x5c, 0xc8,
	0xab, 0x94, 0x5d, 0x5f, 0x2a, 0xdb, 0xe2, 0x72, 0xd9, 0x96, 0x56, 0xca, 0xb6, 0xfc, 0x0e, 0x61,
	0x7c, 0x97, 0x12, 0x4f, 0x97, 0x6d, 0x94, 0xc5, 0x00, 0x68, 0x77, 0x3c, 0xbd, 0xc0, 0x1c, 0x2e,
	0x00, 0x97, 0x7d, 0x15, 0x3d, 0xce, 0xa6, 0xe3, 0x59, 0x32, 0x14, 0x29, 0x44, 0xa3, 0x82, 0x7c,
	0xc0, 0x2a, 0x52, 0x3d, 0xde, 0x9e, 0xc7, 0xdb, 0xb7, 0xe2, 0xdb, 0xe5, 0xb1, 0xee, 0xdc, 0xc1,
	0xeb, 0xdf, 0x57, 0x16, 0x18, 0x87, 0xf8, 0x8c, 0xc6, 0x16, 0x65, 0xc4, 0xe4, 0x3e, 0x2b, 0x0f,
	0x79, 0x98, 0xb0, 0x68, 0x73, 0xd9, 0x22, 0x58, 0x36, 0xbe, 0xc9, 0x01, 0xc6, 0x07, 0xcf, 0x5f,
	0x71, 0x67, 0xcf, 0xff, 0x8b, 0x12, 0x3a, 0x4e, 0xd7, 0x0a, 0x65, 0xef, 0xe5, 0xe9, 0xd3, 0x60,
	0x82, 0xf1, 0xa9, 0x47, 0x9f, 0x03, 0x67, 0x1c, 0x85, 0xc6, 0xf8, 0x37, 0xab, 0x80, 0xdf, 0x91,
	0xb9, 0xab, 0x4e, 0x1b, 0x7b, 0xfa, 0x41, 0x3e, 0xb8, 0x72, 0xc2, 0x64, 0xb8, 0x75, 0x73, 0x01,
	0x0b, 0xf8, 0x78, 0xe5, 0x29, 0xeb, 0xa4, 0x44, 0xde, 0x88, 0x8e, 0x19, 0x3f, 0xe6, 0xd8, 0x26,
	0x29, 0x91, 0x86, 0x42, 0xb5, 0x05, 0x8e, 0xef, 0xa1, 0x7b, 0x0b, 0xa1, 0xbe, 0x94, 0x3a, 0xed,
	0x4b, 0x3e, 0xce, 0x26, 0x0d, 0x41, 0xd4, 0x99, 0x6d, 0x81, 0x4d, 0x3c, 0xf0, 0xdd, 0x45, 0x08,
	0xe7, 0x62, 0xb0, 0x52, 0xc0, 0xc4, 0xbc, 0x7c, 0x6c, 0x79, 0x93, 0x85, 0x35, 0xe1, 0x31, 0x58,
	0x70, 0x38, 0x98, 0x59, 0xae, 0x4b, 0xd7, 0x96, 0xe3, 0x6b, 0x5c, 0x87, 0x7b, 0x91, 0x1f, 0x15,
	0x3a, 0x6d, 0x8e, 0x05, 0xe7, 0x9e, 0xe9, 0xbc, 0xe6, 0x8a, 0x09, 0xd2, 0x85, 0xce, 0x88, 0x6c,
	0x7f, 0x28, 0xb0, 0x4d, 0x2a, 0xea, 0xa4, 0x87, 0x19, 0x59, 0x04, 0x5a, 0x07, 0xae, 0x75, 0x7d,
	0xe0, 0x59, 0xa7, 0x2e, 0xbd, 0x35, 0xc0, 0xfc, 0x3d, 0xff, 0xd2, 0x73, 0x7d, 0xcb, 0x7e, 0x21,
	0x5c, 0x95, 0x0e, 0x60, 0xa8, 0x54, 0x65, 0x72, 0x71, 0xc1, 0x45, 0x7f, 0xae, 0xbc, 0xbc, 0xc3,
	0x9a, 0x5a, 0x3a, 0x00, 0xda, 0x56, 0xae, 0x2a, 0xf9, 0xd0, 0xf2, 0xce, 0x95, 0xea, 0x12, 0xa9,
	0x26, 0x79, 0x8f, 0x9f, 0xa9, 0x87, 0x08, 0x6c, 0xe8, 0x9f, 0x0d, 0x04, 0x0f, 0xa4, 0x16, 0xe5,
	0x2d, 0x6c, 0x24, 0x09, 0xe5, 0x4a, 0xb5, 0xbd, 0xab, 0x88, 0x20, 0x2e, 0xc5, 0xe8, 0xb9, 0xbe,
	0x97, 0x20, 0x02, 0xf4, 0x39, 0xde, 0xd4, 0xbe, 0xcb, 0x5a, 0xe4, 0xca, 0x90, 0x5b, 0x88, 0x70,
	0x6d, 0x29, 0xb0, 0x75, 0xca, 0x9b, 0x89, 0x74, 0x44, 0xba, 0xd0, 0xc8, 0xee, 0x0d, 0x9a, 0x37,
	0xb3, 0xce, 0x03, 0x56, 0x7e, 0x12, 0x04, 0xb8, 0xab, 0x85, 0xbb, 0xb6, 0xd3, 0x0d, 0xc0, 0x13,
	0xd3, 0x24, 0x7a, 0xe8, 0x9f, 0x99, 0xdc, 0x12, 0xe3, 0x69, 0x67, 0x1d, 0x5d, 0xfa, 0x90, 0xd5,
	0xf7, 0x16, 0xae, 0xcb, 0x43, 0xc7, 0xc3, 0xe3, 0x1b, 0x78, 0xfc, 0x6e, 0xe2, 0x12, 0x5a, 0xc6,
	0x57, 0xea, 0x73, 0xdd, 0x3f, 0x9c, 0xf0, 0xcb, 0xe8, 0x9d, 0x48, 0x55, 0x6a, 0x2e, 0xa3, 0x52,
	0xf3, 0xab, 0x95, 0x5a, 0x58, 0xaa, 0x54, 0x6c, 0x25, 0x8c, 0xcf, 0xf4, 0x1b, 0xad, 0xb5, 0xdf,
	0xaa, 0x83, 0x07, 0x4d, 0xd1, 0x76, 0xfd, 0x20, 0xc4, 0x8f, 0x58, 0xa4, 0x7b, 0x97, 0xb5, 0xc8,
	0xf2, 0x43, 0xc7, 0xb3, 0x81, 0x75, 0x64, 0xe9, 0x1f, 0xcc, 0x2c, 0xc7, 0x55, 0x46, 0x83, 0x0e,
	0xb8, 0x35, 0xa6, 0x23, 0xe3, 0x3e, 0x6b, 0x91, 0x35, 0x74, 0x22, 0x83, 0x11, 0xfe, 0xcb, 0x1a,
	0xb4, 0xeb, 0x31, 0x00, 0x1b, 0x46, 0x68, 0x88, 0x8b, 0x91, 0x43, 0xdd, 0x94, 0xf1, 0x88, 0xd5,
	0x92, 0x1c, 0x0d, 0x84, 0x00, 0xff, 0x62, 0x65, 0xc5, 0xee, 0x00, 0x55, 0xbe, 0xb4, 0xdc, 0x05,
	0xd7, 0xee, 0x48, 0xa2, 0x54, 0xc3, 0x57, 0x15, 0x68, 0x87, 0x69, 0x4e, 0x95, 0x56, 0xc0, 0x9f,
	0x14, 0x22, 0x09, 0x9d, 0xf9, 0x15, 0x9d, 0x91, 0x8e, 0x5f, 0x73, 0x8c, 0x25, 0x52, 0x06, 0xae,
	0xc0, 0xff, 0x6d, 0xdd, 0xf2, 0xc9, 0x6f, 0x59, 0x19, 0xda, 0x08, 0xdc, 0x31, 0x4f, 0x76, 0xcb,
	0xfe, 0x0c, 0xab, 0x2c, 0x26, 0x64, 0x29, 0x31, 0x43, 0x2b, 0x5c, 0x04, 0xaa, 0xf2, 0xa0, 0x70,
	0xa4, 0xec, 0xa9, 0xe3, 0x1d, 0xf9, 0xae, 0xad, 0xcb, 0x0e, 0x85, 0xd6, 0x15, 0x0a, 0xcb, 0x4b,
	0x3b, 0x25, 0x03, 0xa8, 0xba, 0x53, 0x97, 0xa0, 0x27, 0xd5, 0x98, 0x77, 0xb0, 0xbc, 0x51, 0xc6,
	0x62, 0x86, 0xe0, 0xc1, 0x58, 0x38, 0xf3, 0x90, 0x4a, 0x2a, 0x3e, 0x8a, 0xaf, 0x0b, 0xf6, 0x82,
	0xc6, 0x77, 0x79, 0xb6, 0xbe, 0x52, 0x92, 0x00, 0x55, 0xf4, 0xd1, 0xd3, 0x1d, 0x1f, 0x0a, 0x12,
	0xdd, 0xae, 0x8c, 0xf3, 0xa5, 0x25, 0xec, 0xf4, 0xac, 0x80, 0x22, 0x73, 0x31, 0x53, 0x8d, 0x2f,
	0x9d, 0x1b, 0x71, 0x31, 0xd3, 0x0c, 0xfb, 0x78, 0x31, 0xb3, 0xa0, 0x94, 0x66, 0x0e, 0x0d, 0x0b,
	0xdb, 0xaa, 0x8e, 0x71, 0x41, 0x9e, 0x2e, 0xa7, 0x4f, 0x13, 0xc3, 0xea, 0x9d, 0x7d, 0x2f, 0x04,
	0x87, 0x2d, 0x57, 0x77, 0x10, 0x28, 0x1e, 0x08, 0x49, 0xbc, 0x8c, 0xd8, 0x50, 0xc9, 0xfc, 0x31,
	0x0f, 0x02, 0x85, 0x00, 0xe9, 0xec, 0x59, 0xaa, 0xed, 0x42, 0xb3, 0x51, 0x74, 0xc8, 0xa3, 0x66,
	0x58, 0x6f, 0xea, 0x0a, 0x6e, 0x45, 0xf3, 0xd5, 0x32, 0x9c, 0x2d, 0x04, 0xef, 0x97, 0x1c, 0x6b,
	0xa4, 0xa6, 0x87, 0xb8, 0x5c, 0x7b, 0x3a, 0xe9, 0x68, 0x26, 0xcb, 0x13, 0xa9, 0xe1, 0xe6, 0x9e,
	0xaa, 0x42, 0xbc, 0xea, 0x4a, 0x46, 0x97, 0x0b, 0x05, 0x1a, 0x6d, 0x19, 0x28, 0xc4, 0x92, 0x49,
	0x95, 0x18, 0xae, 0x00, 0x81, 0xab, 0x68, 0xb8, 0x42, 0x2d, 0xf0, 0x2e, 0x2a, 0x2d, 0x15, 0x02,
	0x8f, 0x12, 0x8f, 0x2b, 0x94, 0x36, 0x58, 0xa9, 0x1f, 0x1c, 0xfb, 0xe3, 0xf3, 0xf8, 0x19, 0xca,
	0x98, 0x8e, 0x6a, 0x6f, 0x9d, 0x8e, 0x1e, 0xb1, 0x7a, 0x8a, 0x2d, 0xb5, 0xad, 0xb9, 0x15, 0x5b,
	0x75, 0x89, 0xf0, 0x99, 0x25, 0xce, 0x55, 0x8d, 0xed, 0xb2, 0x66, 0x9a, 0x30, 0x25, 0xc7, 0x8c,
	0x9c, 0xd0, 0xa5, 0x7e, 0x87, 0x9c, 0xf3, 0x54, 0x2f, 0x6b, 0xfc, 0x1c, 0x8d, 0xf8, 0xcf, 0x17,
	0xd0, 0x60, 0x67, 0x8e, 0xf8, 0xf5, 0x95, 0x1f, 0x66, 0x62, 0xae, 0x2d, 0x64, 0x70, 0xed, 0xda,
	0x2a, 0xd7, 0x16, 0x97, 0xb8, 0xb6, 0x94, 0xee, 0x8a, 0xca, 0x19, 0x2f, 0x79, 0x25, 0x73, 0x18,
	0xaf, 0x26, 0x1a, 0xf9, 0x44, 0xa7, 0xc2, 0xa8, 0x0b, 0x49, 0x35, 0x12, 0xb5, 0xcc, 0xde, 0xa4,
	0x9e, 0xd1, 0x88, 0x34, 0x32, 0xda, 0x8b, 0x26, 0xca, 0x3a, 0x6c, 0x1d, 0xfb, 0xe0, 0x9e, 0x33,
	0x71, 0x42, 0xcb, 0x45, 0x4c, 0x5a, 0x2b, 0x33, 0xc7, 0x3a, 0x9d, 0x4f, 0x0c, 0x17, 0x1b, 0xe4,
	0xf3, 0x22, 0xa2, 0xd1, 0x36, 0x7c, 0x37, 0x8c, 0x37, 0x45, 0xfc, 0xcd, 0x40, 0x83, 0x9d, 0xf1,
	0xb6, 0x68, 0xea, 0x95, 0x80, 0x37, 0x6e, 0xf5, 0xab, 0xc1, 0xfb, 0x1c, 0x36, 0x76, 0xb3, 0x87,
	0x8d, 0xb7, 0xf4, 0x18, 0xd0, 0x36, 0xe3, 0xb0, 0x5a, 0xa5, 0xc1, 0x27, 0x9a, 0x37, 0x50, 0xc6,
	0x62, 0x99, 0x8e, 0x57, 0x2d, 0xa3, 0xf1, 0xaa, 0x67, 0x35, 0x5e, 0x8d, 0x8c, 0xee, 0xa8, 0x99,
	0xd5, 0x1d, 0xad, 0x2f, 0x65, 0xd8, 0x06, 0xde, 0x90, 0x68, 0x4a, 0xda, 0xb7, 0x6d, 0x4a, 0x36,
	0x33, 0x9b, 0x92, 0xad, 0xb7, 0x36, 0x25, 0xd2, 0x1a, 0xe5, 0x9b, 0xfc, 0xec, 0x6c, 0xa3, 0x8e,
	0xff, 0x2b, 0x86, 0x34, 0x2f, 0x04, 0xea, 0xb8, 0x73, 0x33, 0xe4, 0xea, 0xe7, 0x8c, 0xbb, 0x68,
	0xf5, 0xc3, 0xe8, 0x55, 0xa2, 0x63, 0x9d, 0x9b, 0x8f, 0x41, 0x6d, 0xf4, 0xec, 0xd7, 0xdd, 0x71,
	0xe8, 0x00, 0x2e, 0xf7, 0xf4, 0x0f, 0x92, 0x25, 0x80, 0x44, 0xc2, 0xf7, 0x0f, 0xc5, 0xd4, 0x55,
	0xec, 0x55, 0xf6, 0x7d, 0x9b, 0x77, 0xfe, 0x49, 0xbb, 0x92, 0x3f, 0xb0, 0xfc, 0x0b, 0xa9, 0xa3,
	0xca, 0xca, 0x27, 0xe0, 0x14, 0x9c, 0x35, 0x4e, 0xd9, 0xba, 0xec, 0x05, 0xbf, 0x30, 0xb9, 0x67,
	0x77, 0x6d, 0x5b, 0xa6, 0x5f, 0xfc, 0x6a, 0x39, 0xb6, 0x66, 0x92, 0x91, 0x0c, 0x9d, 0x63, 0xeb,
	0x17, 0x3f, 0x56, 0x59, 0xa0, 0x79, 0x4a, 0xa6, 0x20, 0x26, 0x69, 0x41, 0x7e, 0x05, 0xdc, 0x52,
	0xe9, 0xb9, 0x97, 0x7f, 0x5c, 0xf8, 0x23, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x96, 0xa9, 0xd9, 0x29,
	0x16, 0x00, 0x00,
}
