// Code generated by protoc-gen-go.
// source: serverModel.proto
// DO NOT EDIT!

package bbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from base.proto

// Ignoring public import of TerminalInfo from base.proto

// Ignoring public import of User from base.proto

// Ignoring public import of EProtoId from base.proto

// Ignoring public import of ZjhRoom from zhajinhua.proto

// Ignoring public import of ZjhBet from zhajinhua.proto

// Ignoring public import of ZjhLottery from zhajinhua.proto

// Ignoring public import of BroadcastBet from zhajinhua.proto

// Ignoring public import of ZjhPai from zhajinhua.proto

// Ignoring public import of Pai from zhajinhua.proto

// Ignoring public import of ZjhQueryNoSeatUser from zhajinhua.proto

// Ignoring public import of ZjhReqSeat from zhajinhua.proto

// Ignoring public import of ZjhMsg from zhajinhua.proto

// Ignoring public import of ZjhBroadcastBeginBet from zhajinhua.proto

// Ignoring public import of EPaiType from zhajinhua.proto

// Ignoring public import of ThRoom from thPoker.proto

// Ignoring public import of THRoomAddUserBroadcast from thPoker.proto

// Ignoring public import of THPoker from thPoker.proto

// Ignoring public import of THBet from thPoker.proto

// Ignoring public import of THBetBegin from thPoker.proto

// Ignoring public import of THBetBroadcast from thPoker.proto

// Ignoring public import of THUser from thPoker.proto

// Ignoring public import of THLottery from thPoker.proto

// Ignoring public import of ETHType from thPoker.proto

// Ignoring public import of ETHAction from thPoker.proto

// 押注的记录,针对每轮扎金花,只有一次押注记录
type TBetRecord struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Betzone          []int32 `protobuf:"varint,2,rep,name=betzone" json:"betzone,omitempty"`
	ZjhRoundNumber   *string `protobuf:"bytes,3,opt,name=ZjhRoundNumber" json:"ZjhRoundNumber,omitempty"`
	WinAmount        *int32  `protobuf:"varint,4,opt,name=winAmount" json:"winAmount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TBetRecord) Reset()                    { *m = TBetRecord{} }
func (m *TBetRecord) String() string            { return proto.CompactTextString(m) }
func (*TBetRecord) ProtoMessage()               {}
func (*TBetRecord) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *TBetRecord) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *TBetRecord) GetBetzone() []int32 {
	if m != nil {
		return m.Betzone
	}
	return nil
}

func (m *TBetRecord) GetZjhRoundNumber() string {
	if m != nil && m.ZjhRoundNumber != nil {
		return *m.ZjhRoundNumber
	}
	return ""
}

func (m *TBetRecord) GetWinAmount() int32 {
	if m != nil && m.WinAmount != nil {
		return *m.WinAmount
	}
	return 0
}

// 每一轮扎金花的数据
type TZjhRound struct {
	Id               *uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BeginTime        *int64    `protobuf:"varint,2,opt,name=beginTime" json:"beginTime,omitempty"`
	BetEndTime       *int64    `protobuf:"varint,3,opt,name=betEndTime" json:"betEndTime,omitempty"`
	LotteryTime      *int64    `protobuf:"varint,4,opt,name=lotteryTime" json:"lotteryTime,omitempty"`
	EndTime          *int64    `protobuf:"varint,5,opt,name=endTime" json:"endTime,omitempty"`
	ZoneAmount       []int32   `protobuf:"varint,6,rep,name=zoneAmount" json:"zoneAmount,omitempty"`
	ZoneWinAmount    []int32   `protobuf:"varint,7,rep,name=zoneWinAmount" json:"zoneWinAmount,omitempty"`
	BankerUserId     *uint32   `protobuf:"varint,8,opt,name=BankerUserId" json:"BankerUserId,omitempty"`
	ZjhPaiList       []*ZjhPai `protobuf:"bytes,9,rep,name=ZjhPaiList" json:"ZjhPaiList,omitempty"`
	Number           *string   `protobuf:"bytes,10,opt,name=Number" json:"Number,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *TZjhRound) Reset()                    { *m = TZjhRound{} }
func (m *TZjhRound) String() string            { return proto.CompactTextString(m) }
func (*TZjhRound) ProtoMessage()               {}
func (*TZjhRound) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *TZjhRound) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TZjhRound) GetBeginTime() int64 {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return 0
}

func (m *TZjhRound) GetBetEndTime() int64 {
	if m != nil && m.BetEndTime != nil {
		return *m.BetEndTime
	}
	return 0
}

func (m *TZjhRound) GetLotteryTime() int64 {
	if m != nil && m.LotteryTime != nil {
		return *m.LotteryTime
	}
	return 0
}

func (m *TZjhRound) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *TZjhRound) GetZoneAmount() []int32 {
	if m != nil {
		return m.ZoneAmount
	}
	return nil
}

func (m *TZjhRound) GetZoneWinAmount() []int32 {
	if m != nil {
		return m.ZoneWinAmount
	}
	return nil
}

func (m *TZjhRound) GetBankerUserId() uint32 {
	if m != nil && m.BankerUserId != nil {
		return *m.BankerUserId
	}
	return 0
}

func (m *TZjhRound) GetZjhPaiList() []*ZjhPai {
	if m != nil {
		return m.ZjhPaiList
	}
	return nil
}

func (m *TZjhRound) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

type TNotice struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	NoticeType       *int32  `protobuf:"varint,2,opt,name=noticeType" json:"noticeType,omitempty"`
	NoticeTitle      *string `protobuf:"bytes,3,opt,name=noticeTitle" json:"noticeTitle,omitempty"`
	NoticeContent    *string `protobuf:"bytes,4,opt,name=noticeContent" json:"noticeContent,omitempty"`
	NoticeMemo       *string `protobuf:"bytes,5,opt,name=noticeMemo" json:"noticeMemo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TNotice) Reset()                    { *m = TNotice{} }
func (m *TNotice) String() string            { return proto.CompactTextString(m) }
func (*TNotice) ProtoMessage()               {}
func (*TNotice) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *TNotice) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TNotice) GetNoticeType() int32 {
	if m != nil && m.NoticeType != nil {
		return *m.NoticeType
	}
	return 0
}

func (m *TNotice) GetNoticeTitle() string {
	if m != nil && m.NoticeTitle != nil {
		return *m.NoticeTitle
	}
	return ""
}

func (m *TNotice) GetNoticeContent() string {
	if m != nil && m.NoticeContent != nil {
		return *m.NoticeContent
	}
	return ""
}

func (m *TNotice) GetNoticeMemo() string {
	if m != nil && m.NoticeMemo != nil {
		return *m.NoticeMemo
	}
	return ""
}

// 后台保存数据使用的mode,一般不传递给客户端,这个实体一般是保存在redis当中
// 当用程序崩溃的时候,可以用来恢复用户数据
type ThServerUser struct {
	Seat               *int32  `protobuf:"varint,1,opt,name=Seat" json:"Seat,omitempty"`
	Status             *int32  `protobuf:"varint,2,opt,name=Status" json:"Status,omitempty"`
	BreakStatus        *int32  `protobuf:"varint,3,opt,name=BreakStatus" json:"BreakStatus,omitempty"`
	HandCards          []*Pai  `protobuf:"bytes,4,rep,name=HandCards" json:"HandCards,omitempty"`
	WaiTime            *string `protobuf:"bytes,5,opt,name=waiTime" json:"waiTime,omitempty"`
	WaitUUID           *string `protobuf:"bytes,6,opt,name=waitUUID" json:"waitUUID,omitempty"`
	DeskId             *int32  `protobuf:"varint,7,opt,name=deskId" json:"deskId,omitempty"`
	TotalBet           *int64  `protobuf:"varint,8,opt,name=TotalBet" json:"TotalBet,omitempty"`
	TotalBet4CalcAllin *int64  `protobuf:"varint,9,opt,name=TotalBet4calcAllin" json:"TotalBet4calcAllin,omitempty"`
	WinAmount          *int64  `protobuf:"varint,10,opt,name=winAmount" json:"winAmount,omitempty"`
	TurnCoin           *int64  `protobuf:"varint,11,opt,name=TurnCoin" json:"TurnCoin,omitempty"`
	HandCoin           *int64  `protobuf:"varint,12,opt,name=HandCoin" json:"HandCoin,omitempty"`
	RoomCoin           *int64  `protobuf:"varint,13,opt,name=RoomCoin" json:"RoomCoin,omitempty"`
	WinAmountDetail    []int64 `protobuf:"varint,14,rep,name=winAmountDetail" json:"winAmountDetail,omitempty"`
	UserId             *uint32 `protobuf:"varint,15,opt,name=UserId" json:"UserId,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *ThServerUser) Reset()                    { *m = ThServerUser{} }
func (m *ThServerUser) String() string            { return proto.CompactTextString(m) }
func (*ThServerUser) ProtoMessage()               {}
func (*ThServerUser) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *ThServerUser) GetSeat() int32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *ThServerUser) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ThServerUser) GetBreakStatus() int32 {
	if m != nil && m.BreakStatus != nil {
		return *m.BreakStatus
	}
	return 0
}

func (m *ThServerUser) GetHandCards() []*Pai {
	if m != nil {
		return m.HandCards
	}
	return nil
}

func (m *ThServerUser) GetWaiTime() string {
	if m != nil && m.WaiTime != nil {
		return *m.WaiTime
	}
	return ""
}

func (m *ThServerUser) GetWaitUUID() string {
	if m != nil && m.WaitUUID != nil {
		return *m.WaitUUID
	}
	return ""
}

func (m *ThServerUser) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *ThServerUser) GetTotalBet() int64 {
	if m != nil && m.TotalBet != nil {
		return *m.TotalBet
	}
	return 0
}

func (m *ThServerUser) GetTotalBet4CalcAllin() int64 {
	if m != nil && m.TotalBet4CalcAllin != nil {
		return *m.TotalBet4CalcAllin
	}
	return 0
}

func (m *ThServerUser) GetWinAmount() int64 {
	if m != nil && m.WinAmount != nil {
		return *m.WinAmount
	}
	return 0
}

func (m *ThServerUser) GetTurnCoin() int64 {
	if m != nil && m.TurnCoin != nil {
		return *m.TurnCoin
	}
	return 0
}

func (m *ThServerUser) GetHandCoin() int64 {
	if m != nil && m.HandCoin != nil {
		return *m.HandCoin
	}
	return 0
}

func (m *ThServerUser) GetRoomCoin() int64 {
	if m != nil && m.RoomCoin != nil {
		return *m.RoomCoin
	}
	return 0
}

func (m *ThServerUser) GetWinAmountDetail() []int64 {
	if m != nil {
		return m.WinAmountDetail
	}
	return nil
}

func (m *ThServerUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type ThServerAllInJackpot struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	Jackpopt         *int64  `protobuf:"varint,2,opt,name=Jackpopt" json:"Jackpopt,omitempty"`
	ThroundCount     *int32  `protobuf:"varint,3,opt,name=ThroundCount" json:"ThroundCount,omitempty"`
	AllInAmount      *int64  `protobuf:"varint,4,opt,name=AllInAmount" json:"AllInAmount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ThServerAllInJackpot) Reset()                    { *m = ThServerAllInJackpot{} }
func (m *ThServerAllInJackpot) String() string            { return proto.CompactTextString(m) }
func (*ThServerAllInJackpot) ProtoMessage()               {}
func (*ThServerAllInJackpot) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *ThServerAllInJackpot) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ThServerAllInJackpot) GetJackpopt() int64 {
	if m != nil && m.Jackpopt != nil {
		return *m.Jackpopt
	}
	return 0
}

func (m *ThServerAllInJackpot) GetThroundCount() int32 {
	if m != nil && m.ThroundCount != nil {
		return *m.ThroundCount
	}
	return 0
}

func (m *ThServerAllInJackpot) GetAllInAmount() int64 {
	if m != nil && m.AllInAmount != nil {
		return *m.AllInAmount
	}
	return 0
}

// 服务端保存桌子的状态
type ThServerDesk struct {
	Id                   *int32                `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	DeskOwner            *uint32               `protobuf:"varint,2,opt,name=deskOwner" json:"deskOwner,omitempty"`
	RoomKey              *string               `protobuf:"bytes,3,opt,name=RoomKey" json:"RoomKey,omitempty"`
	DeskType             *int32                `protobuf:"varint,4,opt,name=DeskType" json:"DeskType,omitempty"`
	InitRoomCoin         *int32                `protobuf:"varint,5,opt,name=InitRoomCoin" json:"InitRoomCoin,omitempty"`
	JuCount              *int32                `protobuf:"varint,6,opt,name=JuCount" json:"JuCount,omitempty"`
	SmallBlindCoin       *int32                `protobuf:"varint,7,opt,name=SmallBlindCoin" json:"SmallBlindCoin,omitempty"`
	BigBlindCoin         *int32                `protobuf:"varint,8,opt,name=BigBlindCoin" json:"BigBlindCoin,omitempty"`
	Dealer               *uint32               `protobuf:"varint,9,opt,name=Dealer" json:"Dealer,omitempty"`
	BigBlind             *uint32               `protobuf:"varint,10,opt,name=BigBlind" json:"BigBlind,omitempty"`
	SmallBlind           *uint32               `protobuf:"varint,11,opt,name=SmallBlind" json:"SmallBlind,omitempty"`
	RaiseUserId          *uint32               `protobuf:"varint,12,opt,name=RaiseUserId" json:"RaiseUserId,omitempty"`
	NewRoundFirstBetUser *uint32               `protobuf:"varint,13,opt,name=NewRoundFirstBetUser" json:"NewRoundFirstBetUser,omitempty"`
	BetUserNow           *uint32               `protobuf:"varint,14,opt,name=BetUserNow" json:"BetUserNow,omitempty"`
	GameNumber           *ThServerUser         `protobuf:"bytes,15,opt,name=GameNumber" json:"GameNumber,omitempty"`
	Users                []int32               `protobuf:"varint,16,rep,name=Users" json:"Users,omitempty"`
	PublicPai            []*Pai                `protobuf:"bytes,17,rep,name=PublicPai" json:"PublicPai,omitempty"`
	UserCount            *int32                `protobuf:"varint,18,opt,name=UserCount" json:"UserCount,omitempty"`
	UserCountOnline      *int32                `protobuf:"varint,19,opt,name=UserCountOnline" json:"UserCountOnline,omitempty"`
	Status               *int32                `protobuf:"varint,20,opt,name=Status" json:"Status,omitempty"`
	BetAmountNow         *int64                `protobuf:"varint,21,opt,name=BetAmountNow" json:"BetAmountNow,omitempty"`
	RoundCount           *int32                `protobuf:"varint,22,opt,name=RoundCount" json:"RoundCount,omitempty"`
	Jackpot              *int64                `protobuf:"varint,23,opt,name=Jackpot" json:"Jackpot,omitempty"`
	EdgeJackpot          *int64                `protobuf:"varint,24,opt,name=edgeJackpot" json:"edgeJackpot,omitempty"`
	MinRaise             *int64                `protobuf:"varint,25,opt,name=MinRaise" json:"MinRaise,omitempty"`
	AllInJackpot         *ThServerAllInJackpot `protobuf:"bytes,26,opt,name=AllInJackpot" json:"AllInJackpot,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *ThServerDesk) Reset()                    { *m = ThServerDesk{} }
func (m *ThServerDesk) String() string            { return proto.CompactTextString(m) }
func (*ThServerDesk) ProtoMessage()               {}
func (*ThServerDesk) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *ThServerDesk) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ThServerDesk) GetDeskOwner() uint32 {
	if m != nil && m.DeskOwner != nil {
		return *m.DeskOwner
	}
	return 0
}

func (m *ThServerDesk) GetRoomKey() string {
	if m != nil && m.RoomKey != nil {
		return *m.RoomKey
	}
	return ""
}

func (m *ThServerDesk) GetDeskType() int32 {
	if m != nil && m.DeskType != nil {
		return *m.DeskType
	}
	return 0
}

func (m *ThServerDesk) GetInitRoomCoin() int32 {
	if m != nil && m.InitRoomCoin != nil {
		return *m.InitRoomCoin
	}
	return 0
}

func (m *ThServerDesk) GetJuCount() int32 {
	if m != nil && m.JuCount != nil {
		return *m.JuCount
	}
	return 0
}

func (m *ThServerDesk) GetSmallBlindCoin() int32 {
	if m != nil && m.SmallBlindCoin != nil {
		return *m.SmallBlindCoin
	}
	return 0
}

func (m *ThServerDesk) GetBigBlindCoin() int32 {
	if m != nil && m.BigBlindCoin != nil {
		return *m.BigBlindCoin
	}
	return 0
}

func (m *ThServerDesk) GetDealer() uint32 {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return 0
}

func (m *ThServerDesk) GetBigBlind() uint32 {
	if m != nil && m.BigBlind != nil {
		return *m.BigBlind
	}
	return 0
}

func (m *ThServerDesk) GetSmallBlind() uint32 {
	if m != nil && m.SmallBlind != nil {
		return *m.SmallBlind
	}
	return 0
}

func (m *ThServerDesk) GetRaiseUserId() uint32 {
	if m != nil && m.RaiseUserId != nil {
		return *m.RaiseUserId
	}
	return 0
}

func (m *ThServerDesk) GetNewRoundFirstBetUser() uint32 {
	if m != nil && m.NewRoundFirstBetUser != nil {
		return *m.NewRoundFirstBetUser
	}
	return 0
}

func (m *ThServerDesk) GetBetUserNow() uint32 {
	if m != nil && m.BetUserNow != nil {
		return *m.BetUserNow
	}
	return 0
}

func (m *ThServerDesk) GetGameNumber() *ThServerUser {
	if m != nil {
		return m.GameNumber
	}
	return nil
}

func (m *ThServerDesk) GetUsers() []int32 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ThServerDesk) GetPublicPai() []*Pai {
	if m != nil {
		return m.PublicPai
	}
	return nil
}

func (m *ThServerDesk) GetUserCount() int32 {
	if m != nil && m.UserCount != nil {
		return *m.UserCount
	}
	return 0
}

func (m *ThServerDesk) GetUserCountOnline() int32 {
	if m != nil && m.UserCountOnline != nil {
		return *m.UserCountOnline
	}
	return 0
}

func (m *ThServerDesk) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ThServerDesk) GetBetAmountNow() int64 {
	if m != nil && m.BetAmountNow != nil {
		return *m.BetAmountNow
	}
	return 0
}

func (m *ThServerDesk) GetRoundCount() int32 {
	if m != nil && m.RoundCount != nil {
		return *m.RoundCount
	}
	return 0
}

func (m *ThServerDesk) GetJackpot() int64 {
	if m != nil && m.Jackpot != nil {
		return *m.Jackpot
	}
	return 0
}

func (m *ThServerDesk) GetEdgeJackpot() int64 {
	if m != nil && m.EdgeJackpot != nil {
		return *m.EdgeJackpot
	}
	return 0
}

func (m *ThServerDesk) GetMinRaise() int64 {
	if m != nil && m.MinRaise != nil {
		return *m.MinRaise
	}
	return 0
}

func (m *ThServerDesk) GetAllInJackpot() *ThServerAllInJackpot {
	if m != nil {
		return m.AllInJackpot
	}
	return nil
}

func init() {
	proto.RegisterType((*TBetRecord)(nil), "bbproto.TBetRecord")
	proto.RegisterType((*TZjhRound)(nil), "bbproto.TZjhRound")
	proto.RegisterType((*TNotice)(nil), "bbproto.TNotice")
	proto.RegisterType((*ThServerUser)(nil), "bbproto.ThServerUser")
	proto.RegisterType((*ThServerAllInJackpot)(nil), "bbproto.ThServerAllInJackpot")
	proto.RegisterType((*ThServerDesk)(nil), "bbproto.ThServerDesk")
}

var fileDescriptor4 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x54, 0x5d, 0x53, 0x22, 0x47,
	0x14, 0x0d, 0x0c, 0x88, 0xd3, 0x80, 0xe8, 0x88, 0x3a, 0xa1, 0x92, 0x8a, 0x45, 0x5e, 0xcc, 0x8b,
	0x0f, 0x26, 0x7f, 0x40, 0x20, 0x1f, 0x98, 0x88, 0x14, 0x60, 0x65, 0x6b, 0xdf, 0x1a, 0xa6, 0x4b,
	0x5a, 0x86, 0x6e, 0x6a, 0xa6, 0x67, 0x29, 0xfd, 0x5f, 0xfb, 0x3f, 0xf6, 0x79, 0x7f, 0xcd, 0xde,
	0x7b, 0xa7, 0x7b, 0xc0, 0xdd, 0x7d, 0x52, 0x4e, 0xdf, 0xbe, 0xf7, 0x9c, 0x73, 0x4f, 0x0f, 0x3b,
	0x49, 0x45, 0xf2, 0x41, 0x24, 0xf7, 0x3a, 0x12, 0xf1, 0xf5, 0x26, 0xd1, 0x46, 0x07, 0xb5, 0xf9,
	0x9c, 0xfe, 0xe9, 0xb0, 0x39, 0x4f, 0x45, 0x0e, 0x76, 0x5a, 0xaf, 0x4b, 0xfe, 0x2c, 0xd5, 0x32,
	0xe3, 0x16, 0x68, 0x9a, 0xe5, 0x58, 0xaf, 0x44, 0x92, 0xff, 0xec, 0xbe, 0x63, 0x6c, 0xd6, 0x13,
	0x66, 0x22, 0x16, 0x3a, 0x89, 0x82, 0x23, 0x76, 0x90, 0x41, 0xe3, 0x61, 0x14, 0x96, 0x2e, 0x4b,
	0x57, 0xcd, 0xa0, 0xc5, 0x6a, 0x73, 0x61, 0x5e, 0xb5, 0x12, 0x61, 0xf9, 0xd2, 0xbb, 0xaa, 0x06,
	0xe7, 0xec, 0xe8, 0xfd, 0xf3, 0x72, 0xa2, 0x33, 0x15, 0x8d, 0xb2, 0xf5, 0x5c, 0x24, 0xa1, 0x07,
	0x85, 0x7e, 0x70, 0xc2, 0xfc, 0xad, 0x54, 0xb7, 0x6b, 0x38, 0x30, 0x61, 0x05, 0xa0, 0x6a, 0xf7,
	0x73, 0x89, 0xf9, 0x33, 0x57, 0x1c, 0x30, 0x56, 0x96, 0xae, 0x2b, 0x14, 0xcf, 0xc5, 0x93, 0x54,
	0x33, 0xb9, 0xc6, 0xbe, 0xa5, 0x2b, 0x2f, 0x80, 0x73, 0x18, 0xf4, 0xa7, 0x8a, 0x08, 0xf3, 0x08,
	0x3b, 0x65, 0xf5, 0x58, 0x1b, 0x23, 0x92, 0x17, 0x02, 0x2b, 0x04, 0x02, 0x23, 0x61, 0xab, 0xaa,
	0xee, 0x26, 0xf2, 0xb3, 0xa3, 0x0f, 0x88, 0xe5, 0x19, 0x6b, 0x22, 0xf6, 0x7f, 0xc1, 0xa8, 0x46,
	0x70, 0x9b, 0x35, 0x7a, 0x5c, 0x81, 0xf6, 0xc7, 0x5c, 0xe3, 0x21, 0xb1, 0xf9, 0x95, 0x31, 0x60,
	0x39, 0xe6, 0xf2, 0x3f, 0x99, 0x9a, 0xd0, 0x87, 0xca, 0xfa, 0x4d, 0xeb, 0xda, 0x7a, 0x79, 0x9d,
	0x1f, 0xa1, 0x31, 0x56, 0x2f, 0x43, 0xbd, 0x5d, 0xc9, 0x6a, 0xb3, 0x91, 0x36, 0x72, 0x21, 0xf6,
	0x94, 0x55, 0x91, 0x8c, 0x22, 0x74, 0xf6, 0xb2, 0xc9, 0xa5, 0x55, 0x51, 0x86, 0xc5, 0xa4, 0x89,
	0x85, 0xf5, 0x0b, 0x18, 0xe6, 0x60, 0x5f, 0x2b, 0x23, 0xac, 0x67, 0xfe, 0xee, 0xfe, 0xbd, 0x58,
	0x6b, 0x12, 0xe8, 0x77, 0x3f, 0x96, 0x59, 0x63, 0xb6, 0x9c, 0xd2, 0xba, 0x91, 0x78, 0xd0, 0x60,
	0x95, 0xa9, 0xe0, 0xc6, 0x8e, 0x04, 0x66, 0x53, 0xc3, 0x4d, 0x96, 0xee, 0xc6, 0xf5, 0x12, 0xc1,
	0x57, 0x16, 0xf4, 0x08, 0xfc, 0x85, 0xf9, 0xff, 0x70, 0x15, 0xf5, 0x79, 0x12, 0xa5, 0x30, 0x0a,
	0x25, 0x36, 0x0a, 0x89, 0xa8, 0x0f, 0x6c, 0xdd, 0x72, 0x59, 0xd8, 0xea, 0x07, 0xc7, 0xec, 0x10,
	0x00, 0xf3, 0xf8, 0x38, 0x1c, 0x80, 0xa9, 0x88, 0xc0, 0xa0, 0x48, 0xa4, 0x2b, 0xf0, 0xad, 0x46,
	0x3d, 0xa1, 0x62, 0xa6, 0x0d, 0x8f, 0x21, 0x3d, 0xe4, 0xa4, 0x17, 0x74, 0x58, 0xe0, 0x90, 0x3f,
	0x16, 0x3c, 0x5e, 0xdc, 0xc6, 0xb1, 0x54, 0xe0, 0x28, 0x9e, 0xbd, 0x09, 0x08, 0x23, 0x08, 0x1b,
	0x64, 0x89, 0xea, 0x6b, 0x28, 0xaa, 0x3b, 0x84, 0x68, 0x22, 0xd2, 0x70, 0xc8, 0x44, 0xeb, 0x35,
	0x21, 0x4d, 0x42, 0x2e, 0x58, 0xab, 0x68, 0x34, 0x10, 0x86, 0xcb, 0x38, 0x3c, 0x02, 0x41, 0x1e,
	0xf2, 0xb3, 0x7b, 0x6d, 0xe1, 0x5e, 0xbb, 0x0b, 0xd6, 0x76, 0xb6, 0x01, 0x91, 0xa1, 0xba, 0xe3,
	0x8b, 0xd5, 0x46, 0x9b, 0xbd, 0xba, 0x3c, 0x8d, 0x30, 0x22, 0x3f, 0xda, 0x18, 0x1b, 0xc6, 0x36,
	0x1a, 0x9e, 0x60, 0x6c, 0xfb, 0x44, 0xd7, 0x73, 0xc6, 0x52, 0x9f, 0xbd, 0x90, 0x7b, 0xdd, 0x4f,
	0x95, 0xdd, 0x72, 0x06, 0xe0, 0x0e, 0xa6, 0x61, 0xe8, 0xd2, 0x00, 0x9a, 0xd1, 0xb1, 0x87, 0xad,
	0x82, 0xdc, 0x94, 0xdd, 0x83, 0x42, 0x3d, 0xff, 0x8a, 0x17, 0x1b, 0x04, 0x98, 0x8e, 0xf7, 0x28,
	0x2f, 0xf4, 0x6e, 0x70, 0xfa, 0x50, 0x49, 0x53, 0xc8, 0xae, 0x12, 0x0a, 0x17, 0xef, 0xb2, 0xbe,
	0xcd, 0x78, 0x29, 0x7f, 0x89, 0xd3, 0x35, 0x8f, 0xe3, 0x1e, 0x78, 0x9c, 0x3b, 0x56, 0x73, 0xd7,
	0x7b, 0xf2, 0x69, 0x87, 0x1e, 0xba, 0x94, 0x0c, 0x04, 0x8f, 0x81, 0x87, 0xef, 0x44, 0xbb, 0x2a,
	0xda, 0x46, 0x13, 0xa3, 0xb7, 0xeb, 0x47, 0xfb, 0x68, 0xa2, 0xe4, 0x09, 0x97, 0xa9, 0xb0, 0x7e,
	0x35, 0x08, 0xfc, 0x89, 0xb5, 0x47, 0x62, 0x4b, 0xaf, 0xfa, 0x2f, 0x99, 0xa4, 0x06, 0xb6, 0x8d,
	0xe7, 0xb4, 0x1e, 0x6a, 0x63, 0x81, 0x91, 0xde, 0xc2, 0x66, 0x10, 0xfb, 0x8d, 0xb1, 0xbf, 0xf9,
	0x5a, 0xd8, 0x07, 0x84, 0xdb, 0xa9, 0xdf, 0x9c, 0x15, 0xf1, 0x7b, 0x93, 0xed, 0x26, 0xab, 0xe2,
	0xdf, 0x34, 0x3c, 0xa6, 0x17, 0x0b, 0xb9, 0x1d, 0x67, 0xf3, 0x58, 0x2e, 0x20, 0xa3, 0xe1, 0xc9,
	0x77, 0x72, 0x0b, 0x16, 0x63, 0x7d, 0x6e, 0x4c, 0x40, 0x52, 0x21, 0x20, 0x05, 0xf4, 0xa0, 0x40,
	0x8d, 0x08, 0x4f, 0xbf, 0x7a, 0x29, 0xed, 0xc2, 0x29, 0x61, 0xf2, 0x75, 0x22, 0xd9, 0x33, 0xf7,
	0x3d, 0x99, 0xec, 0x56, 0x7f, 0x5e, 0x98, 0x9f, 0xa7, 0x27, 0xbc, 0x70, 0x9f, 0x26, 0x11, 0x3d,
	0x09, 0x07, 0x86, 0x2e, 0xab, 0xf7, 0x52, 0x91, 0x61, 0xe1, 0x8f, 0x84, 0xfc, 0xce, 0x1a, 0xfb,
	0xd1, 0x0b, 0x3b, 0x24, 0xfd, 0xe7, 0x6f, 0xa4, 0xef, 0x17, 0x8d, 0x7f, 0x18, 0x97, 0xc6, 0xe5,
	0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0x4b, 0x99, 0xb8, 0xe0, 0x05, 0x00, 0x00,
}
