// Code generated by protoc-gen-go.
// source: zhajinhua.proto
// DO NOT EDIT!

package bbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from base.proto

// Ignoring public import of TerminalInfo from base.proto

// Ignoring public import of EUnitType from base.proto

// Ignoring public import of EUnitRace from base.proto

// Ignoring public import of EUnitProtoId from base.proto

// Ignoring public import of User from user.proto

// 进入扎金花的房间:押注中(剩余time）、开奖中（剩余time）、jackpot奖池金额、balance、庄家信息、在座玩家
type ZjhRoom struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ReqType          *int32       `protobuf:"varint,2,opt,name=reqType" json:"reqType,omitempty"`
	Jackpot          *int32       `protobuf:"varint,3,opt,name=jackpot" json:"jackpot,omitempty"`
	Banker           *User        `protobuf:"bytes,4,opt,name=banker" json:"banker,omitempty"`
	Me               *User        `protobuf:"bytes,5,opt,name=me" json:"me,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ZjhRoom) Reset()                    { *m = ZjhRoom{} }
func (m *ZjhRoom) String() string            { return proto.CompactTextString(m) }
func (*ZjhRoom) ProtoMessage()               {}
func (*ZjhRoom) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *ZjhRoom) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ZjhRoom) GetReqType() int32 {
	if m != nil && m.ReqType != nil {
		return *m.ReqType
	}
	return 0
}

func (m *ZjhRoom) GetJackpot() int32 {
	if m != nil && m.Jackpot != nil {
		return *m.Jackpot
	}
	return 0
}

func (m *ZjhRoom) GetBanker() *User {
	if m != nil {
		return m.Banker
	}
	return nil
}

func (m *ZjhRoom) GetMe() *User {
	if m != nil {
		return m.Me
	}
	return nil
}

// 押注：押注区betzone=1,2,3,4   押注金额betAmount （若当前时刻已停止押注，返回失败）
type ZjhBet struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	BetAmount        *int32       `protobuf:"varint,2,opt,name=betAmount" json:"betAmount,omitempty"`
	BetzoneA         *int32       `protobuf:"varint,3,opt,name=betzoneA" json:"betzoneA,omitempty"`
	BetzoneB         *int32       `protobuf:"varint,4,opt,name=betzoneB" json:"betzoneB,omitempty"`
	BetzoneC         *int32       `protobuf:"varint,5,opt,name=betzoneC" json:"betzoneC,omitempty"`
	BetzoneD         *int32       `protobuf:"varint,6,opt,name=betzoneD" json:"betzoneD,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ZjhBet) Reset()                    { *m = ZjhBet{} }
func (m *ZjhBet) String() string            { return proto.CompactTextString(m) }
func (*ZjhBet) ProtoMessage()               {}
func (*ZjhBet) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *ZjhBet) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ZjhBet) GetBetAmount() int32 {
	if m != nil && m.BetAmount != nil {
		return *m.BetAmount
	}
	return 0
}

func (m *ZjhBet) GetBetzoneA() int32 {
	if m != nil && m.BetzoneA != nil {
		return *m.BetzoneA
	}
	return 0
}

func (m *ZjhBet) GetBetzoneB() int32 {
	if m != nil && m.BetzoneB != nil {
		return *m.BetzoneB
	}
	return 0
}

func (m *ZjhBet) GetBetzoneC() int32 {
	if m != nil && m.BetzoneC != nil {
		return *m.BetzoneC
	}
	return 0
}

func (m *ZjhBet) GetBetzoneD() int32 {
	if m != nil && m.BetzoneD != nil {
		return *m.BetzoneD
	}
	return 0
}

// 开奖,广播
type ZjhLottery struct {
	// 牌面
	Header *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Pbank  *ZjhPai      `protobuf:"bytes,2,opt,name=pbank" json:"pbank,omitempty"`
	Pa     *ZjhPai      `protobuf:"bytes,3,opt,name=pa" json:"pa,omitempty"`
	Pb     *ZjhPai      `protobuf:"bytes,4,opt,name=pb" json:"pb,omitempty"`
	Pc     *ZjhPai      `protobuf:"bytes,5,opt,name=pc" json:"pc,omitempty"`
	Pd     *ZjhPai      `protobuf:"bytes,6,opt,name=pd" json:"pd,omitempty"`
	// 自己的输赢
	Balance          *int32 `protobuf:"varint,7,opt,name=balance" json:"balance,omitempty"`
	WinAmount        *int32 `protobuf:"varint,8,opt,name=winAmount" json:"winAmount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ZjhLottery) Reset()                    { *m = ZjhLottery{} }
func (m *ZjhLottery) String() string            { return proto.CompactTextString(m) }
func (*ZjhLottery) ProtoMessage()               {}
func (*ZjhLottery) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *ZjhLottery) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ZjhLottery) GetPbank() *ZjhPai {
	if m != nil {
		return m.Pbank
	}
	return nil
}

func (m *ZjhLottery) GetPa() *ZjhPai {
	if m != nil {
		return m.Pa
	}
	return nil
}

func (m *ZjhLottery) GetPb() *ZjhPai {
	if m != nil {
		return m.Pb
	}
	return nil
}

func (m *ZjhLottery) GetPc() *ZjhPai {
	if m != nil {
		return m.Pc
	}
	return nil
}

func (m *ZjhLottery) GetPd() *ZjhPai {
	if m != nil {
		return m.Pd
	}
	return nil
}

func (m *ZjhLottery) GetBalance() int32 {
	if m != nil && m.Balance != nil {
		return *m.Balance
	}
	return 0
}

func (m *ZjhLottery) GetWinAmount() int32 {
	if m != nil && m.WinAmount != nil {
		return *m.WinAmount
	}
	return 0
}

type ZjhPai struct {
	PaiType          *int32 `protobuf:"varint,1,opt,name=PaiType" json:"PaiType,omitempty"`
	LotteryType      *int32 `protobuf:"varint,2,opt,name=lotteryType" json:"lotteryType,omitempty"`
	Result           *bool  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	Pai1             *int32 `protobuf:"varint,4,opt,name=Pai1" json:"Pai1,omitempty"`
	Pai2             *int32 `protobuf:"varint,5,opt,name=Pai2" json:"Pai2,omitempty"`
	Pai3             *int32 `protobuf:"varint,6,opt,name=Pai3" json:"Pai3,omitempty"`
	WinAmount        *int32 `protobuf:"varint,7,opt,name=winAmount" json:"winAmount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ZjhPai) Reset()                    { *m = ZjhPai{} }
func (m *ZjhPai) String() string            { return proto.CompactTextString(m) }
func (*ZjhPai) ProtoMessage()               {}
func (*ZjhPai) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *ZjhPai) GetPaiType() int32 {
	if m != nil && m.PaiType != nil {
		return *m.PaiType
	}
	return 0
}

func (m *ZjhPai) GetLotteryType() int32 {
	if m != nil && m.LotteryType != nil {
		return *m.LotteryType
	}
	return 0
}

func (m *ZjhPai) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func (m *ZjhPai) GetPai1() int32 {
	if m != nil && m.Pai1 != nil {
		return *m.Pai1
	}
	return 0
}

func (m *ZjhPai) GetPai2() int32 {
	if m != nil && m.Pai2 != nil {
		return *m.Pai2
	}
	return 0
}

func (m *ZjhPai) GetPai3() int32 {
	if m != nil && m.Pai3 != nil {
		return *m.Pai3
	}
	return 0
}

func (m *ZjhPai) GetWinAmount() int32 {
	if m != nil && m.WinAmount != nil {
		return *m.WinAmount
	}
	return 0
}

type ZjhQueryNoSeatUser struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ZjhQueryNoSeatUser) Reset()                    { *m = ZjhQueryNoSeatUser{} }
func (m *ZjhQueryNoSeatUser) String() string            { return proto.CompactTextString(m) }
func (*ZjhQueryNoSeatUser) ProtoMessage()               {}
func (*ZjhQueryNoSeatUser) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *ZjhQueryNoSeatUser) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// 座位
type ZjhReqSeat struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ZjhReqSeat) Reset()                    { *m = ZjhReqSeat{} }
func (m *ZjhReqSeat) String() string            { return proto.CompactTextString(m) }
func (*ZjhReqSeat) ProtoMessage()               {}
func (*ZjhReqSeat) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

func (m *ZjhReqSeat) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ZjhMsg struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ZjhMsg) Reset()                    { *m = ZjhMsg{} }
func (m *ZjhMsg) String() string            { return proto.CompactTextString(m) }
func (*ZjhMsg) ProtoMessage()               {}
func (*ZjhMsg) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *ZjhMsg) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*ZjhRoom)(nil), "bbproto.ZjhRoom")
	proto.RegisterType((*ZjhBet)(nil), "bbproto.ZjhBet")
	proto.RegisterType((*ZjhLottery)(nil), "bbproto.ZjhLottery")
	proto.RegisterType((*ZjhPai)(nil), "bbproto.ZjhPai")
	proto.RegisterType((*ZjhQueryNoSeatUser)(nil), "bbproto.ZjhQueryNoSeatUser")
	proto.RegisterType((*ZjhReqSeat)(nil), "bbproto.ZjhReqSeat")
	proto.RegisterType((*ZjhMsg)(nil), "bbproto.ZjhMsg")
}

var fileDescriptor10 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x95, 0xda, 0x42, 0x9d, 0xaa, 0x55, 0xf4, 0x80, 0x1a, 0x8d, 0x21, 0x1e, 0x3c, 0x91, 0x88,
	0x37, 0x6f, 0xad, 0x1e, 0x3c, 0xa8, 0xc1, 0xaa, 0x17, 0x6f, 0xbb, 0xed, 0x44, 0xfa, 0xc5, 0x52,
	0x58, 0x62, 0x5a, 0x7f, 0x81, 0xf1, 0x9f, 0xfa, 0x2b, 0x5c, 0x86, 0x4d, 0xad, 0x09, 0x26, 0x5c,
	0xda, 0xd9, 0xf7, 0xe6, 0xe3, 0xcd, 0x1b, 0xa0, 0xbd, 0x08, 0xd9, 0x68, 0x18, 0x85, 0x19, 0xf3,
	0xe2, 0x44, 0x48, 0x61, 0x5b, 0x9c, 0x53, 0x70, 0x08, 0x9c, 0xa5, 0xe8, 0xe9, 0x38, 0x4b, 0x31,
	0x29, 0x62, 0xf7, 0xcb, 0x00, 0xeb, 0x75, 0x14, 0xf6, 0x84, 0x98, 0xda, 0x67, 0x60, 0x86, 0xc8,
	0x06, 0x98, 0x38, 0xc6, 0xa9, 0x71, 0xde, 0xf2, 0xf7, 0x3d, 0x5d, 0xed, 0x05, 0xf9, 0xef, 0x2d,
	0x71, 0x76, 0x1b, 0xac, 0x04, 0x67, 0xcf, 0xf3, 0x18, 0x9d, 0x9a, 0x4a, 0x6b, 0xe4, 0xc0, 0x88,
	0xf5, 0xc7, 0xb1, 0x90, 0xce, 0x3a, 0x01, 0xc7, 0x60, 0x72, 0x16, 0x8d, 0x55, 0x9f, 0x3a, 0xf5,
	0xd9, 0x5a, 0xf6, 0x79, 0x51, 0x83, 0xed, 0x03, 0xa8, 0x4d, 0xd1, 0x69, 0x94, 0x50, 0xee, 0xa7,
	0x01, 0xa6, 0x52, 0xd3, 0x45, 0x59, 0x51, 0xcc, 0x2e, 0x6c, 0x70, 0x94, 0x9d, 0xa9, 0xc8, 0x22,
	0xa9, 0xe5, 0xec, 0x40, 0x53, 0x41, 0x0b, 0x11, 0x61, 0x47, 0xeb, 0xf9, 0x45, 0xba, 0xa4, 0x68,
	0x15, 0xb9, 0x26, 0x21, 0xab, 0xc8, 0x8d, 0x63, 0xe6, 0x88, 0xfb, 0x6d, 0x00, 0x28, 0x2d, 0x77,
	0x42, 0x4a, 0x4c, 0xe6, 0x15, 0xf5, 0x9c, 0x40, 0x23, 0xce, 0x77, 0x27, 0x2d, 0x2d, 0xbf, 0xbd,
	0x4c, 0x52, 0x9d, 0x02, 0x36, 0xb4, 0x8f, 0xa0, 0x16, 0x33, 0x92, 0xf5, 0x0f, 0xc9, 0xb5, 0x67,
	0xa5, 0x64, 0x5f, 0xbb, 0x56, 0x4a, 0x0e, 0x48, 0x77, 0x09, 0xa9, 0xee, 0xc3, 0xd9, 0x84, 0x45,
	0x7d, 0x74, 0x2c, 0xda, 0x55, 0x99, 0xf6, 0x3e, 0x8c, 0xb4, 0x69, 0x4d, 0x5a, 0xf6, 0x83, 0x7c,
	0xd7, 0xd9, 0xea, 0x8f, 0xce, 0x6b, 0x50, 0xf6, 0x1e, 0xb4, 0x26, 0x85, 0x07, 0x2b, 0x37, 0xdf,
	0x06, 0x33, 0xc1, 0x34, 0x9b, 0x14, 0x27, 0x6f, 0xda, 0x9b, 0x50, 0x57, 0x55, 0x17, 0xda, 0xde,
	0xe2, 0xe5, 0x6b, 0x6b, 0x8b, 0xd7, 0x65, 0x61, 0xeb, 0xdf, 0xe1, 0xa4, 0xc7, 0xbd, 0x02, 0x5b,
	0x0d, 0x7f, 0xcc, 0xd4, 0x88, 0x07, 0xf1, 0x84, 0x4c, 0xd2, 0x67, 0x52, 0xc9, 0x70, 0xd7, 0xa7,
	0x23, 0xf5, 0x70, 0x96, 0xd7, 0x55, 0xac, 0xf1, 0x68, 0xd9, 0xfb, 0xf4, 0xad, 0x5a, 0x7e, 0xb0,
	0x16, 0x18, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0x05, 0x45, 0xee, 0x5a, 0x03, 0x00, 0x00,
}
